// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_10u_config11_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer10_out_dout,
        layer10_out_empty_n,
        layer10_out_read,
        layer11_out_din,
        layer11_out_full_n,
        layer11_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [511:0] layer10_out_dout;
input   layer10_out_empty_n;
output   layer10_out_read;
output  [159:0] layer11_out_din;
input   layer11_out_full_n;
output   layer11_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer10_out_read;
reg layer11_out_write;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln42_fu_1509_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
reg   [0:0] ap_phi_mux_do_init_phi_fu_504_p6;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg   [0:0] icmp_ln42_reg_2807;
reg   [0:0] icmp_ln42_reg_2807_pp0_iter2_reg;
reg    ap_block_state5_pp0_stage0_iter3;
reg    ap_enable_reg_pp0_iter3;
reg    ap_block_pp0_stage0_11001;
wire   [8:0] w11_address0;
reg    w11_ce0;
wire  signed [11:0] w11_q0;
wire   [8:0] w11_address1;
reg    w11_ce1;
wire  signed [11:0] w11_q1;
wire   [8:0] w11_address2;
reg    w11_ce2;
wire  signed [11:0] w11_q2;
wire   [8:0] w11_address3;
reg    w11_ce3;
wire  signed [11:0] w11_q3;
wire   [8:0] w11_address4;
reg    w11_ce4;
wire  signed [11:0] w11_q4;
wire   [8:0] w11_address5;
reg    w11_ce5;
wire  signed [11:0] w11_q5;
wire   [8:0] w11_address6;
reg    w11_ce6;
wire  signed [11:0] w11_q6;
wire   [8:0] w11_address7;
reg    w11_ce7;
wire  signed [11:0] w11_q7;
wire   [8:0] w11_address8;
reg    w11_ce8;
wire  signed [11:0] w11_q8;
wire   [8:0] w11_address9;
reg    w11_ce9;
wire  signed [11:0] w11_q9;
wire   [8:0] w11_address10;
reg    w11_ce10;
wire  signed [11:0] w11_q10;
wire   [8:0] w11_address11;
reg    w11_ce11;
wire  signed [11:0] w11_q11;
wire   [8:0] w11_address12;
reg    w11_ce12;
wire  signed [11:0] w11_q12;
wire   [8:0] w11_address13;
reg    w11_ce13;
wire  signed [11:0] w11_q13;
wire   [8:0] w11_address14;
reg    w11_ce14;
wire  signed [11:0] w11_q14;
wire   [8:0] w11_address15;
reg    w11_ce15;
wire  signed [11:0] w11_q15;
wire   [8:0] w11_address16;
reg    w11_ce16;
wire  signed [11:0] w11_q16;
wire   [8:0] w11_address17;
reg    w11_ce17;
wire  signed [11:0] w11_q17;
wire   [8:0] w11_address18;
reg    w11_ce18;
wire  signed [11:0] w11_q18;
wire   [8:0] w11_address19;
reg    w11_ce19;
wire  signed [11:0] w11_q19;
reg    layer10_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer11_out_blk_n;
reg   [0:0] do_init_reg_500;
reg   [3:0] in_index117_reg_516;
reg   [3:0] in_index117_reg_516_pp0_iter1_reg;
reg   [15:0] data_25_phi_reg_979;
reg   [15:0] data_24_phi_reg_991;
reg   [15:0] data_23_phi_reg_1003;
reg   [15:0] data_22_phi_reg_1015;
reg   [15:0] data_21_phi_reg_1027;
reg   [15:0] data_20_phi_reg_1039;
reg   [15:0] data_19_phi_reg_1051;
reg   [15:0] data_18_phi_reg_1063;
reg   [15:0] data_17_phi_reg_1075;
reg   [15:0] data_16_phi_reg_1087;
reg   [15:0] data_15_phi_reg_1099;
reg   [15:0] data_14_phi_reg_1111;
reg   [15:0] data_13_phi_reg_1123;
reg   [15:0] data_12_phi_reg_1135;
reg   [15:0] data_11_phi_reg_1147;
reg   [15:0] data_8_phi_reg_1159;
reg   [15:0] data_7_phi_reg_1171;
reg   [15:0] data_6_phi_reg_1183;
reg   [15:0] data_5_phi_reg_1195;
reg   [15:0] data_4_phi_reg_1207;
reg   [15:0] data_3_phi_reg_1219;
reg   [15:0] data_2_phi_reg_1231;
reg   [15:0] data_1_phi_reg_1243;
reg   [15:0] data_10_phi_reg_1255;
reg   [15:0] data_9_phi_reg_1267;
reg   [15:0] data_37_phi_reg_1279;
reg   [15:0] data_36_phi_reg_1291;
reg   [15:0] data_35_phi_reg_1303;
reg   [15:0] data_34_phi_reg_1315;
reg   [15:0] data_33_phi_reg_1327;
reg   [15:0] data_32_phi_reg_1339;
reg   [15:0] p_phi_reg_1351;
reg   [11:0] conv_i2_i_154_i_i137_reg_1363;
reg   [11:0] conv_i2_i_355_i_i135_reg_1377;
reg   [11:0] conv_i2_i_556_i_i133_reg_1391;
reg   [11:0] conv_i2_i_757_i_i131_reg_1405;
reg   [11:0] conv_i2_i_958_i_i129_reg_1419;
reg   [11:0] conv_i2_i_1159_i_i127_reg_1433;
reg   [11:0] conv_i2_i_1360_i_i125_reg_1447;
reg   [11:0] conv_i2_i_1561_i_i123_reg_1461;
reg   [11:0] conv_i2_i_1762_i_i121_reg_1475;
reg   [11:0] conv_i2_i_1963_i_i119_reg_1489;
wire   [3:0] in_index_fu_1503_p2;
reg   [3:0] in_index_reg_2802;
reg   [0:0] icmp_ln42_reg_2807_pp0_iter1_reg;
wire   [15:0] data_fu_1515_p1;
reg   [11:0] trunc_ln_reg_3071;
reg   [11:0] trunc_ln53_s_reg_3076;
reg   [11:0] trunc_ln53_63_reg_3081;
reg   [11:0] trunc_ln53_64_reg_3086;
reg   [11:0] trunc_ln53_65_reg_3091;
reg   [11:0] trunc_ln53_66_reg_3096;
reg   [11:0] trunc_ln53_67_reg_3101;
reg   [11:0] trunc_ln53_68_reg_3106;
reg   [11:0] trunc_ln53_69_reg_3111;
reg   [11:0] trunc_ln53_70_reg_3116;
reg   [11:0] trunc_ln53_71_reg_3121;
reg   [11:0] trunc_ln53_72_reg_3126;
reg   [11:0] trunc_ln53_73_reg_3131;
reg   [11:0] trunc_ln53_74_reg_3136;
reg   [11:0] trunc_ln53_75_reg_3141;
reg   [11:0] trunc_ln53_76_reg_3146;
reg   [11:0] trunc_ln53_77_reg_3151;
reg   [11:0] trunc_ln53_78_reg_3156;
reg   [11:0] trunc_ln53_79_reg_3161;
reg   [11:0] trunc_ln53_80_reg_3166;
wire   [11:0] x_fu_2565_p2;
wire   [11:0] x_11_fu_2575_p2;
wire   [11:0] x_12_fu_2585_p2;
wire   [11:0] x_13_fu_2595_p2;
wire   [11:0] x_14_fu_2605_p2;
wire   [11:0] x_15_fu_2615_p2;
wire   [11:0] x_16_fu_2625_p2;
wire   [11:0] x_17_fu_2635_p2;
wire   [11:0] x_18_fu_2645_p2;
wire   [11:0] x_19_fu_2655_p2;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg   [3:0] ap_phi_mux_in_index117_phi_fu_520_p6;
reg   [15:0] ap_phi_mux_data_25_phi_phi_fu_983_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_25_phi_reg_979;
reg   [15:0] ap_phi_reg_pp0_iter1_data_25_phi_reg_979;
reg   [15:0] ap_phi_reg_pp0_iter2_data_25_phi_reg_979;
reg   [15:0] ap_phi_mux_data_24_phi_phi_fu_995_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_24_phi_reg_991;
reg   [15:0] ap_phi_reg_pp0_iter1_data_24_phi_reg_991;
reg   [15:0] ap_phi_reg_pp0_iter2_data_24_phi_reg_991;
reg   [15:0] ap_phi_mux_data_23_phi_phi_fu_1007_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_23_phi_reg_1003;
reg   [15:0] ap_phi_reg_pp0_iter1_data_23_phi_reg_1003;
reg   [15:0] ap_phi_reg_pp0_iter2_data_23_phi_reg_1003;
reg   [15:0] ap_phi_mux_data_22_phi_phi_fu_1019_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_22_phi_reg_1015;
reg   [15:0] ap_phi_reg_pp0_iter1_data_22_phi_reg_1015;
reg   [15:0] ap_phi_reg_pp0_iter2_data_22_phi_reg_1015;
reg   [15:0] ap_phi_mux_data_21_phi_phi_fu_1031_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_21_phi_reg_1027;
reg   [15:0] ap_phi_reg_pp0_iter1_data_21_phi_reg_1027;
reg   [15:0] ap_phi_reg_pp0_iter2_data_21_phi_reg_1027;
reg   [15:0] ap_phi_mux_data_20_phi_phi_fu_1043_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_20_phi_reg_1039;
reg   [15:0] ap_phi_reg_pp0_iter1_data_20_phi_reg_1039;
reg   [15:0] ap_phi_reg_pp0_iter2_data_20_phi_reg_1039;
reg   [15:0] ap_phi_mux_data_19_phi_phi_fu_1055_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_19_phi_reg_1051;
reg   [15:0] ap_phi_reg_pp0_iter1_data_19_phi_reg_1051;
reg   [15:0] ap_phi_reg_pp0_iter2_data_19_phi_reg_1051;
reg   [15:0] ap_phi_mux_data_18_phi_phi_fu_1067_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_18_phi_reg_1063;
reg   [15:0] ap_phi_reg_pp0_iter1_data_18_phi_reg_1063;
reg   [15:0] ap_phi_reg_pp0_iter2_data_18_phi_reg_1063;
reg   [15:0] ap_phi_mux_data_17_phi_phi_fu_1079_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_17_phi_reg_1075;
reg   [15:0] ap_phi_reg_pp0_iter1_data_17_phi_reg_1075;
reg   [15:0] ap_phi_reg_pp0_iter2_data_17_phi_reg_1075;
reg   [15:0] ap_phi_mux_data_16_phi_phi_fu_1091_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_16_phi_reg_1087;
reg   [15:0] ap_phi_reg_pp0_iter1_data_16_phi_reg_1087;
reg   [15:0] ap_phi_reg_pp0_iter2_data_16_phi_reg_1087;
reg   [15:0] ap_phi_mux_data_15_phi_phi_fu_1103_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_15_phi_reg_1099;
reg   [15:0] ap_phi_reg_pp0_iter1_data_15_phi_reg_1099;
reg   [15:0] ap_phi_reg_pp0_iter2_data_15_phi_reg_1099;
reg   [15:0] ap_phi_mux_data_14_phi_phi_fu_1115_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_14_phi_reg_1111;
reg   [15:0] ap_phi_reg_pp0_iter1_data_14_phi_reg_1111;
reg   [15:0] ap_phi_reg_pp0_iter2_data_14_phi_reg_1111;
reg   [15:0] ap_phi_mux_data_13_phi_phi_fu_1127_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_13_phi_reg_1123;
reg   [15:0] ap_phi_reg_pp0_iter1_data_13_phi_reg_1123;
reg   [15:0] ap_phi_reg_pp0_iter2_data_13_phi_reg_1123;
reg   [15:0] ap_phi_mux_data_12_phi_phi_fu_1139_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_12_phi_reg_1135;
reg   [15:0] ap_phi_reg_pp0_iter1_data_12_phi_reg_1135;
reg   [15:0] ap_phi_reg_pp0_iter2_data_12_phi_reg_1135;
reg   [15:0] ap_phi_mux_data_11_phi_phi_fu_1151_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_11_phi_reg_1147;
reg   [15:0] ap_phi_reg_pp0_iter1_data_11_phi_reg_1147;
reg   [15:0] ap_phi_reg_pp0_iter2_data_11_phi_reg_1147;
reg   [15:0] ap_phi_mux_data_8_phi_phi_fu_1163_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_8_phi_reg_1159;
reg   [15:0] ap_phi_reg_pp0_iter1_data_8_phi_reg_1159;
reg   [15:0] ap_phi_reg_pp0_iter2_data_8_phi_reg_1159;
reg   [15:0] ap_phi_mux_data_7_phi_phi_fu_1175_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_7_phi_reg_1171;
reg   [15:0] ap_phi_reg_pp0_iter1_data_7_phi_reg_1171;
reg   [15:0] ap_phi_reg_pp0_iter2_data_7_phi_reg_1171;
reg   [15:0] ap_phi_mux_data_6_phi_phi_fu_1187_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_6_phi_reg_1183;
reg   [15:0] ap_phi_reg_pp0_iter1_data_6_phi_reg_1183;
reg   [15:0] ap_phi_reg_pp0_iter2_data_6_phi_reg_1183;
reg   [15:0] ap_phi_mux_data_5_phi_phi_fu_1199_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_5_phi_reg_1195;
reg   [15:0] ap_phi_reg_pp0_iter1_data_5_phi_reg_1195;
reg   [15:0] ap_phi_reg_pp0_iter2_data_5_phi_reg_1195;
reg   [15:0] ap_phi_mux_data_4_phi_phi_fu_1211_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_4_phi_reg_1207;
reg   [15:0] ap_phi_reg_pp0_iter1_data_4_phi_reg_1207;
reg   [15:0] ap_phi_reg_pp0_iter2_data_4_phi_reg_1207;
reg   [15:0] ap_phi_mux_data_3_phi_phi_fu_1223_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_3_phi_reg_1219;
reg   [15:0] ap_phi_reg_pp0_iter1_data_3_phi_reg_1219;
reg   [15:0] ap_phi_reg_pp0_iter2_data_3_phi_reg_1219;
reg   [15:0] ap_phi_mux_data_2_phi_phi_fu_1235_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_2_phi_reg_1231;
reg   [15:0] ap_phi_reg_pp0_iter1_data_2_phi_reg_1231;
reg   [15:0] ap_phi_reg_pp0_iter2_data_2_phi_reg_1231;
reg   [15:0] ap_phi_mux_data_1_phi_phi_fu_1247_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_1_phi_reg_1243;
reg   [15:0] ap_phi_reg_pp0_iter1_data_1_phi_reg_1243;
reg   [15:0] ap_phi_reg_pp0_iter2_data_1_phi_reg_1243;
reg   [15:0] ap_phi_mux_data_10_phi_phi_fu_1259_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_10_phi_reg_1255;
reg   [15:0] ap_phi_reg_pp0_iter1_data_10_phi_reg_1255;
reg   [15:0] ap_phi_reg_pp0_iter2_data_10_phi_reg_1255;
reg   [15:0] ap_phi_mux_data_9_phi_phi_fu_1271_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_9_phi_reg_1267;
reg   [15:0] ap_phi_reg_pp0_iter1_data_9_phi_reg_1267;
reg   [15:0] ap_phi_reg_pp0_iter2_data_9_phi_reg_1267;
reg   [15:0] ap_phi_mux_data_37_phi_phi_fu_1283_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_37_phi_reg_1279;
reg   [15:0] ap_phi_reg_pp0_iter1_data_37_phi_reg_1279;
reg   [15:0] ap_phi_reg_pp0_iter2_data_37_phi_reg_1279;
reg   [15:0] ap_phi_mux_data_36_phi_phi_fu_1295_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_36_phi_reg_1291;
reg   [15:0] ap_phi_reg_pp0_iter1_data_36_phi_reg_1291;
reg   [15:0] ap_phi_reg_pp0_iter2_data_36_phi_reg_1291;
reg   [15:0] ap_phi_mux_data_35_phi_phi_fu_1307_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_35_phi_reg_1303;
reg   [15:0] ap_phi_reg_pp0_iter1_data_35_phi_reg_1303;
reg   [15:0] ap_phi_reg_pp0_iter2_data_35_phi_reg_1303;
reg   [15:0] ap_phi_mux_data_34_phi_phi_fu_1319_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_34_phi_reg_1315;
reg   [15:0] ap_phi_reg_pp0_iter1_data_34_phi_reg_1315;
reg   [15:0] ap_phi_reg_pp0_iter2_data_34_phi_reg_1315;
reg   [15:0] ap_phi_mux_data_33_phi_phi_fu_1331_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_33_phi_reg_1327;
reg   [15:0] ap_phi_reg_pp0_iter1_data_33_phi_reg_1327;
reg   [15:0] ap_phi_reg_pp0_iter2_data_33_phi_reg_1327;
reg   [15:0] ap_phi_mux_data_32_phi_phi_fu_1343_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_data_32_phi_reg_1339;
reg   [15:0] ap_phi_reg_pp0_iter1_data_32_phi_reg_1339;
reg   [15:0] ap_phi_reg_pp0_iter2_data_32_phi_reg_1339;
reg   [15:0] ap_phi_mux_p_phi_phi_fu_1355_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_p_phi_reg_1351;
reg   [15:0] ap_phi_reg_pp0_iter1_p_phi_reg_1351;
reg   [15:0] ap_phi_reg_pp0_iter2_p_phi_reg_1351;
wire   [63:0] zext_ln42_fu_1829_p1;
wire   [63:0] p_cast88_cast_fu_1846_p1;
wire   [63:0] p_cast89_cast_fu_1863_p1;
wire   [63:0] p_cast90_cast_cast_fu_1872_p1;
wire   [63:0] p_cast91_cast_fu_1885_p1;
wire   [63:0] p_cast92_cast_fu_1898_p1;
wire   [63:0] p_cast93_cast_cast_fu_1915_p1;
wire   [63:0] p_cast94_cast_cast_fu_1924_p1;
wire   [63:0] p_cast95_cast_fu_1937_p1;
wire   [63:0] p_cast96_cast_fu_1950_p1;
wire   [63:0] p_cast97_cast_fu_1963_p1;
wire   [63:0] p_cast98_cast_fu_1976_p1;
wire   [63:0] p_cast99_cast_cast_fu_1993_p1;
wire   [63:0] p_cast100_cast_cast_fu_2002_p1;
wire   [63:0] p_cast101_cast_cast_fu_2011_p1;
wire   [63:0] p_cast102_cast_cast_fu_2020_p1;
wire   [63:0] p_cast103_cast_fu_2033_p1;
wire   [63:0] p_cast104_cast_fu_2046_p1;
wire   [63:0] p_cast105_cast_fu_2059_p1;
wire   [63:0] p_cast106_cast_fu_2072_p1;
reg    ap_block_pp0_stage0_01001;
wire  signed [4:0] p_cast_fu_1838_p3;
wire   [5:0] p_cast1_fu_1855_p3;
wire  signed [5:0] p_cast90_cast_fu_1868_p1;
wire   [6:0] p_cast2_fu_1877_p3;
wire  signed [6:0] p_cast3_fu_1890_p3;
wire   [4:0] add_ln55261_fu_1834_p1;
wire  signed [5:0] tmp_s_fu_1903_p3;
wire  signed [6:0] p_cast93_cast_fu_1911_p1;
wire  signed [6:0] p_cast94_cast_fu_1920_p1;
wire   [7:0] p_cast4_fu_1929_p3;
wire   [7:0] p_cast5_fu_1942_p3;
wire   [7:0] p_cast6_fu_1955_p3;
wire   [7:0] p_cast7_fu_1968_p3;
wire   [5:0] add_ln55_63262_fu_1851_p1;
wire   [6:0] tmp_28_fu_1981_p3;
wire  signed [7:0] p_cast99_cast_fu_1989_p1;
wire  signed [7:0] p_cast100_cast_fu_1998_p1;
wire  signed [7:0] p_cast101_cast_fu_2007_p1;
wire  signed [7:0] p_cast102_cast_fu_2016_p1;
wire   [8:0] p_cast8_fu_2025_p3;
wire   [8:0] p_cast9_fu_2038_p3;
wire   [8:0] p_cast10_fu_2051_p3;
wire   [8:0] p_cast11_fu_2064_p3;
wire   [15:0] a_fu_2077_p18;
wire  signed [15:0] mul_ln53_fu_2123_p1;
wire  signed [23:0] sext_ln73_72_fu_2119_p1;
wire   [23:0] mul_ln53_fu_2123_p2;
wire   [15:0] a_4_fu_2139_p18;
wire  signed [15:0] mul_ln53_66_fu_2185_p1;
wire  signed [23:0] sext_ln73_74_fu_2181_p1;
wire   [23:0] mul_ln53_66_fu_2185_p2;
wire  signed [15:0] mul_ln53_67_fu_2205_p1;
wire   [23:0] mul_ln53_67_fu_2205_p2;
wire  signed [15:0] mul_ln53_68_fu_2225_p1;
wire   [23:0] mul_ln53_68_fu_2225_p2;
wire  signed [15:0] mul_ln53_69_fu_2245_p1;
wire   [23:0] mul_ln53_69_fu_2245_p2;
wire  signed [15:0] mul_ln53_70_fu_2265_p1;
wire   [23:0] mul_ln53_70_fu_2265_p2;
wire  signed [15:0] mul_ln53_71_fu_2285_p1;
wire   [23:0] mul_ln53_71_fu_2285_p2;
wire  signed [15:0] mul_ln53_72_fu_2305_p1;
wire   [23:0] mul_ln53_72_fu_2305_p2;
wire  signed [15:0] mul_ln53_73_fu_2325_p1;
wire   [23:0] mul_ln53_73_fu_2325_p2;
wire  signed [15:0] mul_ln53_74_fu_2345_p1;
wire   [23:0] mul_ln53_74_fu_2345_p2;
wire  signed [15:0] mul_ln53_75_fu_2365_p1;
wire   [23:0] mul_ln53_75_fu_2365_p2;
wire  signed [15:0] mul_ln53_76_fu_2385_p1;
wire   [23:0] mul_ln53_76_fu_2385_p2;
wire  signed [15:0] mul_ln53_77_fu_2405_p1;
wire   [23:0] mul_ln53_77_fu_2405_p2;
wire  signed [15:0] mul_ln53_78_fu_2425_p1;
wire   [23:0] mul_ln53_78_fu_2425_p2;
wire  signed [15:0] mul_ln53_79_fu_2445_p1;
wire   [23:0] mul_ln53_79_fu_2445_p2;
wire  signed [15:0] mul_ln53_80_fu_2465_p1;
wire   [23:0] mul_ln53_80_fu_2465_p2;
wire  signed [15:0] mul_ln53_81_fu_2485_p1;
wire   [23:0] mul_ln53_81_fu_2485_p2;
wire  signed [15:0] mul_ln53_82_fu_2505_p1;
wire   [23:0] mul_ln53_82_fu_2505_p2;
wire  signed [15:0] mul_ln53_83_fu_2525_p1;
wire   [23:0] mul_ln53_83_fu_2525_p2;
wire  signed [15:0] mul_ln53_84_fu_2545_p1;
wire   [23:0] mul_ln53_84_fu_2545_p2;
wire   [11:0] add_ln53_fu_2561_p2;
wire   [11:0] add_ln53_67_fu_2571_p2;
wire   [11:0] add_ln53_69_fu_2581_p2;
wire   [11:0] add_ln53_71_fu_2591_p2;
wire   [11:0] add_ln53_73_fu_2601_p2;
wire   [11:0] add_ln53_75_fu_2611_p2;
wire   [11:0] add_ln53_77_fu_2621_p2;
wire   [11:0] add_ln53_79_fu_2631_p2;
wire   [11:0] add_ln53_81_fu_2641_p2;
wire   [11:0] add_ln53_83_fu_2651_p2;
wire   [13:0] res_fu_2661_p3;
wire   [13:0] res_37_fu_2673_p3;
wire   [13:0] res_30_fu_2685_p3;
wire   [13:0] res_31_fu_2697_p3;
wire   [13:0] res_32_fu_2709_p3;
wire   [13:0] res_33_fu_2721_p3;
wire   [13:0] res_34_fu_2733_p3;
wire   [13:0] res_35_fu_2745_p3;
wire   [13:0] res_36_fu_2757_p3;
wire  signed [15:0] sext_ln110_16_fu_2765_p1;
wire  signed [15:0] sext_ln110_15_fu_2753_p1;
wire  signed [15:0] sext_ln110_14_fu_2741_p1;
wire  signed [15:0] sext_ln110_13_fu_2729_p1;
wire  signed [15:0] sext_ln110_12_fu_2717_p1;
wire  signed [15:0] sext_ln110_11_fu_2705_p1;
wire  signed [15:0] sext_ln110_10_fu_2693_p1;
wire  signed [15:0] sext_ln110_9_fu_2681_p1;
wire  signed [15:0] sext_ln110_fu_2669_p1;
wire   [157:0] or_ln77_s_fu_2769_p12;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_155;
reg    ap_condition_511;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_10u_config11_s_w11_ROM_AUTzec #(
    .DataWidth( 12 ),
    .AddressRange( 320 ),
    .AddressWidth( 9 ))
w11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w11_address0),
    .ce0(w11_ce0),
    .q0(w11_q0),
    .address1(w11_address1),
    .ce1(w11_ce1),
    .q1(w11_q1),
    .address2(w11_address2),
    .ce2(w11_ce2),
    .q2(w11_q2),
    .address3(w11_address3),
    .ce3(w11_ce3),
    .q3(w11_q3),
    .address4(w11_address4),
    .ce4(w11_ce4),
    .q4(w11_q4),
    .address5(w11_address5),
    .ce5(w11_ce5),
    .q5(w11_q5),
    .address6(w11_address6),
    .ce6(w11_ce6),
    .q6(w11_q6),
    .address7(w11_address7),
    .ce7(w11_ce7),
    .q7(w11_q7),
    .address8(w11_address8),
    .ce8(w11_ce8),
    .q8(w11_q8),
    .address9(w11_address9),
    .ce9(w11_ce9),
    .q9(w11_q9),
    .address10(w11_address10),
    .ce10(w11_ce10),
    .q10(w11_q10),
    .address11(w11_address11),
    .ce11(w11_ce11),
    .q11(w11_q11),
    .address12(w11_address12),
    .ce12(w11_ce12),
    .q12(w11_q12),
    .address13(w11_address13),
    .ce13(w11_ce13),
    .q13(w11_q13),
    .address14(w11_address14),
    .ce14(w11_ce14),
    .q14(w11_q14),
    .address15(w11_address15),
    .ce15(w11_ce15),
    .q15(w11_q15),
    .address16(w11_address16),
    .ce16(w11_ce16),
    .q16(w11_q16),
    .address17(w11_address17),
    .ce17(w11_ce17),
    .q17(w11_q17),
    .address18(w11_address18),
    .ce18(w11_ce18),
    .q18(w11_q18),
    .address19(w11_address19),
    .ce19(w11_ce19),
    .q19(w11_q19)
);

myproject_mux_16_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
mux_16_4_16_1_1_U245(
    .din0(ap_phi_mux_p_phi_phi_fu_1355_p4),
    .din1(ap_phi_mux_data_10_phi_phi_fu_1259_p4),
    .din2(ap_phi_mux_data_1_phi_phi_fu_1247_p4),
    .din3(ap_phi_mux_data_2_phi_phi_fu_1235_p4),
    .din4(ap_phi_mux_data_3_phi_phi_fu_1223_p4),
    .din5(ap_phi_mux_data_4_phi_phi_fu_1211_p4),
    .din6(ap_phi_mux_data_5_phi_phi_fu_1199_p4),
    .din7(ap_phi_mux_data_6_phi_phi_fu_1187_p4),
    .din8(ap_phi_mux_data_7_phi_phi_fu_1175_p4),
    .din9(ap_phi_mux_data_8_phi_phi_fu_1163_p4),
    .din10(ap_phi_mux_data_32_phi_phi_fu_1343_p4),
    .din11(ap_phi_mux_data_33_phi_phi_fu_1331_p4),
    .din12(ap_phi_mux_data_34_phi_phi_fu_1319_p4),
    .din13(ap_phi_mux_data_35_phi_phi_fu_1307_p4),
    .din14(ap_phi_mux_data_11_phi_phi_fu_1151_p4),
    .din15(ap_phi_mux_data_12_phi_phi_fu_1139_p4),
    .din16(in_index117_reg_516_pp0_iter1_reg),
    .dout(a_fu_2077_p18)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U246(
    .din0(w11_q19),
    .din1(mul_ln53_fu_2123_p1),
    .dout(mul_ln53_fu_2123_p2)
);

myproject_mux_16_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
mux_16_4_16_1_1_U247(
    .din0(ap_phi_mux_data_13_phi_phi_fu_1127_p4),
    .din1(ap_phi_mux_data_14_phi_phi_fu_1115_p4),
    .din2(ap_phi_mux_data_15_phi_phi_fu_1103_p4),
    .din3(ap_phi_mux_data_16_phi_phi_fu_1091_p4),
    .din4(ap_phi_mux_data_17_phi_phi_fu_1079_p4),
    .din5(ap_phi_mux_data_18_phi_phi_fu_1067_p4),
    .din6(ap_phi_mux_data_19_phi_phi_fu_1055_p4),
    .din7(ap_phi_mux_data_20_phi_phi_fu_1043_p4),
    .din8(ap_phi_mux_data_21_phi_phi_fu_1031_p4),
    .din9(ap_phi_mux_data_22_phi_phi_fu_1019_p4),
    .din10(ap_phi_mux_data_23_phi_phi_fu_1007_p4),
    .din11(ap_phi_mux_data_24_phi_phi_fu_995_p4),
    .din12(ap_phi_mux_data_25_phi_phi_fu_983_p4),
    .din13(ap_phi_mux_data_36_phi_phi_fu_1295_p4),
    .din14(ap_phi_mux_data_37_phi_phi_fu_1283_p4),
    .din15(ap_phi_mux_data_9_phi_phi_fu_1271_p4),
    .din16(in_index117_reg_516_pp0_iter1_reg),
    .dout(a_4_fu_2139_p18)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U248(
    .din0(w11_q18),
    .din1(mul_ln53_66_fu_2185_p1),
    .dout(mul_ln53_66_fu_2185_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U249(
    .din0(w11_q17),
    .din1(mul_ln53_67_fu_2205_p1),
    .dout(mul_ln53_67_fu_2205_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U250(
    .din0(w11_q16),
    .din1(mul_ln53_68_fu_2225_p1),
    .dout(mul_ln53_68_fu_2225_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U251(
    .din0(w11_q15),
    .din1(mul_ln53_69_fu_2245_p1),
    .dout(mul_ln53_69_fu_2245_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U252(
    .din0(w11_q14),
    .din1(mul_ln53_70_fu_2265_p1),
    .dout(mul_ln53_70_fu_2265_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U253(
    .din0(w11_q13),
    .din1(mul_ln53_71_fu_2285_p1),
    .dout(mul_ln53_71_fu_2285_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U254(
    .din0(w11_q12),
    .din1(mul_ln53_72_fu_2305_p1),
    .dout(mul_ln53_72_fu_2305_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U255(
    .din0(w11_q11),
    .din1(mul_ln53_73_fu_2325_p1),
    .dout(mul_ln53_73_fu_2325_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U256(
    .din0(w11_q10),
    .din1(mul_ln53_74_fu_2345_p1),
    .dout(mul_ln53_74_fu_2345_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U257(
    .din0(w11_q9),
    .din1(mul_ln53_75_fu_2365_p1),
    .dout(mul_ln53_75_fu_2365_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U258(
    .din0(w11_q8),
    .din1(mul_ln53_76_fu_2385_p1),
    .dout(mul_ln53_76_fu_2385_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U259(
    .din0(w11_q7),
    .din1(mul_ln53_77_fu_2405_p1),
    .dout(mul_ln53_77_fu_2405_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U260(
    .din0(w11_q6),
    .din1(mul_ln53_78_fu_2425_p1),
    .dout(mul_ln53_78_fu_2425_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U261(
    .din0(w11_q5),
    .din1(mul_ln53_79_fu_2445_p1),
    .dout(mul_ln53_79_fu_2445_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U262(
    .din0(w11_q4),
    .din1(mul_ln53_80_fu_2465_p1),
    .dout(mul_ln53_80_fu_2465_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U263(
    .din0(w11_q3),
    .din1(mul_ln53_81_fu_2485_p1),
    .dout(mul_ln53_81_fu_2485_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U264(
    .din0(w11_q2),
    .din1(mul_ln53_82_fu_2505_p1),
    .dout(mul_ln53_82_fu_2505_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U265(
    .din0(w11_q1),
    .din1(mul_ln53_83_fu_2525_p1),
    .dout(mul_ln53_83_fu_2525_p2)
);

myproject_mul_12s_16s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_12s_16s_24_1_1_U266(
    .din0(w11_q0),
    .din1(mul_ln53_84_fu_2545_p1),
    .dout(mul_ln53_84_fu_2545_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_10_phi_reg_1255 <= {{layer10_out_dout[31:16]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_10_phi_reg_1255 <= ap_phi_reg_pp0_iter1_data_10_phi_reg_1255;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_11_phi_reg_1147 <= {{layer10_out_dout[239:224]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_11_phi_reg_1147 <= ap_phi_reg_pp0_iter1_data_11_phi_reg_1147;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_12_phi_reg_1135 <= {{layer10_out_dout[255:240]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_12_phi_reg_1135 <= ap_phi_reg_pp0_iter1_data_12_phi_reg_1135;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_13_phi_reg_1123 <= {{layer10_out_dout[271:256]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_13_phi_reg_1123 <= ap_phi_reg_pp0_iter1_data_13_phi_reg_1123;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_14_phi_reg_1111 <= {{layer10_out_dout[287:272]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_14_phi_reg_1111 <= ap_phi_reg_pp0_iter1_data_14_phi_reg_1111;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_15_phi_reg_1099 <= {{layer10_out_dout[303:288]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_15_phi_reg_1099 <= ap_phi_reg_pp0_iter1_data_15_phi_reg_1099;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_16_phi_reg_1087 <= {{layer10_out_dout[319:304]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_16_phi_reg_1087 <= ap_phi_reg_pp0_iter1_data_16_phi_reg_1087;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_17_phi_reg_1075 <= {{layer10_out_dout[335:320]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_17_phi_reg_1075 <= ap_phi_reg_pp0_iter1_data_17_phi_reg_1075;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_18_phi_reg_1063 <= {{layer10_out_dout[351:336]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_18_phi_reg_1063 <= ap_phi_reg_pp0_iter1_data_18_phi_reg_1063;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_19_phi_reg_1051 <= {{layer10_out_dout[367:352]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_19_phi_reg_1051 <= ap_phi_reg_pp0_iter1_data_19_phi_reg_1051;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_1_phi_reg_1243 <= {{layer10_out_dout[47:32]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_1_phi_reg_1243 <= ap_phi_reg_pp0_iter1_data_1_phi_reg_1243;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_20_phi_reg_1039 <= {{layer10_out_dout[383:368]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_20_phi_reg_1039 <= ap_phi_reg_pp0_iter1_data_20_phi_reg_1039;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_21_phi_reg_1027 <= {{layer10_out_dout[399:384]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_21_phi_reg_1027 <= ap_phi_reg_pp0_iter1_data_21_phi_reg_1027;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_22_phi_reg_1015 <= {{layer10_out_dout[415:400]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_22_phi_reg_1015 <= ap_phi_reg_pp0_iter1_data_22_phi_reg_1015;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_23_phi_reg_1003 <= {{layer10_out_dout[431:416]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_23_phi_reg_1003 <= ap_phi_reg_pp0_iter1_data_23_phi_reg_1003;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_24_phi_reg_991 <= {{layer10_out_dout[447:432]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_24_phi_reg_991 <= ap_phi_reg_pp0_iter1_data_24_phi_reg_991;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_25_phi_reg_979 <= {{layer10_out_dout[463:448]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_25_phi_reg_979 <= ap_phi_reg_pp0_iter1_data_25_phi_reg_979;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_2_phi_reg_1231 <= {{layer10_out_dout[63:48]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_2_phi_reg_1231 <= ap_phi_reg_pp0_iter1_data_2_phi_reg_1231;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_32_phi_reg_1339 <= {{layer10_out_dout[175:160]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_32_phi_reg_1339 <= ap_phi_reg_pp0_iter1_data_32_phi_reg_1339;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_33_phi_reg_1327 <= {{layer10_out_dout[191:176]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_33_phi_reg_1327 <= ap_phi_reg_pp0_iter1_data_33_phi_reg_1327;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_34_phi_reg_1315 <= {{layer10_out_dout[207:192]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_34_phi_reg_1315 <= ap_phi_reg_pp0_iter1_data_34_phi_reg_1315;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_35_phi_reg_1303 <= {{layer10_out_dout[223:208]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_35_phi_reg_1303 <= ap_phi_reg_pp0_iter1_data_35_phi_reg_1303;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_36_phi_reg_1291 <= {{layer10_out_dout[479:464]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_36_phi_reg_1291 <= ap_phi_reg_pp0_iter1_data_36_phi_reg_1291;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_37_phi_reg_1279 <= {{layer10_out_dout[495:480]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_37_phi_reg_1279 <= ap_phi_reg_pp0_iter1_data_37_phi_reg_1279;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_3_phi_reg_1219 <= {{layer10_out_dout[79:64]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_3_phi_reg_1219 <= ap_phi_reg_pp0_iter1_data_3_phi_reg_1219;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_4_phi_reg_1207 <= {{layer10_out_dout[95:80]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_4_phi_reg_1207 <= ap_phi_reg_pp0_iter1_data_4_phi_reg_1207;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_5_phi_reg_1195 <= {{layer10_out_dout[111:96]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_5_phi_reg_1195 <= ap_phi_reg_pp0_iter1_data_5_phi_reg_1195;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_6_phi_reg_1183 <= {{layer10_out_dout[127:112]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_6_phi_reg_1183 <= ap_phi_reg_pp0_iter1_data_6_phi_reg_1183;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_7_phi_reg_1171 <= {{layer10_out_dout[143:128]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_7_phi_reg_1171 <= ap_phi_reg_pp0_iter1_data_7_phi_reg_1171;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_8_phi_reg_1159 <= {{layer10_out_dout[159:144]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_8_phi_reg_1159 <= ap_phi_reg_pp0_iter1_data_8_phi_reg_1159;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_data_9_phi_reg_1267 <= {{layer10_out_dout[511:496]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_data_9_phi_reg_1267 <= ap_phi_reg_pp0_iter1_data_9_phi_reg_1267;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_511)) begin
        if ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter2_p_phi_reg_1351 <= data_fu_1515_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_phi_reg_1351 <= ap_phi_reg_pp0_iter1_p_phi_reg_1351;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd0))) begin
        conv_i2_i_1159_i_i127_reg_1433 <= x_15_fu_2615_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        conv_i2_i_1159_i_i127_reg_1433 <= 12'd4058;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd0))) begin
        conv_i2_i_1360_i_i125_reg_1447 <= x_16_fu_2625_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        conv_i2_i_1360_i_i125_reg_1447 <= 12'd23;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd0))) begin
        conv_i2_i_154_i_i137_reg_1363 <= x_fu_2565_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        conv_i2_i_154_i_i137_reg_1363 <= 12'd6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd0))) begin
        conv_i2_i_1561_i_i123_reg_1461 <= x_17_fu_2635_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        conv_i2_i_1561_i_i123_reg_1461 <= 12'd4023;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd0))) begin
        conv_i2_i_1762_i_i121_reg_1475 <= x_18_fu_2645_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        conv_i2_i_1762_i_i121_reg_1475 <= 12'd4062;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd0))) begin
        conv_i2_i_1963_i_i119_reg_1489 <= x_19_fu_2655_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        conv_i2_i_1963_i_i119_reg_1489 <= 12'd116;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd0))) begin
        conv_i2_i_355_i_i135_reg_1377 <= x_11_fu_2575_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        conv_i2_i_355_i_i135_reg_1377 <= 12'd35;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd0))) begin
        conv_i2_i_556_i_i133_reg_1391 <= x_12_fu_2585_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        conv_i2_i_556_i_i133_reg_1391 <= 12'd3989;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd0))) begin
        conv_i2_i_757_i_i131_reg_1405 <= x_13_fu_2595_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        conv_i2_i_757_i_i131_reg_1405 <= 12'd56;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd0))) begin
        conv_i2_i_958_i_i129_reg_1419 <= x_14_fu_2605_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        conv_i2_i_958_i_i129_reg_1419 <= 12'd6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_10_phi_reg_1255 <= data_10_phi_reg_1255;
        end else if ((1'b1 == 1'b1)) begin
            data_10_phi_reg_1255 <= ap_phi_reg_pp0_iter2_data_10_phi_reg_1255;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_11_phi_reg_1147 <= data_11_phi_reg_1147;
        end else if ((1'b1 == 1'b1)) begin
            data_11_phi_reg_1147 <= ap_phi_reg_pp0_iter2_data_11_phi_reg_1147;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_12_phi_reg_1135 <= data_12_phi_reg_1135;
        end else if ((1'b1 == 1'b1)) begin
            data_12_phi_reg_1135 <= ap_phi_reg_pp0_iter2_data_12_phi_reg_1135;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_13_phi_reg_1123 <= data_13_phi_reg_1123;
        end else if ((1'b1 == 1'b1)) begin
            data_13_phi_reg_1123 <= ap_phi_reg_pp0_iter2_data_13_phi_reg_1123;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_14_phi_reg_1111 <= data_14_phi_reg_1111;
        end else if ((1'b1 == 1'b1)) begin
            data_14_phi_reg_1111 <= ap_phi_reg_pp0_iter2_data_14_phi_reg_1111;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_15_phi_reg_1099 <= data_15_phi_reg_1099;
        end else if ((1'b1 == 1'b1)) begin
            data_15_phi_reg_1099 <= ap_phi_reg_pp0_iter2_data_15_phi_reg_1099;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_16_phi_reg_1087 <= data_16_phi_reg_1087;
        end else if ((1'b1 == 1'b1)) begin
            data_16_phi_reg_1087 <= ap_phi_reg_pp0_iter2_data_16_phi_reg_1087;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_17_phi_reg_1075 <= data_17_phi_reg_1075;
        end else if ((1'b1 == 1'b1)) begin
            data_17_phi_reg_1075 <= ap_phi_reg_pp0_iter2_data_17_phi_reg_1075;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_18_phi_reg_1063 <= data_18_phi_reg_1063;
        end else if ((1'b1 == 1'b1)) begin
            data_18_phi_reg_1063 <= ap_phi_reg_pp0_iter2_data_18_phi_reg_1063;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_19_phi_reg_1051 <= data_19_phi_reg_1051;
        end else if ((1'b1 == 1'b1)) begin
            data_19_phi_reg_1051 <= ap_phi_reg_pp0_iter2_data_19_phi_reg_1051;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_1_phi_reg_1243 <= data_1_phi_reg_1243;
        end else if ((1'b1 == 1'b1)) begin
            data_1_phi_reg_1243 <= ap_phi_reg_pp0_iter2_data_1_phi_reg_1243;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_20_phi_reg_1039 <= data_20_phi_reg_1039;
        end else if ((1'b1 == 1'b1)) begin
            data_20_phi_reg_1039 <= ap_phi_reg_pp0_iter2_data_20_phi_reg_1039;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_21_phi_reg_1027 <= data_21_phi_reg_1027;
        end else if ((1'b1 == 1'b1)) begin
            data_21_phi_reg_1027 <= ap_phi_reg_pp0_iter2_data_21_phi_reg_1027;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_22_phi_reg_1015 <= data_22_phi_reg_1015;
        end else if ((1'b1 == 1'b1)) begin
            data_22_phi_reg_1015 <= ap_phi_reg_pp0_iter2_data_22_phi_reg_1015;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_23_phi_reg_1003 <= data_23_phi_reg_1003;
        end else if ((1'b1 == 1'b1)) begin
            data_23_phi_reg_1003 <= ap_phi_reg_pp0_iter2_data_23_phi_reg_1003;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_24_phi_reg_991 <= data_24_phi_reg_991;
        end else if ((1'b1 == 1'b1)) begin
            data_24_phi_reg_991 <= ap_phi_reg_pp0_iter2_data_24_phi_reg_991;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_25_phi_reg_979 <= data_25_phi_reg_979;
        end else if ((1'b1 == 1'b1)) begin
            data_25_phi_reg_979 <= ap_phi_reg_pp0_iter2_data_25_phi_reg_979;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_2_phi_reg_1231 <= data_2_phi_reg_1231;
        end else if ((1'b1 == 1'b1)) begin
            data_2_phi_reg_1231 <= ap_phi_reg_pp0_iter2_data_2_phi_reg_1231;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_32_phi_reg_1339 <= data_32_phi_reg_1339;
        end else if ((1'b1 == 1'b1)) begin
            data_32_phi_reg_1339 <= ap_phi_reg_pp0_iter2_data_32_phi_reg_1339;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_33_phi_reg_1327 <= data_33_phi_reg_1327;
        end else if ((1'b1 == 1'b1)) begin
            data_33_phi_reg_1327 <= ap_phi_reg_pp0_iter2_data_33_phi_reg_1327;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_34_phi_reg_1315 <= data_34_phi_reg_1315;
        end else if ((1'b1 == 1'b1)) begin
            data_34_phi_reg_1315 <= ap_phi_reg_pp0_iter2_data_34_phi_reg_1315;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_35_phi_reg_1303 <= data_35_phi_reg_1303;
        end else if ((1'b1 == 1'b1)) begin
            data_35_phi_reg_1303 <= ap_phi_reg_pp0_iter2_data_35_phi_reg_1303;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_36_phi_reg_1291 <= data_36_phi_reg_1291;
        end else if ((1'b1 == 1'b1)) begin
            data_36_phi_reg_1291 <= ap_phi_reg_pp0_iter2_data_36_phi_reg_1291;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_37_phi_reg_1279 <= data_37_phi_reg_1279;
        end else if ((1'b1 == 1'b1)) begin
            data_37_phi_reg_1279 <= ap_phi_reg_pp0_iter2_data_37_phi_reg_1279;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_3_phi_reg_1219 <= data_3_phi_reg_1219;
        end else if ((1'b1 == 1'b1)) begin
            data_3_phi_reg_1219 <= ap_phi_reg_pp0_iter2_data_3_phi_reg_1219;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_4_phi_reg_1207 <= data_4_phi_reg_1207;
        end else if ((1'b1 == 1'b1)) begin
            data_4_phi_reg_1207 <= ap_phi_reg_pp0_iter2_data_4_phi_reg_1207;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_5_phi_reg_1195 <= data_5_phi_reg_1195;
        end else if ((1'b1 == 1'b1)) begin
            data_5_phi_reg_1195 <= ap_phi_reg_pp0_iter2_data_5_phi_reg_1195;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_6_phi_reg_1183 <= data_6_phi_reg_1183;
        end else if ((1'b1 == 1'b1)) begin
            data_6_phi_reg_1183 <= ap_phi_reg_pp0_iter2_data_6_phi_reg_1183;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_7_phi_reg_1171 <= data_7_phi_reg_1171;
        end else if ((1'b1 == 1'b1)) begin
            data_7_phi_reg_1171 <= ap_phi_reg_pp0_iter2_data_7_phi_reg_1171;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_8_phi_reg_1159 <= data_8_phi_reg_1159;
        end else if ((1'b1 == 1'b1)) begin
            data_8_phi_reg_1159 <= ap_phi_reg_pp0_iter2_data_8_phi_reg_1159;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            data_9_phi_reg_1267 <= data_9_phi_reg_1267;
        end else if ((1'b1 == 1'b1)) begin
            data_9_phi_reg_1267 <= ap_phi_reg_pp0_iter2_data_9_phi_reg_1267;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter1_reg == 1'd0))) begin
        do_init_reg_500 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter1_reg == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_500 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_reg_2807 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index117_reg_516 <= in_index_reg_2802;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln42_reg_2807 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index117_reg_516 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((do_init_reg_500 == 1'd0)) begin
            p_phi_reg_1351 <= p_phi_reg_1351;
        end else if ((1'b1 == 1'b1)) begin
            p_phi_reg_1351 <= ap_phi_reg_pp0_iter2_p_phi_reg_1351;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_data_10_phi_reg_1255 <= ap_phi_reg_pp0_iter0_data_10_phi_reg_1255;
        ap_phi_reg_pp0_iter1_data_11_phi_reg_1147 <= ap_phi_reg_pp0_iter0_data_11_phi_reg_1147;
        ap_phi_reg_pp0_iter1_data_12_phi_reg_1135 <= ap_phi_reg_pp0_iter0_data_12_phi_reg_1135;
        ap_phi_reg_pp0_iter1_data_13_phi_reg_1123 <= ap_phi_reg_pp0_iter0_data_13_phi_reg_1123;
        ap_phi_reg_pp0_iter1_data_14_phi_reg_1111 <= ap_phi_reg_pp0_iter0_data_14_phi_reg_1111;
        ap_phi_reg_pp0_iter1_data_15_phi_reg_1099 <= ap_phi_reg_pp0_iter0_data_15_phi_reg_1099;
        ap_phi_reg_pp0_iter1_data_16_phi_reg_1087 <= ap_phi_reg_pp0_iter0_data_16_phi_reg_1087;
        ap_phi_reg_pp0_iter1_data_17_phi_reg_1075 <= ap_phi_reg_pp0_iter0_data_17_phi_reg_1075;
        ap_phi_reg_pp0_iter1_data_18_phi_reg_1063 <= ap_phi_reg_pp0_iter0_data_18_phi_reg_1063;
        ap_phi_reg_pp0_iter1_data_19_phi_reg_1051 <= ap_phi_reg_pp0_iter0_data_19_phi_reg_1051;
        ap_phi_reg_pp0_iter1_data_1_phi_reg_1243 <= ap_phi_reg_pp0_iter0_data_1_phi_reg_1243;
        ap_phi_reg_pp0_iter1_data_20_phi_reg_1039 <= ap_phi_reg_pp0_iter0_data_20_phi_reg_1039;
        ap_phi_reg_pp0_iter1_data_21_phi_reg_1027 <= ap_phi_reg_pp0_iter0_data_21_phi_reg_1027;
        ap_phi_reg_pp0_iter1_data_22_phi_reg_1015 <= ap_phi_reg_pp0_iter0_data_22_phi_reg_1015;
        ap_phi_reg_pp0_iter1_data_23_phi_reg_1003 <= ap_phi_reg_pp0_iter0_data_23_phi_reg_1003;
        ap_phi_reg_pp0_iter1_data_24_phi_reg_991 <= ap_phi_reg_pp0_iter0_data_24_phi_reg_991;
        ap_phi_reg_pp0_iter1_data_25_phi_reg_979 <= ap_phi_reg_pp0_iter0_data_25_phi_reg_979;
        ap_phi_reg_pp0_iter1_data_2_phi_reg_1231 <= ap_phi_reg_pp0_iter0_data_2_phi_reg_1231;
        ap_phi_reg_pp0_iter1_data_32_phi_reg_1339 <= ap_phi_reg_pp0_iter0_data_32_phi_reg_1339;
        ap_phi_reg_pp0_iter1_data_33_phi_reg_1327 <= ap_phi_reg_pp0_iter0_data_33_phi_reg_1327;
        ap_phi_reg_pp0_iter1_data_34_phi_reg_1315 <= ap_phi_reg_pp0_iter0_data_34_phi_reg_1315;
        ap_phi_reg_pp0_iter1_data_35_phi_reg_1303 <= ap_phi_reg_pp0_iter0_data_35_phi_reg_1303;
        ap_phi_reg_pp0_iter1_data_36_phi_reg_1291 <= ap_phi_reg_pp0_iter0_data_36_phi_reg_1291;
        ap_phi_reg_pp0_iter1_data_37_phi_reg_1279 <= ap_phi_reg_pp0_iter0_data_37_phi_reg_1279;
        ap_phi_reg_pp0_iter1_data_3_phi_reg_1219 <= ap_phi_reg_pp0_iter0_data_3_phi_reg_1219;
        ap_phi_reg_pp0_iter1_data_4_phi_reg_1207 <= ap_phi_reg_pp0_iter0_data_4_phi_reg_1207;
        ap_phi_reg_pp0_iter1_data_5_phi_reg_1195 <= ap_phi_reg_pp0_iter0_data_5_phi_reg_1195;
        ap_phi_reg_pp0_iter1_data_6_phi_reg_1183 <= ap_phi_reg_pp0_iter0_data_6_phi_reg_1183;
        ap_phi_reg_pp0_iter1_data_7_phi_reg_1171 <= ap_phi_reg_pp0_iter0_data_7_phi_reg_1171;
        ap_phi_reg_pp0_iter1_data_8_phi_reg_1159 <= ap_phi_reg_pp0_iter0_data_8_phi_reg_1159;
        ap_phi_reg_pp0_iter1_data_9_phi_reg_1267 <= ap_phi_reg_pp0_iter0_data_9_phi_reg_1267;
        ap_phi_reg_pp0_iter1_p_phi_reg_1351 <= ap_phi_reg_pp0_iter0_p_phi_reg_1351;
        in_index_reg_2802 <= in_index_fu_1503_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln42_reg_2807 <= icmp_ln42_fu_1509_p2;
        icmp_ln42_reg_2807_pp0_iter1_reg <= icmp_ln42_reg_2807;
        in_index117_reg_516_pp0_iter1_reg <= in_index117_reg_516;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln42_reg_2807_pp0_iter2_reg <= icmp_ln42_reg_2807_pp0_iter1_reg;
        trunc_ln53_63_reg_3081 <= {{mul_ln53_67_fu_2205_p2[23:12]}};
        trunc_ln53_64_reg_3086 <= {{mul_ln53_68_fu_2225_p2[23:12]}};
        trunc_ln53_65_reg_3091 <= {{mul_ln53_69_fu_2245_p2[23:12]}};
        trunc_ln53_66_reg_3096 <= {{mul_ln53_70_fu_2265_p2[23:12]}};
        trunc_ln53_67_reg_3101 <= {{mul_ln53_71_fu_2285_p2[23:12]}};
        trunc_ln53_68_reg_3106 <= {{mul_ln53_72_fu_2305_p2[23:12]}};
        trunc_ln53_69_reg_3111 <= {{mul_ln53_73_fu_2325_p2[23:12]}};
        trunc_ln53_70_reg_3116 <= {{mul_ln53_74_fu_2345_p2[23:12]}};
        trunc_ln53_71_reg_3121 <= {{mul_ln53_75_fu_2365_p2[23:12]}};
        trunc_ln53_72_reg_3126 <= {{mul_ln53_76_fu_2385_p2[23:12]}};
        trunc_ln53_73_reg_3131 <= {{mul_ln53_77_fu_2405_p2[23:12]}};
        trunc_ln53_74_reg_3136 <= {{mul_ln53_78_fu_2425_p2[23:12]}};
        trunc_ln53_75_reg_3141 <= {{mul_ln53_79_fu_2445_p2[23:12]}};
        trunc_ln53_76_reg_3146 <= {{mul_ln53_80_fu_2465_p2[23:12]}};
        trunc_ln53_77_reg_3151 <= {{mul_ln53_81_fu_2485_p2[23:12]}};
        trunc_ln53_78_reg_3156 <= {{mul_ln53_82_fu_2505_p2[23:12]}};
        trunc_ln53_79_reg_3161 <= {{mul_ln53_83_fu_2525_p2[23:12]}};
        trunc_ln53_80_reg_3166 <= {{mul_ln53_84_fu_2545_p2[23:12]}};
        trunc_ln53_s_reg_3076 <= {{mul_ln53_66_fu_2185_p2[23:12]}};
        trunc_ln_reg_3071 <= {{mul_ln53_fu_2123_p2[23:12]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_10_phi_phi_fu_1259_p4 = data_10_phi_reg_1255;
    end else begin
        ap_phi_mux_data_10_phi_phi_fu_1259_p4 = ap_phi_reg_pp0_iter2_data_10_phi_reg_1255;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_11_phi_phi_fu_1151_p4 = data_11_phi_reg_1147;
    end else begin
        ap_phi_mux_data_11_phi_phi_fu_1151_p4 = ap_phi_reg_pp0_iter2_data_11_phi_reg_1147;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_12_phi_phi_fu_1139_p4 = data_12_phi_reg_1135;
    end else begin
        ap_phi_mux_data_12_phi_phi_fu_1139_p4 = ap_phi_reg_pp0_iter2_data_12_phi_reg_1135;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_13_phi_phi_fu_1127_p4 = data_13_phi_reg_1123;
    end else begin
        ap_phi_mux_data_13_phi_phi_fu_1127_p4 = ap_phi_reg_pp0_iter2_data_13_phi_reg_1123;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_14_phi_phi_fu_1115_p4 = data_14_phi_reg_1111;
    end else begin
        ap_phi_mux_data_14_phi_phi_fu_1115_p4 = ap_phi_reg_pp0_iter2_data_14_phi_reg_1111;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_15_phi_phi_fu_1103_p4 = data_15_phi_reg_1099;
    end else begin
        ap_phi_mux_data_15_phi_phi_fu_1103_p4 = ap_phi_reg_pp0_iter2_data_15_phi_reg_1099;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_16_phi_phi_fu_1091_p4 = data_16_phi_reg_1087;
    end else begin
        ap_phi_mux_data_16_phi_phi_fu_1091_p4 = ap_phi_reg_pp0_iter2_data_16_phi_reg_1087;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_17_phi_phi_fu_1079_p4 = data_17_phi_reg_1075;
    end else begin
        ap_phi_mux_data_17_phi_phi_fu_1079_p4 = ap_phi_reg_pp0_iter2_data_17_phi_reg_1075;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_18_phi_phi_fu_1067_p4 = data_18_phi_reg_1063;
    end else begin
        ap_phi_mux_data_18_phi_phi_fu_1067_p4 = ap_phi_reg_pp0_iter2_data_18_phi_reg_1063;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_19_phi_phi_fu_1055_p4 = data_19_phi_reg_1051;
    end else begin
        ap_phi_mux_data_19_phi_phi_fu_1055_p4 = ap_phi_reg_pp0_iter2_data_19_phi_reg_1051;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_1_phi_phi_fu_1247_p4 = data_1_phi_reg_1243;
    end else begin
        ap_phi_mux_data_1_phi_phi_fu_1247_p4 = ap_phi_reg_pp0_iter2_data_1_phi_reg_1243;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_20_phi_phi_fu_1043_p4 = data_20_phi_reg_1039;
    end else begin
        ap_phi_mux_data_20_phi_phi_fu_1043_p4 = ap_phi_reg_pp0_iter2_data_20_phi_reg_1039;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_21_phi_phi_fu_1031_p4 = data_21_phi_reg_1027;
    end else begin
        ap_phi_mux_data_21_phi_phi_fu_1031_p4 = ap_phi_reg_pp0_iter2_data_21_phi_reg_1027;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_22_phi_phi_fu_1019_p4 = data_22_phi_reg_1015;
    end else begin
        ap_phi_mux_data_22_phi_phi_fu_1019_p4 = ap_phi_reg_pp0_iter2_data_22_phi_reg_1015;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_23_phi_phi_fu_1007_p4 = data_23_phi_reg_1003;
    end else begin
        ap_phi_mux_data_23_phi_phi_fu_1007_p4 = ap_phi_reg_pp0_iter2_data_23_phi_reg_1003;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_24_phi_phi_fu_995_p4 = data_24_phi_reg_991;
    end else begin
        ap_phi_mux_data_24_phi_phi_fu_995_p4 = ap_phi_reg_pp0_iter2_data_24_phi_reg_991;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_25_phi_phi_fu_983_p4 = data_25_phi_reg_979;
    end else begin
        ap_phi_mux_data_25_phi_phi_fu_983_p4 = ap_phi_reg_pp0_iter2_data_25_phi_reg_979;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_2_phi_phi_fu_1235_p4 = data_2_phi_reg_1231;
    end else begin
        ap_phi_mux_data_2_phi_phi_fu_1235_p4 = ap_phi_reg_pp0_iter2_data_2_phi_reg_1231;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_32_phi_phi_fu_1343_p4 = data_32_phi_reg_1339;
    end else begin
        ap_phi_mux_data_32_phi_phi_fu_1343_p4 = ap_phi_reg_pp0_iter2_data_32_phi_reg_1339;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_33_phi_phi_fu_1331_p4 = data_33_phi_reg_1327;
    end else begin
        ap_phi_mux_data_33_phi_phi_fu_1331_p4 = ap_phi_reg_pp0_iter2_data_33_phi_reg_1327;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_34_phi_phi_fu_1319_p4 = data_34_phi_reg_1315;
    end else begin
        ap_phi_mux_data_34_phi_phi_fu_1319_p4 = ap_phi_reg_pp0_iter2_data_34_phi_reg_1315;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_35_phi_phi_fu_1307_p4 = data_35_phi_reg_1303;
    end else begin
        ap_phi_mux_data_35_phi_phi_fu_1307_p4 = ap_phi_reg_pp0_iter2_data_35_phi_reg_1303;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_36_phi_phi_fu_1295_p4 = data_36_phi_reg_1291;
    end else begin
        ap_phi_mux_data_36_phi_phi_fu_1295_p4 = ap_phi_reg_pp0_iter2_data_36_phi_reg_1291;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_37_phi_phi_fu_1283_p4 = data_37_phi_reg_1279;
    end else begin
        ap_phi_mux_data_37_phi_phi_fu_1283_p4 = ap_phi_reg_pp0_iter2_data_37_phi_reg_1279;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_3_phi_phi_fu_1223_p4 = data_3_phi_reg_1219;
    end else begin
        ap_phi_mux_data_3_phi_phi_fu_1223_p4 = ap_phi_reg_pp0_iter2_data_3_phi_reg_1219;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_4_phi_phi_fu_1211_p4 = data_4_phi_reg_1207;
    end else begin
        ap_phi_mux_data_4_phi_phi_fu_1211_p4 = ap_phi_reg_pp0_iter2_data_4_phi_reg_1207;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_5_phi_phi_fu_1199_p4 = data_5_phi_reg_1195;
    end else begin
        ap_phi_mux_data_5_phi_phi_fu_1199_p4 = ap_phi_reg_pp0_iter2_data_5_phi_reg_1195;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_6_phi_phi_fu_1187_p4 = data_6_phi_reg_1183;
    end else begin
        ap_phi_mux_data_6_phi_phi_fu_1187_p4 = ap_phi_reg_pp0_iter2_data_6_phi_reg_1183;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_7_phi_phi_fu_1175_p4 = data_7_phi_reg_1171;
    end else begin
        ap_phi_mux_data_7_phi_phi_fu_1175_p4 = ap_phi_reg_pp0_iter2_data_7_phi_reg_1171;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_8_phi_phi_fu_1163_p4 = data_8_phi_reg_1159;
    end else begin
        ap_phi_mux_data_8_phi_phi_fu_1163_p4 = ap_phi_reg_pp0_iter2_data_8_phi_reg_1159;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_data_9_phi_phi_fu_1271_p4 = data_9_phi_reg_1267;
    end else begin
        ap_phi_mux_data_9_phi_phi_fu_1271_p4 = ap_phi_reg_pp0_iter2_data_9_phi_reg_1267;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln42_reg_2807_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_504_p6 = 1'd1;
        end else if ((icmp_ln42_reg_2807_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_504_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_504_p6 = do_init_reg_500;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_504_p6 = do_init_reg_500;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_155)) begin
        if ((icmp_ln42_reg_2807 == 1'd1)) begin
            ap_phi_mux_in_index117_phi_fu_520_p6 = 4'd0;
        end else if ((icmp_ln42_reg_2807 == 1'd0)) begin
            ap_phi_mux_in_index117_phi_fu_520_p6 = in_index_reg_2802;
        end else begin
            ap_phi_mux_in_index117_phi_fu_520_p6 = in_index117_reg_516;
        end
    end else begin
        ap_phi_mux_in_index117_phi_fu_520_p6 = in_index117_reg_516;
    end
end

always @ (*) begin
    if ((do_init_reg_500 == 1'd0)) begin
        ap_phi_mux_p_phi_phi_fu_1355_p4 = p_phi_reg_1351;
    end else begin
        ap_phi_mux_p_phi_phi_fu_1355_p4 = ap_phi_reg_pp0_iter2_p_phi_reg_1351;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln42_fu_1509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer10_out_blk_n = layer10_out_empty_n;
    end else begin
        layer10_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer10_out_read = 1'b1;
    end else begin
        layer10_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1))) begin
        layer11_out_blk_n = layer11_out_full_n;
    end else begin
        layer11_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1))) begin
        layer11_out_write = 1'b1;
    end else begin
        layer11_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce0 = 1'b1;
    end else begin
        w11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce1 = 1'b1;
    end else begin
        w11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce10 = 1'b1;
    end else begin
        w11_ce10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce11 = 1'b1;
    end else begin
        w11_ce11 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce12 = 1'b1;
    end else begin
        w11_ce12 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce13 = 1'b1;
    end else begin
        w11_ce13 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce14 = 1'b1;
    end else begin
        w11_ce14 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce15 = 1'b1;
    end else begin
        w11_ce15 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce16 = 1'b1;
    end else begin
        w11_ce16 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce17 = 1'b1;
    end else begin
        w11_ce17 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce18 = 1'b1;
    end else begin
        w11_ce18 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce19 = 1'b1;
    end else begin
        w11_ce19 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce2 = 1'b1;
    end else begin
        w11_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce3 = 1'b1;
    end else begin
        w11_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce4 = 1'b1;
    end else begin
        w11_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce5 = 1'b1;
    end else begin
        w11_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce6 = 1'b1;
    end else begin
        w11_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce7 = 1'b1;
    end else begin
        w11_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce8 = 1'b1;
    end else begin
        w11_ce8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_ce9 = 1'b1;
    end else begin
        w11_ce9 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln53_67_fu_2571_p2 = (trunc_ln53_64_reg_3086 + trunc_ln53_63_reg_3081);

assign add_ln53_69_fu_2581_p2 = (trunc_ln53_66_reg_3096 + trunc_ln53_65_reg_3091);

assign add_ln53_71_fu_2591_p2 = (trunc_ln53_68_reg_3106 + trunc_ln53_67_reg_3101);

assign add_ln53_73_fu_2601_p2 = (trunc_ln53_70_reg_3116 + trunc_ln53_69_reg_3111);

assign add_ln53_75_fu_2611_p2 = (trunc_ln53_72_reg_3126 + trunc_ln53_71_reg_3121);

assign add_ln53_77_fu_2621_p2 = (trunc_ln53_74_reg_3136 + trunc_ln53_73_reg_3131);

assign add_ln53_79_fu_2631_p2 = (trunc_ln53_76_reg_3146 + trunc_ln53_75_reg_3141);

assign add_ln53_81_fu_2641_p2 = (trunc_ln53_78_reg_3156 + trunc_ln53_77_reg_3151);

assign add_ln53_83_fu_2651_p2 = (trunc_ln53_80_reg_3166 + trunc_ln53_79_reg_3161);

assign add_ln53_fu_2561_p2 = (trunc_ln53_s_reg_3076 + trunc_ln_reg_3071);

assign add_ln55261_fu_1834_p1 = in_index117_reg_516;

assign add_ln55_63262_fu_1851_p1 = in_index117_reg_516;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1) & (layer11_out_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1) & (layer10_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1) & (layer11_out_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1) & (layer10_out_empty_n == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter3 == 1'b1) & (icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1) & (layer11_out_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1) & (layer10_out_empty_n == 1'b0)));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((ap_phi_mux_do_init_phi_fu_504_p6 == 1'd1) & (layer10_out_empty_n == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter3 = ((icmp_ln42_reg_2807_pp0_iter2_reg == 1'd1) & (layer11_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_155 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_511 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_data_10_phi_reg_1255 = 'bx;

assign ap_phi_reg_pp0_iter0_data_11_phi_reg_1147 = 'bx;

assign ap_phi_reg_pp0_iter0_data_12_phi_reg_1135 = 'bx;

assign ap_phi_reg_pp0_iter0_data_13_phi_reg_1123 = 'bx;

assign ap_phi_reg_pp0_iter0_data_14_phi_reg_1111 = 'bx;

assign ap_phi_reg_pp0_iter0_data_15_phi_reg_1099 = 'bx;

assign ap_phi_reg_pp0_iter0_data_16_phi_reg_1087 = 'bx;

assign ap_phi_reg_pp0_iter0_data_17_phi_reg_1075 = 'bx;

assign ap_phi_reg_pp0_iter0_data_18_phi_reg_1063 = 'bx;

assign ap_phi_reg_pp0_iter0_data_19_phi_reg_1051 = 'bx;

assign ap_phi_reg_pp0_iter0_data_1_phi_reg_1243 = 'bx;

assign ap_phi_reg_pp0_iter0_data_20_phi_reg_1039 = 'bx;

assign ap_phi_reg_pp0_iter0_data_21_phi_reg_1027 = 'bx;

assign ap_phi_reg_pp0_iter0_data_22_phi_reg_1015 = 'bx;

assign ap_phi_reg_pp0_iter0_data_23_phi_reg_1003 = 'bx;

assign ap_phi_reg_pp0_iter0_data_24_phi_reg_991 = 'bx;

assign ap_phi_reg_pp0_iter0_data_25_phi_reg_979 = 'bx;

assign ap_phi_reg_pp0_iter0_data_2_phi_reg_1231 = 'bx;

assign ap_phi_reg_pp0_iter0_data_32_phi_reg_1339 = 'bx;

assign ap_phi_reg_pp0_iter0_data_33_phi_reg_1327 = 'bx;

assign ap_phi_reg_pp0_iter0_data_34_phi_reg_1315 = 'bx;

assign ap_phi_reg_pp0_iter0_data_35_phi_reg_1303 = 'bx;

assign ap_phi_reg_pp0_iter0_data_36_phi_reg_1291 = 'bx;

assign ap_phi_reg_pp0_iter0_data_37_phi_reg_1279 = 'bx;

assign ap_phi_reg_pp0_iter0_data_3_phi_reg_1219 = 'bx;

assign ap_phi_reg_pp0_iter0_data_4_phi_reg_1207 = 'bx;

assign ap_phi_reg_pp0_iter0_data_5_phi_reg_1195 = 'bx;

assign ap_phi_reg_pp0_iter0_data_6_phi_reg_1183 = 'bx;

assign ap_phi_reg_pp0_iter0_data_7_phi_reg_1171 = 'bx;

assign ap_phi_reg_pp0_iter0_data_8_phi_reg_1159 = 'bx;

assign ap_phi_reg_pp0_iter0_data_9_phi_reg_1267 = 'bx;

assign ap_phi_reg_pp0_iter0_p_phi_reg_1351 = 'bx;

assign data_fu_1515_p1 = layer10_out_dout[15:0];

assign icmp_ln42_fu_1509_p2 = ((ap_phi_mux_in_index117_phi_fu_520_p6 == 4'd15) ? 1'b1 : 1'b0);

assign in_index_fu_1503_p2 = (ap_phi_mux_in_index117_phi_fu_520_p6 + 4'd1);

assign layer11_out_din = $signed(or_ln77_s_fu_2769_p12);

assign mul_ln53_66_fu_2185_p1 = sext_ln73_74_fu_2181_p1;

assign mul_ln53_67_fu_2205_p1 = sext_ln73_72_fu_2119_p1;

assign mul_ln53_68_fu_2225_p1 = sext_ln73_74_fu_2181_p1;

assign mul_ln53_69_fu_2245_p1 = sext_ln73_72_fu_2119_p1;

assign mul_ln53_70_fu_2265_p1 = sext_ln73_74_fu_2181_p1;

assign mul_ln53_71_fu_2285_p1 = sext_ln73_72_fu_2119_p1;

assign mul_ln53_72_fu_2305_p1 = sext_ln73_74_fu_2181_p1;

assign mul_ln53_73_fu_2325_p1 = sext_ln73_72_fu_2119_p1;

assign mul_ln53_74_fu_2345_p1 = sext_ln73_74_fu_2181_p1;

assign mul_ln53_75_fu_2365_p1 = sext_ln73_72_fu_2119_p1;

assign mul_ln53_76_fu_2385_p1 = sext_ln73_74_fu_2181_p1;

assign mul_ln53_77_fu_2405_p1 = sext_ln73_72_fu_2119_p1;

assign mul_ln53_78_fu_2425_p1 = sext_ln73_74_fu_2181_p1;

assign mul_ln53_79_fu_2445_p1 = sext_ln73_72_fu_2119_p1;

assign mul_ln53_80_fu_2465_p1 = sext_ln73_74_fu_2181_p1;

assign mul_ln53_81_fu_2485_p1 = sext_ln73_72_fu_2119_p1;

assign mul_ln53_82_fu_2505_p1 = sext_ln73_74_fu_2181_p1;

assign mul_ln53_83_fu_2525_p1 = sext_ln73_72_fu_2119_p1;

assign mul_ln53_84_fu_2545_p1 = sext_ln73_74_fu_2181_p1;

assign mul_ln53_fu_2123_p1 = sext_ln73_72_fu_2119_p1;

assign or_ln77_s_fu_2769_p12 = {{{{{{{{{{{x_19_fu_2655_p2}, {2'd0}}, {sext_ln110_16_fu_2765_p1}}, {sext_ln110_15_fu_2753_p1}}, {sext_ln110_14_fu_2741_p1}}, {sext_ln110_13_fu_2729_p1}}, {sext_ln110_12_fu_2717_p1}}, {sext_ln110_11_fu_2705_p1}}, {sext_ln110_10_fu_2693_p1}}, {sext_ln110_9_fu_2681_p1}}, {sext_ln110_fu_2669_p1}};

assign p_cast100_cast_cast_fu_2002_p1 = $unsigned(p_cast100_cast_fu_1998_p1);

assign p_cast100_cast_fu_1998_p1 = p_cast3_fu_1890_p3;

assign p_cast101_cast_cast_fu_2011_p1 = $unsigned(p_cast101_cast_fu_2007_p1);

assign p_cast101_cast_fu_2007_p1 = tmp_s_fu_1903_p3;

assign p_cast102_cast_cast_fu_2020_p1 = $unsigned(p_cast102_cast_fu_2016_p1);

assign p_cast102_cast_fu_2016_p1 = p_cast_fu_1838_p3;

assign p_cast103_cast_fu_2033_p1 = p_cast8_fu_2025_p3;

assign p_cast104_cast_fu_2046_p1 = p_cast9_fu_2038_p3;

assign p_cast105_cast_fu_2059_p1 = p_cast10_fu_2051_p3;

assign p_cast106_cast_fu_2072_p1 = p_cast11_fu_2064_p3;

assign p_cast10_fu_2051_p3 = {{5'd18}, {in_index117_reg_516}};

assign p_cast11_fu_2064_p3 = {{5'd19}, {in_index117_reg_516}};

assign p_cast1_fu_1855_p3 = {{2'd2}, {in_index117_reg_516}};

assign p_cast2_fu_1877_p3 = {{3'd4}, {in_index117_reg_516}};

assign p_cast3_fu_1890_p3 = {{3'd5}, {in_index117_reg_516}};

assign p_cast4_fu_1929_p3 = {{4'd8}, {in_index117_reg_516}};

assign p_cast5_fu_1942_p3 = {{4'd9}, {in_index117_reg_516}};

assign p_cast6_fu_1955_p3 = {{4'd10}, {in_index117_reg_516}};

assign p_cast7_fu_1968_p3 = {{4'd11}, {in_index117_reg_516}};

assign p_cast88_cast_fu_1846_p1 = $unsigned(p_cast_fu_1838_p3);

assign p_cast89_cast_fu_1863_p1 = p_cast1_fu_1855_p3;

assign p_cast8_fu_2025_p3 = {{5'd16}, {in_index117_reg_516}};

assign p_cast90_cast_cast_fu_1872_p1 = $unsigned(p_cast90_cast_fu_1868_p1);

assign p_cast90_cast_fu_1868_p1 = p_cast_fu_1838_p3;

assign p_cast91_cast_fu_1885_p1 = p_cast2_fu_1877_p3;

assign p_cast92_cast_fu_1898_p1 = $unsigned(p_cast3_fu_1890_p3);

assign p_cast93_cast_cast_fu_1915_p1 = $unsigned(p_cast93_cast_fu_1911_p1);

assign p_cast93_cast_fu_1911_p1 = tmp_s_fu_1903_p3;

assign p_cast94_cast_cast_fu_1924_p1 = $unsigned(p_cast94_cast_fu_1920_p1);

assign p_cast94_cast_fu_1920_p1 = p_cast_fu_1838_p3;

assign p_cast95_cast_fu_1937_p1 = p_cast4_fu_1929_p3;

assign p_cast96_cast_fu_1950_p1 = p_cast5_fu_1942_p3;

assign p_cast97_cast_fu_1963_p1 = p_cast6_fu_1955_p3;

assign p_cast98_cast_fu_1976_p1 = p_cast7_fu_1968_p3;

assign p_cast99_cast_cast_fu_1993_p1 = $unsigned(p_cast99_cast_fu_1989_p1);

assign p_cast99_cast_fu_1989_p1 = $signed(tmp_28_fu_1981_p3);

assign p_cast9_fu_2038_p3 = {{5'd17}, {in_index117_reg_516}};

assign p_cast_fu_1838_p3 = {{1'd1}, {in_index117_reg_516}};

assign res_30_fu_2685_p3 = {{x_12_fu_2585_p2}, {2'd0}};

assign res_31_fu_2697_p3 = {{x_13_fu_2595_p2}, {2'd0}};

assign res_32_fu_2709_p3 = {{x_14_fu_2605_p2}, {2'd0}};

assign res_33_fu_2721_p3 = {{x_15_fu_2615_p2}, {2'd0}};

assign res_34_fu_2733_p3 = {{x_16_fu_2625_p2}, {2'd0}};

assign res_35_fu_2745_p3 = {{x_17_fu_2635_p2}, {2'd0}};

assign res_36_fu_2757_p3 = {{x_18_fu_2645_p2}, {2'd0}};

assign res_37_fu_2673_p3 = {{x_11_fu_2575_p2}, {2'd0}};

assign res_fu_2661_p3 = {{x_fu_2565_p2}, {2'd0}};

assign sext_ln110_10_fu_2693_p1 = $signed(res_30_fu_2685_p3);

assign sext_ln110_11_fu_2705_p1 = $signed(res_31_fu_2697_p3);

assign sext_ln110_12_fu_2717_p1 = $signed(res_32_fu_2709_p3);

assign sext_ln110_13_fu_2729_p1 = $signed(res_33_fu_2721_p3);

assign sext_ln110_14_fu_2741_p1 = $signed(res_34_fu_2733_p3);

assign sext_ln110_15_fu_2753_p1 = $signed(res_35_fu_2745_p3);

assign sext_ln110_16_fu_2765_p1 = $signed(res_36_fu_2757_p3);

assign sext_ln110_9_fu_2681_p1 = $signed(res_37_fu_2673_p3);

assign sext_ln110_fu_2669_p1 = $signed(res_fu_2661_p3);

assign sext_ln73_72_fu_2119_p1 = $signed(a_fu_2077_p18);

assign sext_ln73_74_fu_2181_p1 = $signed(a_4_fu_2139_p18);

assign tmp_28_fu_1981_p3 = {{1'd1}, {add_ln55_63262_fu_1851_p1}};

assign tmp_s_fu_1903_p3 = {{1'd1}, {add_ln55261_fu_1834_p1}};

assign w11_address0 = p_cast106_cast_fu_2072_p1;

assign w11_address1 = p_cast105_cast_fu_2059_p1;

assign w11_address10 = p_cast96_cast_fu_1950_p1;

assign w11_address11 = p_cast95_cast_fu_1937_p1;

assign w11_address12 = p_cast94_cast_cast_fu_1924_p1;

assign w11_address13 = p_cast93_cast_cast_fu_1915_p1;

assign w11_address14 = p_cast92_cast_fu_1898_p1;

assign w11_address15 = p_cast91_cast_fu_1885_p1;

assign w11_address16 = p_cast90_cast_cast_fu_1872_p1;

assign w11_address17 = p_cast89_cast_fu_1863_p1;

assign w11_address18 = p_cast88_cast_fu_1846_p1;

assign w11_address19 = zext_ln42_fu_1829_p1;

assign w11_address2 = p_cast104_cast_fu_2046_p1;

assign w11_address3 = p_cast103_cast_fu_2033_p1;

assign w11_address4 = p_cast102_cast_cast_fu_2020_p1;

assign w11_address5 = p_cast101_cast_cast_fu_2011_p1;

assign w11_address6 = p_cast100_cast_cast_fu_2002_p1;

assign w11_address7 = p_cast99_cast_cast_fu_1993_p1;

assign w11_address8 = p_cast98_cast_fu_1976_p1;

assign w11_address9 = p_cast97_cast_fu_1963_p1;

assign x_11_fu_2575_p2 = (conv_i2_i_355_i_i135_reg_1377 + add_ln53_67_fu_2571_p2);

assign x_12_fu_2585_p2 = (conv_i2_i_556_i_i133_reg_1391 + add_ln53_69_fu_2581_p2);

assign x_13_fu_2595_p2 = (conv_i2_i_757_i_i131_reg_1405 + add_ln53_71_fu_2591_p2);

assign x_14_fu_2605_p2 = (conv_i2_i_958_i_i129_reg_1419 + add_ln53_73_fu_2601_p2);

assign x_15_fu_2615_p2 = (conv_i2_i_1159_i_i127_reg_1433 + add_ln53_75_fu_2611_p2);

assign x_16_fu_2625_p2 = (conv_i2_i_1360_i_i125_reg_1447 + add_ln53_77_fu_2621_p2);

assign x_17_fu_2635_p2 = (conv_i2_i_1561_i_i123_reg_1461 + add_ln53_79_fu_2631_p2);

assign x_18_fu_2645_p2 = (conv_i2_i_1762_i_i121_reg_1475 + add_ln53_81_fu_2641_p2);

assign x_19_fu_2655_p2 = (conv_i2_i_1963_i_i119_reg_1489 + add_ln53_83_fu_2651_p2);

assign x_fu_2565_p2 = (conv_i2_i_154_i_i137_reg_1363 + add_ln53_fu_2561_p2);

assign zext_ln42_fu_1829_p1 = in_index117_reg_516;

endmodule //myproject_dense_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_10u_config11_s
