// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer14_out_dout,
        layer14_out_empty_n,
        layer14_out_read,
        layer5_out_din,
        layer5_out_full_n,
        layer5_out_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] layer14_out_dout;
input   layer14_out_empty_n;
output   layer14_out_read;
output  [127:0] layer5_out_din;
input   layer5_out_full_n;
output   layer5_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer14_out_read;
reg layer5_out_write;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    layer14_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln51_fu_274_p2;
wire   [15:0] trunc_ln57_fu_286_p1;
reg   [15:0] trunc_ln57_reg_339;
reg   [15:0] tmp_reg_344;
reg   [15:0] trunc_ln57_2_reg_349;
reg   [15:0] trunc_ln57_3_reg_354;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_start;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_done;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_idle;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_ready;
wire   [127:0] grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_layer5_out_din;
wire    grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_layer5_out_write;
reg    grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_start_reg;
reg    ap_block_state2_ignore_call8;
wire    ap_CS_fsm_state3;
reg   [5:0] indvar_flatten_fu_148;
wire   [5:0] add_ln51_fu_280_p2;
reg    ap_block_state2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_start_reg = 1'b0;
end

myproject_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_start),
    .ap_done(grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_done),
    .ap_idle(grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_idle),
    .ap_ready(grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_ready),
    .p_read(trunc_ln57_reg_339),
    .p_read1(tmp_reg_344),
    .p_read2(trunc_ln57_2_reg_349),
    .p_read3(trunc_ln57_3_reg_354),
    .layer5_out_din(grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_layer5_out_din),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_layer5_out_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln51_fu_274_p2 == 1'd0) & (layer14_out_empty_n == 1'b0)) & (icmp_ln51_fu_274_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_start_reg <= 1'b1;
        end else if ((grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_ready == 1'b1)) begin
            grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_fu_148 <= 6'd0;
    end else if ((~((icmp_ln51_fu_274_p2 == 1'd0) & (layer14_out_empty_n == 1'b0)) & (icmp_ln51_fu_274_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_148 <= add_ln51_fu_280_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln51_fu_274_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_reg_344 <= {{layer14_out_dout[31:16]}};
        trunc_ln57_2_reg_349 <= {{layer14_out_dout[47:32]}};
        trunc_ln57_3_reg_354 <= {{layer14_out_dout[63:48]}};
        trunc_ln57_reg_339 <= trunc_ln57_fu_286_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_274_p2 == 1'd0) & (layer14_out_empty_n == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((~((icmp_ln51_fu_274_p2 == 1'd0) & (layer14_out_empty_n == 1'b0)) & (icmp_ln51_fu_274_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_274_p2 == 1'd0) & (layer14_out_empty_n == 1'b0)) & (icmp_ln51_fu_274_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_274_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer14_out_blk_n = layer14_out_empty_n;
    end else begin
        layer14_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln51_fu_274_p2 == 1'd0) & (layer14_out_empty_n == 1'b0)) & (icmp_ln51_fu_274_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        layer14_out_read = 1'b1;
    end else begin
        layer14_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        layer5_out_write = grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_layer5_out_write;
    end else begin
        layer5_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((icmp_ln51_fu_274_p2 == 1'd0) & (layer14_out_empty_n == 1'b0)) & (icmp_ln51_fu_274_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~((icmp_ln51_fu_274_p2 == 1'd0) & (layer14_out_empty_n == 1'b0)) & (icmp_ln51_fu_274_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_fu_280_p2 = (indvar_flatten_fu_148 + 6'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state2 = ((icmp_ln51_fu_274_p2 == 1'd0) & (layer14_out_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_ignore_call8 = ((icmp_ln51_fu_274_p2 == 1'd0) & (layer14_out_empty_n == 1'b0));
end

assign grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_start = grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_ap_start_reg;

assign icmp_ln51_fu_274_p2 = ((indvar_flatten_fu_148 == 6'd36) ? 1'b1 : 1'b0);

assign layer5_out_din = grp_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_8u_config5_s_fu_158_layer5_out_din;

assign trunc_ln57_fu_286_p1 = layer14_out_dout[15:0];

endmodule //myproject_conv_2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_8u_config5_s
