// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_array_array_ap_fixed_16_6_5_3_0_32u_config9_Pipeline_DataPrepare (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer7_out_dout,
        layer7_out_empty_n,
        layer7_out_read,
        p_0_7_0_0_063_out,
        p_0_7_0_0_063_out_ap_vld,
        p_0_6_0_0_061_out,
        p_0_6_0_0_061_out_ap_vld,
        p_0_5_0_0_059_out,
        p_0_5_0_0_059_out_ap_vld,
        p_0_4_0_0_057_out,
        p_0_4_0_0_057_out_ap_vld,
        p_0_3_0_0_055_out,
        p_0_3_0_0_055_out_ap_vld,
        p_0_2_0_0_053_out,
        p_0_2_0_0_053_out_ap_vld,
        p_0_1_0_0_051_out,
        p_0_1_0_0_051_out_ap_vld,
        p_0_0_0_0_049_out,
        p_0_0_0_0_049_out_ap_vld,
        p_0_7_0_0_047_out,
        p_0_7_0_0_047_out_ap_vld,
        p_0_6_0_0_045_out,
        p_0_6_0_0_045_out_ap_vld,
        p_0_5_0_0_043_out,
        p_0_5_0_0_043_out_ap_vld,
        p_0_4_0_0_041_out,
        p_0_4_0_0_041_out_ap_vld,
        p_0_3_0_0_039_out,
        p_0_3_0_0_039_out_ap_vld,
        p_0_2_0_0_037_out,
        p_0_2_0_0_037_out_ap_vld,
        p_0_1_0_0_035_out,
        p_0_1_0_0_035_out_ap_vld,
        p_0_0_0_0_033_out,
        p_0_0_0_0_033_out_ap_vld,
        p_0_7_0_0_031_out,
        p_0_7_0_0_031_out_ap_vld,
        p_0_6_0_0_029_out,
        p_0_6_0_0_029_out_ap_vld,
        p_0_5_0_0_027_out,
        p_0_5_0_0_027_out_ap_vld,
        p_0_4_0_0_025_out,
        p_0_4_0_0_025_out_ap_vld,
        p_0_3_0_0_023_out,
        p_0_3_0_0_023_out_ap_vld,
        p_0_2_0_0_021_out,
        p_0_2_0_0_021_out_ap_vld,
        p_0_1_0_0_019_out,
        p_0_1_0_0_019_out_ap_vld,
        p_0_0_0_0_017_out,
        p_0_0_0_0_017_out_ap_vld,
        p_0_7_0_0_015_out,
        p_0_7_0_0_015_out_ap_vld,
        p_0_6_0_0_013_out,
        p_0_6_0_0_013_out_ap_vld,
        p_0_5_0_0_011_out,
        p_0_5_0_0_011_out_ap_vld,
        p_0_4_0_0_09_out,
        p_0_4_0_0_09_out_ap_vld,
        p_0_3_0_0_07_out,
        p_0_3_0_0_07_out_ap_vld,
        p_0_2_0_0_05_out,
        p_0_2_0_0_05_out_ap_vld,
        p_0_1_0_0_03_out,
        p_0_1_0_0_03_out_ap_vld,
        p_0_0_0_0_01_out,
        p_0_0_0_0_01_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] layer7_out_dout;
input   layer7_out_empty_n;
output   layer7_out_read;
output  [15:0] p_0_7_0_0_063_out;
output   p_0_7_0_0_063_out_ap_vld;
output  [15:0] p_0_6_0_0_061_out;
output   p_0_6_0_0_061_out_ap_vld;
output  [15:0] p_0_5_0_0_059_out;
output   p_0_5_0_0_059_out_ap_vld;
output  [15:0] p_0_4_0_0_057_out;
output   p_0_4_0_0_057_out_ap_vld;
output  [15:0] p_0_3_0_0_055_out;
output   p_0_3_0_0_055_out_ap_vld;
output  [15:0] p_0_2_0_0_053_out;
output   p_0_2_0_0_053_out_ap_vld;
output  [15:0] p_0_1_0_0_051_out;
output   p_0_1_0_0_051_out_ap_vld;
output  [15:0] p_0_0_0_0_049_out;
output   p_0_0_0_0_049_out_ap_vld;
output  [15:0] p_0_7_0_0_047_out;
output   p_0_7_0_0_047_out_ap_vld;
output  [15:0] p_0_6_0_0_045_out;
output   p_0_6_0_0_045_out_ap_vld;
output  [15:0] p_0_5_0_0_043_out;
output   p_0_5_0_0_043_out_ap_vld;
output  [15:0] p_0_4_0_0_041_out;
output   p_0_4_0_0_041_out_ap_vld;
output  [15:0] p_0_3_0_0_039_out;
output   p_0_3_0_0_039_out_ap_vld;
output  [15:0] p_0_2_0_0_037_out;
output   p_0_2_0_0_037_out_ap_vld;
output  [15:0] p_0_1_0_0_035_out;
output   p_0_1_0_0_035_out_ap_vld;
output  [15:0] p_0_0_0_0_033_out;
output   p_0_0_0_0_033_out_ap_vld;
output  [15:0] p_0_7_0_0_031_out;
output   p_0_7_0_0_031_out_ap_vld;
output  [15:0] p_0_6_0_0_029_out;
output   p_0_6_0_0_029_out_ap_vld;
output  [15:0] p_0_5_0_0_027_out;
output   p_0_5_0_0_027_out_ap_vld;
output  [15:0] p_0_4_0_0_025_out;
output   p_0_4_0_0_025_out_ap_vld;
output  [15:0] p_0_3_0_0_023_out;
output   p_0_3_0_0_023_out_ap_vld;
output  [15:0] p_0_2_0_0_021_out;
output   p_0_2_0_0_021_out_ap_vld;
output  [15:0] p_0_1_0_0_019_out;
output   p_0_1_0_0_019_out_ap_vld;
output  [15:0] p_0_0_0_0_017_out;
output   p_0_0_0_0_017_out_ap_vld;
output  [15:0] p_0_7_0_0_015_out;
output   p_0_7_0_0_015_out_ap_vld;
output  [15:0] p_0_6_0_0_013_out;
output   p_0_6_0_0_013_out_ap_vld;
output  [15:0] p_0_5_0_0_011_out;
output   p_0_5_0_0_011_out_ap_vld;
output  [15:0] p_0_4_0_0_09_out;
output   p_0_4_0_0_09_out_ap_vld;
output  [15:0] p_0_3_0_0_07_out;
output   p_0_3_0_0_07_out_ap_vld;
output  [15:0] p_0_2_0_0_05_out;
output   p_0_2_0_0_05_out_ap_vld;
output  [15:0] p_0_1_0_0_03_out;
output   p_0_1_0_0_03_out_ap_vld;
output  [15:0] p_0_0_0_0_01_out;
output   p_0_0_0_0_01_out_ap_vld;

reg ap_idle;
reg layer7_out_read;
reg p_0_7_0_0_063_out_ap_vld;
reg p_0_6_0_0_061_out_ap_vld;
reg p_0_5_0_0_059_out_ap_vld;
reg p_0_4_0_0_057_out_ap_vld;
reg p_0_3_0_0_055_out_ap_vld;
reg p_0_2_0_0_053_out_ap_vld;
reg p_0_1_0_0_051_out_ap_vld;
reg p_0_0_0_0_049_out_ap_vld;
reg p_0_7_0_0_047_out_ap_vld;
reg p_0_6_0_0_045_out_ap_vld;
reg p_0_5_0_0_043_out_ap_vld;
reg p_0_4_0_0_041_out_ap_vld;
reg p_0_3_0_0_039_out_ap_vld;
reg p_0_2_0_0_037_out_ap_vld;
reg p_0_1_0_0_035_out_ap_vld;
reg p_0_0_0_0_033_out_ap_vld;
reg p_0_7_0_0_031_out_ap_vld;
reg p_0_6_0_0_029_out_ap_vld;
reg p_0_5_0_0_027_out_ap_vld;
reg p_0_4_0_0_025_out_ap_vld;
reg p_0_3_0_0_023_out_ap_vld;
reg p_0_2_0_0_021_out_ap_vld;
reg p_0_1_0_0_019_out_ap_vld;
reg p_0_0_0_0_017_out_ap_vld;
reg p_0_7_0_0_015_out_ap_vld;
reg p_0_6_0_0_013_out_ap_vld;
reg p_0_5_0_0_011_out_ap_vld;
reg p_0_4_0_0_09_out_ap_vld;
reg p_0_3_0_0_07_out_ap_vld;
reg p_0_2_0_0_05_out_ap_vld;
reg p_0_1_0_0_03_out_ap_vld;
reg p_0_0_0_0_01_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln33_fu_504_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer7_out_blk_n;
wire    ap_block_pp0_stage0;
wire   [1:0] trunc_ln33_fu_516_p1;
reg   [1:0] trunc_ln33_reg_1089;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] i_in_fu_134;
wire   [2:0] add_ln33_fu_510_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_in_1;
reg   [15:0] p_0_0_0_0_01_fu_138;
wire   [15:0] trunc_ln35_fu_525_p1;
reg   [15:0] p_0_1_0_0_03_fu_142;
reg   [15:0] p_0_2_0_0_05_fu_146;
reg   [15:0] p_0_3_0_0_07_fu_150;
reg   [15:0] p_0_4_0_0_09_fu_154;
reg   [15:0] p_0_5_0_0_011_fu_158;
reg   [15:0] p_0_6_0_0_013_fu_162;
reg   [15:0] p_0_7_0_0_015_fu_166;
reg   [15:0] p_0_0_0_0_017_fu_170;
reg   [15:0] p_0_1_0_0_019_fu_174;
reg   [15:0] p_0_2_0_0_021_fu_178;
reg   [15:0] p_0_3_0_0_023_fu_182;
reg   [15:0] p_0_4_0_0_025_fu_186;
reg   [15:0] p_0_5_0_0_027_fu_190;
reg   [15:0] p_0_6_0_0_029_fu_194;
reg   [15:0] p_0_7_0_0_031_fu_198;
reg   [15:0] p_0_0_0_0_033_fu_202;
reg   [15:0] p_0_1_0_0_035_fu_206;
reg   [15:0] p_0_2_0_0_037_fu_210;
reg   [15:0] p_0_3_0_0_039_fu_214;
reg   [15:0] p_0_4_0_0_041_fu_218;
reg   [15:0] p_0_5_0_0_043_fu_222;
reg   [15:0] p_0_6_0_0_045_fu_226;
reg   [15:0] p_0_7_0_0_047_fu_230;
reg   [15:0] p_0_0_0_0_049_fu_234;
reg   [15:0] p_0_1_0_0_051_fu_238;
reg   [15:0] p_0_2_0_0_053_fu_242;
reg   [15:0] p_0_3_0_0_055_fu_246;
reg   [15:0] p_0_4_0_0_057_fu_250;
reg   [15:0] p_0_5_0_0_059_fu_254;
reg   [15:0] p_0_6_0_0_061_fu_258;
reg   [15:0] p_0_7_0_0_063_fu_262;
reg    ap_block_pp0_stage0_01001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

myproject_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln33_fu_504_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_in_fu_134 <= add_ln33_fu_510_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_in_fu_134 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln33_reg_1089 == 2'd1))) begin
        p_0_0_0_0_017_fu_170 <= trunc_ln35_fu_525_p1;
        p_0_1_0_0_019_fu_174 <= {{layer7_out_dout[31:16]}};
        p_0_2_0_0_021_fu_178 <= {{layer7_out_dout[47:32]}};
        p_0_3_0_0_023_fu_182 <= {{layer7_out_dout[63:48]}};
        p_0_4_0_0_025_fu_186 <= {{layer7_out_dout[79:64]}};
        p_0_5_0_0_027_fu_190 <= {{layer7_out_dout[95:80]}};
        p_0_6_0_0_029_fu_194 <= {{layer7_out_dout[111:96]}};
        p_0_7_0_0_031_fu_198 <= {{layer7_out_dout[127:112]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln33_reg_1089 == 2'd2))) begin
        p_0_0_0_0_01_fu_138 <= trunc_ln35_fu_525_p1;
        p_0_1_0_0_03_fu_142 <= {{layer7_out_dout[31:16]}};
        p_0_2_0_0_05_fu_146 <= {{layer7_out_dout[47:32]}};
        p_0_3_0_0_07_fu_150 <= {{layer7_out_dout[63:48]}};
        p_0_4_0_0_09_fu_154 <= {{layer7_out_dout[79:64]}};
        p_0_5_0_0_011_fu_158 <= {{layer7_out_dout[95:80]}};
        p_0_6_0_0_013_fu_162 <= {{layer7_out_dout[111:96]}};
        p_0_7_0_0_015_fu_166 <= {{layer7_out_dout[127:112]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln33_reg_1089 == 2'd0))) begin
        p_0_0_0_0_033_fu_202 <= trunc_ln35_fu_525_p1;
        p_0_1_0_0_035_fu_206 <= {{layer7_out_dout[31:16]}};
        p_0_2_0_0_037_fu_210 <= {{layer7_out_dout[47:32]}};
        p_0_3_0_0_039_fu_214 <= {{layer7_out_dout[63:48]}};
        p_0_4_0_0_041_fu_218 <= {{layer7_out_dout[79:64]}};
        p_0_5_0_0_043_fu_222 <= {{layer7_out_dout[95:80]}};
        p_0_6_0_0_045_fu_226 <= {{layer7_out_dout[111:96]}};
        p_0_7_0_0_047_fu_230 <= {{layer7_out_dout[127:112]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln33_reg_1089 == 2'd3))) begin
        p_0_0_0_0_049_fu_234 <= trunc_ln35_fu_525_p1;
        p_0_1_0_0_051_fu_238 <= {{layer7_out_dout[31:16]}};
        p_0_2_0_0_053_fu_242 <= {{layer7_out_dout[47:32]}};
        p_0_3_0_0_055_fu_246 <= {{layer7_out_dout[63:48]}};
        p_0_4_0_0_057_fu_250 <= {{layer7_out_dout[79:64]}};
        p_0_5_0_0_059_fu_254 <= {{layer7_out_dout[95:80]}};
        p_0_6_0_0_061_fu_258 <= {{layer7_out_dout[111:96]}};
        p_0_7_0_0_063_fu_262 <= {{layer7_out_dout[127:112]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln33_fu_504_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln33_reg_1089 <= trunc_ln33_fu_516_p1;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_in_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_in_1 = i_in_fu_134;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer7_out_blk_n = layer7_out_empty_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer7_out_read = 1'b1;
    end else begin
        layer7_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0_0_017_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_017_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0_0_01_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_01_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0_0_033_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_033_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_0_0_0_049_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0_0_049_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_1_0_0_019_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_019_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_1_0_0_035_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_035_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_1_0_0_03_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_03_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_1_0_0_051_out_ap_vld = 1'b1;
    end else begin
        p_0_1_0_0_051_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_2_0_0_021_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_021_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_2_0_0_037_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_037_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_2_0_0_053_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_053_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_2_0_0_05_out_ap_vld = 1'b1;
    end else begin
        p_0_2_0_0_05_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_3_0_0_023_out_ap_vld = 1'b1;
    end else begin
        p_0_3_0_0_023_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_3_0_0_039_out_ap_vld = 1'b1;
    end else begin
        p_0_3_0_0_039_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_3_0_0_055_out_ap_vld = 1'b1;
    end else begin
        p_0_3_0_0_055_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_3_0_0_07_out_ap_vld = 1'b1;
    end else begin
        p_0_3_0_0_07_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_4_0_0_025_out_ap_vld = 1'b1;
    end else begin
        p_0_4_0_0_025_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_4_0_0_041_out_ap_vld = 1'b1;
    end else begin
        p_0_4_0_0_041_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_4_0_0_057_out_ap_vld = 1'b1;
    end else begin
        p_0_4_0_0_057_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_4_0_0_09_out_ap_vld = 1'b1;
    end else begin
        p_0_4_0_0_09_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_5_0_0_011_out_ap_vld = 1'b1;
    end else begin
        p_0_5_0_0_011_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_5_0_0_027_out_ap_vld = 1'b1;
    end else begin
        p_0_5_0_0_027_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_5_0_0_043_out_ap_vld = 1'b1;
    end else begin
        p_0_5_0_0_043_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_5_0_0_059_out_ap_vld = 1'b1;
    end else begin
        p_0_5_0_0_059_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_6_0_0_013_out_ap_vld = 1'b1;
    end else begin
        p_0_6_0_0_013_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_6_0_0_029_out_ap_vld = 1'b1;
    end else begin
        p_0_6_0_0_029_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_6_0_0_045_out_ap_vld = 1'b1;
    end else begin
        p_0_6_0_0_045_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_6_0_0_061_out_ap_vld = 1'b1;
    end else begin
        p_0_6_0_0_061_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_7_0_0_015_out_ap_vld = 1'b1;
    end else begin
        p_0_7_0_0_015_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_7_0_0_031_out_ap_vld = 1'b1;
    end else begin
        p_0_7_0_0_031_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_7_0_0_047_out_ap_vld = 1'b1;
    end else begin
        p_0_7_0_0_047_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_504_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_0_7_0_0_063_out_ap_vld = 1'b1;
    end else begin
        p_0_7_0_0_063_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln33_fu_510_p2 = (ap_sig_allocacmp_i_in_1 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((layer7_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((layer7_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((layer7_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer7_out_empty_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln33_fu_504_p2 = ((ap_sig_allocacmp_i_in_1 == 3'd4) ? 1'b1 : 1'b0);

assign p_0_0_0_0_017_out = p_0_0_0_0_017_fu_170;

assign p_0_0_0_0_01_out = p_0_0_0_0_01_fu_138;

assign p_0_0_0_0_033_out = p_0_0_0_0_033_fu_202;

assign p_0_0_0_0_049_out = p_0_0_0_0_049_fu_234;

assign p_0_1_0_0_019_out = p_0_1_0_0_019_fu_174;

assign p_0_1_0_0_035_out = p_0_1_0_0_035_fu_206;

assign p_0_1_0_0_03_out = p_0_1_0_0_03_fu_142;

assign p_0_1_0_0_051_out = p_0_1_0_0_051_fu_238;

assign p_0_2_0_0_021_out = p_0_2_0_0_021_fu_178;

assign p_0_2_0_0_037_out = p_0_2_0_0_037_fu_210;

assign p_0_2_0_0_053_out = p_0_2_0_0_053_fu_242;

assign p_0_2_0_0_05_out = p_0_2_0_0_05_fu_146;

assign p_0_3_0_0_023_out = p_0_3_0_0_023_fu_182;

assign p_0_3_0_0_039_out = p_0_3_0_0_039_fu_214;

assign p_0_3_0_0_055_out = p_0_3_0_0_055_fu_246;

assign p_0_3_0_0_07_out = p_0_3_0_0_07_fu_150;

assign p_0_4_0_0_025_out = p_0_4_0_0_025_fu_186;

assign p_0_4_0_0_041_out = p_0_4_0_0_041_fu_218;

assign p_0_4_0_0_057_out = p_0_4_0_0_057_fu_250;

assign p_0_4_0_0_09_out = p_0_4_0_0_09_fu_154;

assign p_0_5_0_0_011_out = p_0_5_0_0_011_fu_158;

assign p_0_5_0_0_027_out = p_0_5_0_0_027_fu_190;

assign p_0_5_0_0_043_out = p_0_5_0_0_043_fu_222;

assign p_0_5_0_0_059_out = p_0_5_0_0_059_fu_254;

assign p_0_6_0_0_013_out = p_0_6_0_0_013_fu_162;

assign p_0_6_0_0_029_out = p_0_6_0_0_029_fu_194;

assign p_0_6_0_0_045_out = p_0_6_0_0_045_fu_226;

assign p_0_6_0_0_061_out = p_0_6_0_0_061_fu_258;

assign p_0_7_0_0_015_out = p_0_7_0_0_015_fu_166;

assign p_0_7_0_0_031_out = p_0_7_0_0_031_fu_198;

assign p_0_7_0_0_047_out = p_0_7_0_0_047_fu_230;

assign p_0_7_0_0_063_out = p_0_7_0_0_063_fu_262;

assign trunc_ln33_fu_516_p1 = ap_sig_allocacmp_i_in_1[1:0];

assign trunc_ln35_fu_525_p1 = layer7_out_dout[15:0];

endmodule //myproject_dense_array_array_ap_fixed_16_6_5_3_0_32u_config9_Pipeline_DataPrepare
