// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config10_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer9_out_dout,
        layer9_out_empty_n,
        layer9_out_read,
        layer10_out_din,
        layer10_out_full_n,
        layer10_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [511:0] layer9_out_dout;
input   layer9_out_empty_n;
output   layer9_out_read;
output  [511:0] layer10_out_din;
input   layer10_out_full_n;
output   layer10_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer9_out_read;
reg layer10_out_write;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    layer9_out_blk_n;
reg    layer10_out_blk_n;
wire    ap_CS_fsm_state2;
wire   [14:0] select_ln51_fu_861_p3;
reg   [14:0] select_ln51_reg_1468;
wire   [14:0] select_ln51_4_fu_875_p3;
reg   [14:0] select_ln51_4_reg_1473;
wire   [14:0] select_ln51_5_fu_889_p3;
reg   [14:0] select_ln51_5_reg_1478;
wire   [14:0] select_ln51_6_fu_903_p3;
reg   [14:0] select_ln51_6_reg_1483;
wire   [14:0] select_ln51_7_fu_917_p3;
reg   [14:0] select_ln51_7_reg_1488;
wire   [14:0] select_ln51_8_fu_931_p3;
reg   [14:0] select_ln51_8_reg_1493;
wire   [14:0] select_ln51_9_fu_945_p3;
reg   [14:0] select_ln51_9_reg_1498;
wire   [14:0] select_ln51_10_fu_959_p3;
reg   [14:0] select_ln51_10_reg_1503;
wire   [14:0] select_ln51_11_fu_973_p3;
reg   [14:0] select_ln51_11_reg_1508;
wire   [14:0] select_ln51_12_fu_987_p3;
reg   [14:0] select_ln51_12_reg_1513;
wire   [14:0] select_ln51_13_fu_1001_p3;
reg   [14:0] select_ln51_13_reg_1518;
wire   [14:0] select_ln51_14_fu_1015_p3;
reg   [14:0] select_ln51_14_reg_1523;
wire   [14:0] select_ln51_15_fu_1029_p3;
reg   [14:0] select_ln51_15_reg_1528;
wire   [14:0] select_ln51_16_fu_1043_p3;
reg   [14:0] select_ln51_16_reg_1533;
wire   [14:0] select_ln51_17_fu_1057_p3;
reg   [14:0] select_ln51_17_reg_1538;
wire   [14:0] select_ln51_18_fu_1071_p3;
reg   [14:0] select_ln51_18_reg_1543;
wire   [14:0] select_ln51_19_fu_1085_p3;
reg   [14:0] select_ln51_19_reg_1548;
wire   [14:0] select_ln51_20_fu_1099_p3;
reg   [14:0] select_ln51_20_reg_1553;
wire   [14:0] select_ln51_21_fu_1113_p3;
reg   [14:0] select_ln51_21_reg_1558;
wire   [14:0] select_ln51_22_fu_1127_p3;
reg   [14:0] select_ln51_22_reg_1563;
wire   [14:0] select_ln51_23_fu_1141_p3;
reg   [14:0] select_ln51_23_reg_1568;
wire   [14:0] select_ln51_24_fu_1155_p3;
reg   [14:0] select_ln51_24_reg_1573;
wire   [14:0] select_ln51_25_fu_1169_p3;
reg   [14:0] select_ln51_25_reg_1578;
wire   [14:0] select_ln51_26_fu_1183_p3;
reg   [14:0] select_ln51_26_reg_1583;
wire   [14:0] select_ln51_27_fu_1197_p3;
reg   [14:0] select_ln51_27_reg_1588;
wire   [14:0] select_ln51_28_fu_1211_p3;
reg   [14:0] select_ln51_28_reg_1593;
wire   [14:0] select_ln51_29_fu_1225_p3;
reg   [14:0] select_ln51_29_reg_1598;
wire   [14:0] select_ln51_30_fu_1239_p3;
reg   [14:0] select_ln51_30_reg_1603;
wire   [14:0] select_ln51_31_fu_1253_p3;
reg   [14:0] select_ln51_31_reg_1608;
wire   [14:0] select_ln51_32_fu_1267_p3;
reg   [14:0] select_ln51_32_reg_1613;
wire   [14:0] select_ln51_33_fu_1281_p3;
reg   [14:0] select_ln51_33_reg_1618;
wire   [14:0] select_ln51_34_fu_1295_p3;
reg   [14:0] select_ln51_34_reg_1623;
reg    ap_block_state1;
wire   [15:0] in_data_fu_227_p1;
wire   [0:0] icmp_ln51_fu_855_p2;
wire   [14:0] trunc_ln44_3_fu_231_p1;
wire   [15:0] in_data_10_fu_305_p4;
wire   [0:0] icmp_ln51_8_fu_869_p2;
wire   [14:0] in_data_10_cast_fu_315_p4;
wire   [15:0] in_data_11_fu_325_p4;
wire   [0:0] icmp_ln51_9_fu_883_p2;
wire   [14:0] in_data_11_cast_fu_335_p4;
wire   [15:0] in_data_12_fu_345_p4;
wire   [0:0] icmp_ln51_10_fu_897_p2;
wire   [14:0] in_data_12_cast_fu_355_p4;
wire   [15:0] tmp_fu_365_p4;
wire   [0:0] icmp_ln51_11_fu_911_p2;
wire   [14:0] tmp_cast_fu_375_p4;
wire   [15:0] tmp_s_fu_385_p4;
wire   [0:0] icmp_ln51_12_fu_925_p2;
wire   [14:0] tmp_cast_55_fu_395_p4;
wire   [15:0] tmp_3_fu_405_p4;
wire   [0:0] icmp_ln51_13_fu_939_p2;
wire   [14:0] tmp_3_cast_fu_415_p4;
wire   [15:0] tmp_4_fu_425_p4;
wire   [0:0] icmp_ln51_14_fu_953_p2;
wire   [14:0] tmp_4_cast_fu_435_p4;
wire   [15:0] tmp_5_fu_445_p4;
wire   [0:0] icmp_ln51_15_fu_967_p2;
wire   [14:0] tmp_5_cast_fu_455_p4;
wire   [15:0] tmp_6_fu_465_p4;
wire   [0:0] icmp_ln51_16_fu_981_p2;
wire   [14:0] tmp_6_cast_fu_475_p4;
wire   [15:0] tmp_7_fu_235_p4;
wire   [0:0] icmp_ln51_17_fu_995_p2;
wire   [14:0] tmp_7_cast_fu_485_p4;
wire   [15:0] tmp_8_fu_245_p4;
wire   [0:0] icmp_ln51_18_fu_1009_p2;
wire   [14:0] tmp_8_cast_fu_495_p4;
wire   [15:0] tmp_9_fu_255_p4;
wire   [0:0] icmp_ln51_19_fu_1023_p2;
wire   [14:0] tmp_9_cast_fu_505_p4;
wire   [15:0] tmp_24_fu_265_p4;
wire   [0:0] icmp_ln51_20_fu_1037_p2;
wire   [14:0] tmp_1_cast_fu_515_p4;
wire   [15:0] tmp_2_fu_525_p4;
wire   [0:0] icmp_ln51_21_fu_1051_p2;
wire   [14:0] tmp_2_cast_fu_535_p4;
wire   [15:0] tmp_10_fu_545_p4;
wire   [0:0] icmp_ln51_22_fu_1065_p2;
wire   [14:0] tmp_10_cast_fu_555_p4;
wire   [15:0] tmp_11_fu_565_p4;
wire   [0:0] icmp_ln51_23_fu_1079_p2;
wire   [14:0] tmp_11_cast_fu_575_p4;
wire   [15:0] tmp_12_fu_585_p4;
wire   [0:0] icmp_ln51_24_fu_1093_p2;
wire   [14:0] tmp_12_cast_fu_595_p4;
wire   [15:0] tmp_13_fu_605_p4;
wire   [0:0] icmp_ln51_25_fu_1107_p2;
wire   [14:0] tmp_13_cast_fu_615_p4;
wire   [15:0] tmp_14_fu_625_p4;
wire   [0:0] icmp_ln51_26_fu_1121_p2;
wire   [14:0] tmp_14_cast_fu_635_p4;
wire   [15:0] tmp_15_fu_645_p4;
wire   [0:0] icmp_ln51_27_fu_1135_p2;
wire   [14:0] tmp_15_cast_fu_655_p4;
wire   [15:0] tmp_16_fu_665_p4;
wire   [0:0] icmp_ln51_28_fu_1149_p2;
wire   [14:0] tmp_16_cast_fu_675_p4;
wire   [15:0] tmp_17_fu_685_p4;
wire   [0:0] icmp_ln51_29_fu_1163_p2;
wire   [14:0] tmp_17_cast_fu_695_p4;
wire   [15:0] tmp_18_fu_705_p4;
wire   [0:0] icmp_ln51_30_fu_1177_p2;
wire   [14:0] tmp_18_cast_fu_715_p4;
wire   [15:0] tmp_19_fu_725_p4;
wire   [0:0] icmp_ln51_31_fu_1191_p2;
wire   [14:0] tmp_19_cast_fu_735_p4;
wire   [15:0] tmp_20_fu_745_p4;
wire   [0:0] icmp_ln51_32_fu_1205_p2;
wire   [14:0] tmp_20_cast_fu_755_p4;
wire   [15:0] tmp_21_fu_765_p4;
wire   [0:0] icmp_ln51_33_fu_1219_p2;
wire   [14:0] tmp_21_cast_fu_775_p4;
wire   [15:0] tmp_22_fu_785_p4;
wire   [0:0] icmp_ln51_34_fu_1233_p2;
wire   [14:0] tmp_22_cast_fu_795_p4;
wire   [15:0] tmp_23_fu_805_p4;
wire   [0:0] icmp_ln51_35_fu_1247_p2;
wire   [14:0] tmp_23_cast_fu_815_p4;
wire   [15:0] tmp_25_fu_275_p4;
wire   [0:0] icmp_ln51_36_fu_1261_p2;
wire   [14:0] tmp_24_cast_fu_825_p4;
wire   [15:0] trunc_ln44_1_fu_285_p4;
wire   [0:0] icmp_ln51_37_fu_1275_p2;
wire   [14:0] tmp_25_cast_fu_835_p4;
wire   [15:0] trunc_ln44_2_fu_295_p4;
wire   [0:0] icmp_ln51_38_fu_1289_p2;
wire   [14:0] tmp_26_cast_fu_845_p4;
wire   [15:0] zext_ln51_32_fu_1393_p1;
wire   [15:0] zext_ln51_31_fu_1390_p1;
wire   [15:0] zext_ln51_30_fu_1387_p1;
wire   [15:0] zext_ln51_29_fu_1384_p1;
wire   [15:0] zext_ln51_28_fu_1381_p1;
wire   [15:0] zext_ln51_27_fu_1378_p1;
wire   [15:0] zext_ln51_26_fu_1375_p1;
wire   [15:0] zext_ln51_25_fu_1372_p1;
wire   [15:0] zext_ln51_24_fu_1369_p1;
wire   [15:0] zext_ln51_23_fu_1366_p1;
wire   [15:0] zext_ln51_22_fu_1363_p1;
wire   [15:0] zext_ln51_21_fu_1360_p1;
wire   [15:0] zext_ln51_20_fu_1357_p1;
wire   [15:0] zext_ln51_19_fu_1354_p1;
wire   [15:0] zext_ln51_18_fu_1351_p1;
wire   [15:0] zext_ln51_17_fu_1348_p1;
wire   [15:0] zext_ln51_16_fu_1345_p1;
wire   [15:0] zext_ln51_15_fu_1342_p1;
wire   [15:0] zext_ln51_14_fu_1339_p1;
wire   [15:0] zext_ln51_13_fu_1336_p1;
wire   [15:0] zext_ln51_12_fu_1333_p1;
wire   [15:0] zext_ln51_11_fu_1330_p1;
wire   [15:0] zext_ln51_10_fu_1327_p1;
wire   [15:0] zext_ln51_9_fu_1324_p1;
wire   [15:0] zext_ln51_8_fu_1321_p1;
wire   [15:0] zext_ln51_7_fu_1318_p1;
wire   [15:0] zext_ln51_6_fu_1315_p1;
wire   [15:0] zext_ln51_5_fu_1312_p1;
wire   [15:0] zext_ln51_4_fu_1309_p1;
wire   [15:0] zext_ln51_3_fu_1306_p1;
wire   [15:0] zext_ln51_fu_1303_p1;
wire   [510:0] or_ln57_s_fu_1396_p33;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        select_ln51_10_reg_1503 <= select_ln51_10_fu_959_p3;
        select_ln51_11_reg_1508 <= select_ln51_11_fu_973_p3;
        select_ln51_12_reg_1513 <= select_ln51_12_fu_987_p3;
        select_ln51_13_reg_1518 <= select_ln51_13_fu_1001_p3;
        select_ln51_14_reg_1523 <= select_ln51_14_fu_1015_p3;
        select_ln51_15_reg_1528 <= select_ln51_15_fu_1029_p3;
        select_ln51_16_reg_1533 <= select_ln51_16_fu_1043_p3;
        select_ln51_17_reg_1538 <= select_ln51_17_fu_1057_p3;
        select_ln51_18_reg_1543 <= select_ln51_18_fu_1071_p3;
        select_ln51_19_reg_1548 <= select_ln51_19_fu_1085_p3;
        select_ln51_20_reg_1553 <= select_ln51_20_fu_1099_p3;
        select_ln51_21_reg_1558 <= select_ln51_21_fu_1113_p3;
        select_ln51_22_reg_1563 <= select_ln51_22_fu_1127_p3;
        select_ln51_23_reg_1568 <= select_ln51_23_fu_1141_p3;
        select_ln51_24_reg_1573 <= select_ln51_24_fu_1155_p3;
        select_ln51_25_reg_1578 <= select_ln51_25_fu_1169_p3;
        select_ln51_26_reg_1583 <= select_ln51_26_fu_1183_p3;
        select_ln51_27_reg_1588 <= select_ln51_27_fu_1197_p3;
        select_ln51_28_reg_1593 <= select_ln51_28_fu_1211_p3;
        select_ln51_29_reg_1598 <= select_ln51_29_fu_1225_p3;
        select_ln51_30_reg_1603 <= select_ln51_30_fu_1239_p3;
        select_ln51_31_reg_1608 <= select_ln51_31_fu_1253_p3;
        select_ln51_32_reg_1613 <= select_ln51_32_fu_1267_p3;
        select_ln51_33_reg_1618 <= select_ln51_33_fu_1281_p3;
        select_ln51_34_reg_1623 <= select_ln51_34_fu_1295_p3;
        select_ln51_4_reg_1473 <= select_ln51_4_fu_875_p3;
        select_ln51_5_reg_1478 <= select_ln51_5_fu_889_p3;
        select_ln51_6_reg_1483 <= select_ln51_6_fu_903_p3;
        select_ln51_7_reg_1488 <= select_ln51_7_fu_917_p3;
        select_ln51_8_reg_1493 <= select_ln51_8_fu_931_p3;
        select_ln51_9_reg_1498 <= select_ln51_9_fu_945_p3;
        select_ln51_reg_1468 <= select_ln51_fu_861_p3;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (layer9_out_empty_n == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer10_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((layer10_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer10_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer10_out_blk_n = layer10_out_full_n;
    end else begin
        layer10_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer10_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer10_out_write = 1'b1;
    end else begin
        layer10_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer9_out_blk_n = layer9_out_empty_n;
    end else begin
        layer9_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (layer9_out_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer9_out_read = 1'b1;
    end else begin
        layer9_out_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (layer9_out_empty_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer10_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (layer9_out_empty_n == 1'b0));
end

assign icmp_ln51_10_fu_897_p2 = (($signed(in_data_12_fu_345_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_11_fu_911_p2 = (($signed(tmp_fu_365_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_12_fu_925_p2 = (($signed(tmp_s_fu_385_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_13_fu_939_p2 = (($signed(tmp_3_fu_405_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_14_fu_953_p2 = (($signed(tmp_4_fu_425_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_15_fu_967_p2 = (($signed(tmp_5_fu_445_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_16_fu_981_p2 = (($signed(tmp_6_fu_465_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_17_fu_995_p2 = (($signed(tmp_7_fu_235_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_18_fu_1009_p2 = (($signed(tmp_8_fu_245_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_19_fu_1023_p2 = (($signed(tmp_9_fu_255_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_20_fu_1037_p2 = (($signed(tmp_24_fu_265_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_21_fu_1051_p2 = (($signed(tmp_2_fu_525_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_22_fu_1065_p2 = (($signed(tmp_10_fu_545_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_23_fu_1079_p2 = (($signed(tmp_11_fu_565_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_24_fu_1093_p2 = (($signed(tmp_12_fu_585_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_25_fu_1107_p2 = (($signed(tmp_13_fu_605_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_26_fu_1121_p2 = (($signed(tmp_14_fu_625_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_27_fu_1135_p2 = (($signed(tmp_15_fu_645_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_28_fu_1149_p2 = (($signed(tmp_16_fu_665_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_29_fu_1163_p2 = (($signed(tmp_17_fu_685_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_30_fu_1177_p2 = (($signed(tmp_18_fu_705_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_31_fu_1191_p2 = (($signed(tmp_19_fu_725_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_32_fu_1205_p2 = (($signed(tmp_20_fu_745_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_33_fu_1219_p2 = (($signed(tmp_21_fu_765_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_34_fu_1233_p2 = (($signed(tmp_22_fu_785_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_35_fu_1247_p2 = (($signed(tmp_23_fu_805_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_36_fu_1261_p2 = (($signed(tmp_25_fu_275_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_37_fu_1275_p2 = (($signed(trunc_ln44_1_fu_285_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_38_fu_1289_p2 = (($signed(trunc_ln44_2_fu_295_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_8_fu_869_p2 = (($signed(in_data_10_fu_305_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_9_fu_883_p2 = (($signed(in_data_11_fu_325_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_855_p2 = (($signed(in_data_fu_227_p1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign in_data_10_cast_fu_315_p4 = {{layer9_out_dout[30:16]}};

assign in_data_10_fu_305_p4 = {{layer9_out_dout[31:16]}};

assign in_data_11_cast_fu_335_p4 = {{layer9_out_dout[46:32]}};

assign in_data_11_fu_325_p4 = {{layer9_out_dout[47:32]}};

assign in_data_12_cast_fu_355_p4 = {{layer9_out_dout[62:48]}};

assign in_data_12_fu_345_p4 = {{layer9_out_dout[63:48]}};

assign in_data_fu_227_p1 = layer9_out_dout[15:0];

assign layer10_out_din = or_ln57_s_fu_1396_p33;

assign or_ln57_s_fu_1396_p33 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{select_ln51_34_reg_1623}, {zext_ln51_32_fu_1393_p1}}, {zext_ln51_31_fu_1390_p1}}, {zext_ln51_30_fu_1387_p1}}, {zext_ln51_29_fu_1384_p1}}, {zext_ln51_28_fu_1381_p1}}, {zext_ln51_27_fu_1378_p1}}, {zext_ln51_26_fu_1375_p1}}, {zext_ln51_25_fu_1372_p1}}, {zext_ln51_24_fu_1369_p1}}, {zext_ln51_23_fu_1366_p1}}, {zext_ln51_22_fu_1363_p1}}, {zext_ln51_21_fu_1360_p1}}, {zext_ln51_20_fu_1357_p1}}, {zext_ln51_19_fu_1354_p1}}, {zext_ln51_18_fu_1351_p1}}, {zext_ln51_17_fu_1348_p1}}, {zext_ln51_16_fu_1345_p1}}, {zext_ln51_15_fu_1342_p1}}, {zext_ln51_14_fu_1339_p1}}, {zext_ln51_13_fu_1336_p1}}, {zext_ln51_12_fu_1333_p1}}, {zext_ln51_11_fu_1330_p1}}, {zext_ln51_10_fu_1327_p1}}, {zext_ln51_9_fu_1324_p1}}, {zext_ln51_8_fu_1321_p1}}, {zext_ln51_7_fu_1318_p1}}, {zext_ln51_6_fu_1315_p1}}, {zext_ln51_5_fu_1312_p1}}, {zext_ln51_4_fu_1309_p1}}, {zext_ln51_3_fu_1306_p1}}, {zext_ln51_fu_1303_p1}};

assign select_ln51_10_fu_959_p3 = ((icmp_ln51_14_fu_953_p2[0:0] == 1'b1) ? tmp_4_cast_fu_435_p4 : 15'd0);

assign select_ln51_11_fu_973_p3 = ((icmp_ln51_15_fu_967_p2[0:0] == 1'b1) ? tmp_5_cast_fu_455_p4 : 15'd0);

assign select_ln51_12_fu_987_p3 = ((icmp_ln51_16_fu_981_p2[0:0] == 1'b1) ? tmp_6_cast_fu_475_p4 : 15'd0);

assign select_ln51_13_fu_1001_p3 = ((icmp_ln51_17_fu_995_p2[0:0] == 1'b1) ? tmp_7_cast_fu_485_p4 : 15'd0);

assign select_ln51_14_fu_1015_p3 = ((icmp_ln51_18_fu_1009_p2[0:0] == 1'b1) ? tmp_8_cast_fu_495_p4 : 15'd0);

assign select_ln51_15_fu_1029_p3 = ((icmp_ln51_19_fu_1023_p2[0:0] == 1'b1) ? tmp_9_cast_fu_505_p4 : 15'd0);

assign select_ln51_16_fu_1043_p3 = ((icmp_ln51_20_fu_1037_p2[0:0] == 1'b1) ? tmp_1_cast_fu_515_p4 : 15'd0);

assign select_ln51_17_fu_1057_p3 = ((icmp_ln51_21_fu_1051_p2[0:0] == 1'b1) ? tmp_2_cast_fu_535_p4 : 15'd0);

assign select_ln51_18_fu_1071_p3 = ((icmp_ln51_22_fu_1065_p2[0:0] == 1'b1) ? tmp_10_cast_fu_555_p4 : 15'd0);

assign select_ln51_19_fu_1085_p3 = ((icmp_ln51_23_fu_1079_p2[0:0] == 1'b1) ? tmp_11_cast_fu_575_p4 : 15'd0);

assign select_ln51_20_fu_1099_p3 = ((icmp_ln51_24_fu_1093_p2[0:0] == 1'b1) ? tmp_12_cast_fu_595_p4 : 15'd0);

assign select_ln51_21_fu_1113_p3 = ((icmp_ln51_25_fu_1107_p2[0:0] == 1'b1) ? tmp_13_cast_fu_615_p4 : 15'd0);

assign select_ln51_22_fu_1127_p3 = ((icmp_ln51_26_fu_1121_p2[0:0] == 1'b1) ? tmp_14_cast_fu_635_p4 : 15'd0);

assign select_ln51_23_fu_1141_p3 = ((icmp_ln51_27_fu_1135_p2[0:0] == 1'b1) ? tmp_15_cast_fu_655_p4 : 15'd0);

assign select_ln51_24_fu_1155_p3 = ((icmp_ln51_28_fu_1149_p2[0:0] == 1'b1) ? tmp_16_cast_fu_675_p4 : 15'd0);

assign select_ln51_25_fu_1169_p3 = ((icmp_ln51_29_fu_1163_p2[0:0] == 1'b1) ? tmp_17_cast_fu_695_p4 : 15'd0);

assign select_ln51_26_fu_1183_p3 = ((icmp_ln51_30_fu_1177_p2[0:0] == 1'b1) ? tmp_18_cast_fu_715_p4 : 15'd0);

assign select_ln51_27_fu_1197_p3 = ((icmp_ln51_31_fu_1191_p2[0:0] == 1'b1) ? tmp_19_cast_fu_735_p4 : 15'd0);

assign select_ln51_28_fu_1211_p3 = ((icmp_ln51_32_fu_1205_p2[0:0] == 1'b1) ? tmp_20_cast_fu_755_p4 : 15'd0);

assign select_ln51_29_fu_1225_p3 = ((icmp_ln51_33_fu_1219_p2[0:0] == 1'b1) ? tmp_21_cast_fu_775_p4 : 15'd0);

assign select_ln51_30_fu_1239_p3 = ((icmp_ln51_34_fu_1233_p2[0:0] == 1'b1) ? tmp_22_cast_fu_795_p4 : 15'd0);

assign select_ln51_31_fu_1253_p3 = ((icmp_ln51_35_fu_1247_p2[0:0] == 1'b1) ? tmp_23_cast_fu_815_p4 : 15'd0);

assign select_ln51_32_fu_1267_p3 = ((icmp_ln51_36_fu_1261_p2[0:0] == 1'b1) ? tmp_24_cast_fu_825_p4 : 15'd0);

assign select_ln51_33_fu_1281_p3 = ((icmp_ln51_37_fu_1275_p2[0:0] == 1'b1) ? tmp_25_cast_fu_835_p4 : 15'd0);

assign select_ln51_34_fu_1295_p3 = ((icmp_ln51_38_fu_1289_p2[0:0] == 1'b1) ? tmp_26_cast_fu_845_p4 : 15'd0);

assign select_ln51_4_fu_875_p3 = ((icmp_ln51_8_fu_869_p2[0:0] == 1'b1) ? in_data_10_cast_fu_315_p4 : 15'd0);

assign select_ln51_5_fu_889_p3 = ((icmp_ln51_9_fu_883_p2[0:0] == 1'b1) ? in_data_11_cast_fu_335_p4 : 15'd0);

assign select_ln51_6_fu_903_p3 = ((icmp_ln51_10_fu_897_p2[0:0] == 1'b1) ? in_data_12_cast_fu_355_p4 : 15'd0);

assign select_ln51_7_fu_917_p3 = ((icmp_ln51_11_fu_911_p2[0:0] == 1'b1) ? tmp_cast_fu_375_p4 : 15'd0);

assign select_ln51_8_fu_931_p3 = ((icmp_ln51_12_fu_925_p2[0:0] == 1'b1) ? tmp_cast_55_fu_395_p4 : 15'd0);

assign select_ln51_9_fu_945_p3 = ((icmp_ln51_13_fu_939_p2[0:0] == 1'b1) ? tmp_3_cast_fu_415_p4 : 15'd0);

assign select_ln51_fu_861_p3 = ((icmp_ln51_fu_855_p2[0:0] == 1'b1) ? trunc_ln44_3_fu_231_p1 : 15'd0);

assign tmp_10_cast_fu_555_p4 = {{layer9_out_dout[254:240]}};

assign tmp_10_fu_545_p4 = {{layer9_out_dout[255:240]}};

assign tmp_11_cast_fu_575_p4 = {{layer9_out_dout[270:256]}};

assign tmp_11_fu_565_p4 = {{layer9_out_dout[271:256]}};

assign tmp_12_cast_fu_595_p4 = {{layer9_out_dout[286:272]}};

assign tmp_12_fu_585_p4 = {{layer9_out_dout[287:272]}};

assign tmp_13_cast_fu_615_p4 = {{layer9_out_dout[302:288]}};

assign tmp_13_fu_605_p4 = {{layer9_out_dout[303:288]}};

assign tmp_14_cast_fu_635_p4 = {{layer9_out_dout[318:304]}};

assign tmp_14_fu_625_p4 = {{layer9_out_dout[319:304]}};

assign tmp_15_cast_fu_655_p4 = {{layer9_out_dout[334:320]}};

assign tmp_15_fu_645_p4 = {{layer9_out_dout[335:320]}};

assign tmp_16_cast_fu_675_p4 = {{layer9_out_dout[350:336]}};

assign tmp_16_fu_665_p4 = {{layer9_out_dout[351:336]}};

assign tmp_17_cast_fu_695_p4 = {{layer9_out_dout[366:352]}};

assign tmp_17_fu_685_p4 = {{layer9_out_dout[367:352]}};

assign tmp_18_cast_fu_715_p4 = {{layer9_out_dout[382:368]}};

assign tmp_18_fu_705_p4 = {{layer9_out_dout[383:368]}};

assign tmp_19_cast_fu_735_p4 = {{layer9_out_dout[398:384]}};

assign tmp_19_fu_725_p4 = {{layer9_out_dout[399:384]}};

assign tmp_1_cast_fu_515_p4 = {{layer9_out_dout[222:208]}};

assign tmp_20_cast_fu_755_p4 = {{layer9_out_dout[414:400]}};

assign tmp_20_fu_745_p4 = {{layer9_out_dout[415:400]}};

assign tmp_21_cast_fu_775_p4 = {{layer9_out_dout[430:416]}};

assign tmp_21_fu_765_p4 = {{layer9_out_dout[431:416]}};

assign tmp_22_cast_fu_795_p4 = {{layer9_out_dout[446:432]}};

assign tmp_22_fu_785_p4 = {{layer9_out_dout[447:432]}};

assign tmp_23_cast_fu_815_p4 = {{layer9_out_dout[462:448]}};

assign tmp_23_fu_805_p4 = {{layer9_out_dout[463:448]}};

assign tmp_24_cast_fu_825_p4 = {{layer9_out_dout[478:464]}};

assign tmp_24_fu_265_p4 = {{layer9_out_dout[223:208]}};

assign tmp_25_cast_fu_835_p4 = {{layer9_out_dout[494:480]}};

assign tmp_25_fu_275_p4 = {{layer9_out_dout[479:464]}};

assign tmp_26_cast_fu_845_p4 = {{layer9_out_dout[510:496]}};

assign tmp_2_cast_fu_535_p4 = {{layer9_out_dout[238:224]}};

assign tmp_2_fu_525_p4 = {{layer9_out_dout[239:224]}};

assign tmp_3_cast_fu_415_p4 = {{layer9_out_dout[110:96]}};

assign tmp_3_fu_405_p4 = {{layer9_out_dout[111:96]}};

assign tmp_4_cast_fu_435_p4 = {{layer9_out_dout[126:112]}};

assign tmp_4_fu_425_p4 = {{layer9_out_dout[127:112]}};

assign tmp_5_cast_fu_455_p4 = {{layer9_out_dout[142:128]}};

assign tmp_5_fu_445_p4 = {{layer9_out_dout[143:128]}};

assign tmp_6_cast_fu_475_p4 = {{layer9_out_dout[158:144]}};

assign tmp_6_fu_465_p4 = {{layer9_out_dout[159:144]}};

assign tmp_7_cast_fu_485_p4 = {{layer9_out_dout[174:160]}};

assign tmp_7_fu_235_p4 = {{layer9_out_dout[175:160]}};

assign tmp_8_cast_fu_495_p4 = {{layer9_out_dout[190:176]}};

assign tmp_8_fu_245_p4 = {{layer9_out_dout[191:176]}};

assign tmp_9_cast_fu_505_p4 = {{layer9_out_dout[206:192]}};

assign tmp_9_fu_255_p4 = {{layer9_out_dout[207:192]}};

assign tmp_cast_55_fu_395_p4 = {{layer9_out_dout[94:80]}};

assign tmp_cast_fu_375_p4 = {{layer9_out_dout[78:64]}};

assign tmp_fu_365_p4 = {{layer9_out_dout[79:64]}};

assign tmp_s_fu_385_p4 = {{layer9_out_dout[95:80]}};

assign trunc_ln44_1_fu_285_p4 = {{layer9_out_dout[495:480]}};

assign trunc_ln44_2_fu_295_p4 = {{layer9_out_dout[511:496]}};

assign trunc_ln44_3_fu_231_p1 = layer9_out_dout[14:0];

assign zext_ln51_10_fu_1327_p1 = select_ln51_11_reg_1508;

assign zext_ln51_11_fu_1330_p1 = select_ln51_12_reg_1513;

assign zext_ln51_12_fu_1333_p1 = select_ln51_13_reg_1518;

assign zext_ln51_13_fu_1336_p1 = select_ln51_14_reg_1523;

assign zext_ln51_14_fu_1339_p1 = select_ln51_15_reg_1528;

assign zext_ln51_15_fu_1342_p1 = select_ln51_16_reg_1533;

assign zext_ln51_16_fu_1345_p1 = select_ln51_17_reg_1538;

assign zext_ln51_17_fu_1348_p1 = select_ln51_18_reg_1543;

assign zext_ln51_18_fu_1351_p1 = select_ln51_19_reg_1548;

assign zext_ln51_19_fu_1354_p1 = select_ln51_20_reg_1553;

assign zext_ln51_20_fu_1357_p1 = select_ln51_21_reg_1558;

assign zext_ln51_21_fu_1360_p1 = select_ln51_22_reg_1563;

assign zext_ln51_22_fu_1363_p1 = select_ln51_23_reg_1568;

assign zext_ln51_23_fu_1366_p1 = select_ln51_24_reg_1573;

assign zext_ln51_24_fu_1369_p1 = select_ln51_25_reg_1578;

assign zext_ln51_25_fu_1372_p1 = select_ln51_26_reg_1583;

assign zext_ln51_26_fu_1375_p1 = select_ln51_27_reg_1588;

assign zext_ln51_27_fu_1378_p1 = select_ln51_28_reg_1593;

assign zext_ln51_28_fu_1381_p1 = select_ln51_29_reg_1598;

assign zext_ln51_29_fu_1384_p1 = select_ln51_30_reg_1603;

assign zext_ln51_30_fu_1387_p1 = select_ln51_31_reg_1608;

assign zext_ln51_31_fu_1390_p1 = select_ln51_32_reg_1613;

assign zext_ln51_32_fu_1393_p1 = select_ln51_33_reg_1618;

assign zext_ln51_3_fu_1306_p1 = select_ln51_4_reg_1473;

assign zext_ln51_4_fu_1309_p1 = select_ln51_5_reg_1478;

assign zext_ln51_5_fu_1312_p1 = select_ln51_6_reg_1483;

assign zext_ln51_6_fu_1315_p1 = select_ln51_7_reg_1488;

assign zext_ln51_7_fu_1318_p1 = select_ln51_8_reg_1493;

assign zext_ln51_8_fu_1321_p1 = select_ln51_9_reg_1498;

assign zext_ln51_9_fu_1324_p1 = select_ln51_10_reg_1503;

assign zext_ln51_fu_1303_p1 = select_ln51_reg_1468;

endmodule //myproject_relu_array_ap_fixed_32u_array_ap_fixed_16_6_5_3_0_32u_relu_config10_s
