// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11,
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11;
input  [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln42_fu_568_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] w2_address0;
reg    w2_ce0;
wire  signed [6:0] w2_q0;
wire   [5:0] w2_address1;
reg    w2_ce1;
wire  signed [6:0] w2_q1;
wire   [5:0] w2_address2;
reg    w2_ce2;
wire  signed [6:0] w2_q2;
wire   [5:0] w2_address3;
reg    w2_ce3;
wire  signed [6:0] w2_q3;
reg   [0:0] do_init_reg_127;
reg   [3:0] in_index21_reg_269;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_283;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_295;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_307;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_reg_319;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_reg_331;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_reg_343;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_reg_355;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_reg_367;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_reg_379;
reg   [11:0] empty_reg_391;
reg   [11:0] empty_79_reg_405;
reg   [11:0] empty_80_reg_419;
reg   [11:0] empty_81_reg_433;
wire   [15:0] a_fu_505_p11;
reg   [15:0] a_reg_757;
wire   [3:0] in_index_fu_562_p2;
reg   [3:0] in_index_reg_782;
reg   [0:0] icmp_ln42_reg_787;
wire   [11:0] x_fu_597_p2;
reg    ap_enable_reg_pp0_iter1;
wire   [11:0] x_8_fu_623_p2;
wire   [11:0] x_9_fu_649_p2;
wire   [11:0] x_10_fu_675_p2;
wire    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_do_init_phi_fu_131_p6;
wire    ap_block_pp0_stage0;
reg   [3:0] ap_phi_mux_in_index21_phi_fu_273_p6;
reg   [15:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_phi_fu_287_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_283;
reg   [15:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_phi_fu_299_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_295;
reg   [15:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_phi_fu_311_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_307;
reg   [15:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_phi_fu_323_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_reg_319;
reg   [15:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_phi_fu_335_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_reg_331;
reg   [15:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_phi_fu_347_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_reg_343;
reg   [15:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_phi_fu_359_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_reg_355;
reg   [15:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_phi_fu_371_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_reg_367;
reg   [15:0] ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_phi_fu_383_p4;
wire   [15:0] ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_reg_379;
wire   [63:0] zext_ln42_fu_492_p1;
wire   [63:0] add_ln55_cast_fu_535_p1;
wire   [63:0] add_ln55_31_cast_fu_546_p1;
wire   [63:0] add_ln55_32_cast_fu_557_p1;
wire   [4:0] zext_ln42_7_fu_501_p1;
wire   [4:0] add_ln55_fu_529_p2;
wire   [4:0] add_ln55_30_fu_540_p2;
wire   [5:0] zext_ln42_6_fu_497_p1;
wire   [5:0] add_ln55_31_fu_551_p2;
wire  signed [15:0] mul_ln53_fu_581_p0;
wire  signed [18:0] sext_ln73_fu_574_p1;
wire   [18:0] mul_ln53_fu_581_p2;
wire   [11:0] trunc_ln_fu_587_p4;
wire  signed [15:0] mul_ln53_32_fu_607_p0;
wire   [18:0] mul_ln53_32_fu_607_p2;
wire   [11:0] trunc_ln53_s_fu_613_p4;
wire  signed [15:0] mul_ln53_33_fu_633_p0;
wire   [18:0] mul_ln53_33_fu_633_p2;
wire   [11:0] trunc_ln53_31_fu_639_p4;
wire  signed [15:0] mul_ln53_34_fu_659_p0;
wire   [18:0] mul_ln53_34_fu_659_p2;
wire   [11:0] trunc_ln53_32_fu_665_p4;
wire   [13:0] shl_ln_fu_681_p3;
wire   [13:0] shl_ln111_8_fu_693_p3;
wire   [13:0] shl_ln111_9_fu_705_p3;
wire   [13:0] shl_ln111_s_fu_717_p3;
wire  signed [15:0] sext_ln110_fu_689_p1;
wire  signed [15:0] sext_ln110_7_fu_701_p1;
wire  signed [15:0] sext_ln110_8_fu_713_p1;
wire  signed [15:0] sext_ln246_fu_725_p1;
reg   [15:0] ap_return_0_preg;
reg   [15:0] ap_return_1_preg;
reg   [15:0] ap_return_2_preg;
reg   [15:0] ap_return_3_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_163;
reg    ap_condition_39;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_return_0_preg = 16'd0;
#0 ap_return_1_preg = 16'd0;
#0 ap_return_2_preg = 16'd0;
#0 ap_return_3_preg = 16'd0;
end

myproject_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_w2_ROM_dEe #(
    .DataWidth( 7 ),
    .AddressRange( 36 ),
    .AddressWidth( 6 ))
w2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_address0),
    .ce0(w2_ce0),
    .q0(w2_q0),
    .address1(w2_address1),
    .ce1(w2_ce1),
    .q1(w2_q1),
    .address2(w2_address2),
    .ce2(w2_ce2),
    .q2(w2_q2),
    .address3(w2_address3),
    .ce3(w2_ce3),
    .q3(w2_q3)
);

myproject_mux_9_4_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
mux_9_4_16_1_1_U16(
    .din0(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_phi_fu_383_p4),
    .din1(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_phi_fu_371_p4),
    .din2(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_phi_fu_359_p4),
    .din3(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_phi_fu_347_p4),
    .din4(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_phi_fu_335_p4),
    .din5(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_phi_fu_323_p4),
    .din6(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_phi_fu_311_p4),
    .din7(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_phi_fu_299_p4),
    .din8(ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_phi_fu_287_p4),
    .din9(ap_phi_mux_in_index21_phi_fu_273_p6),
    .dout(a_fu_505_p11)
);

myproject_mul_16s_7s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 19 ))
mul_16s_7s_19_1_1_U17(
    .din0(mul_ln53_fu_581_p0),
    .din1(w2_q3),
    .dout(mul_ln53_fu_581_p2)
);

myproject_mul_16s_7s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 19 ))
mul_16s_7s_19_1_1_U18(
    .din0(mul_ln53_32_fu_607_p0),
    .din1(w2_q2),
    .dout(mul_ln53_32_fu_607_p2)
);

myproject_mul_16s_7s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 19 ))
mul_16s_7s_19_1_1_U19(
    .din0(mul_ln53_33_fu_633_p0),
    .din1(w2_q1),
    .dout(mul_ln53_33_fu_633_p2)
);

myproject_mul_16s_7s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 19 ))
mul_16s_7s_19_1_1_U20(
    .din0(mul_ln53_34_fu_659_p0),
    .din1(w2_q0),
    .dout(mul_ln53_34_fu_659_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_0_preg[2] <= 1'b0;
        ap_return_0_preg[3] <= 1'b0;
        ap_return_0_preg[4] <= 1'b0;
        ap_return_0_preg[5] <= 1'b0;
        ap_return_0_preg[6] <= 1'b0;
        ap_return_0_preg[7] <= 1'b0;
        ap_return_0_preg[8] <= 1'b0;
        ap_return_0_preg[9] <= 1'b0;
        ap_return_0_preg[10] <= 1'b0;
        ap_return_0_preg[11] <= 1'b0;
        ap_return_0_preg[12] <= 1'b0;
        ap_return_0_preg[13] <= 1'b0;
        ap_return_0_preg[14] <= 1'b0;
        ap_return_0_preg[15] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1))) begin
                        ap_return_0_preg[15 : 2] <= sext_ln110_fu_689_p1[15 : 2];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_1_preg[2] <= 1'b0;
        ap_return_1_preg[3] <= 1'b0;
        ap_return_1_preg[4] <= 1'b0;
        ap_return_1_preg[5] <= 1'b0;
        ap_return_1_preg[6] <= 1'b0;
        ap_return_1_preg[7] <= 1'b0;
        ap_return_1_preg[8] <= 1'b0;
        ap_return_1_preg[9] <= 1'b0;
        ap_return_1_preg[10] <= 1'b0;
        ap_return_1_preg[11] <= 1'b0;
        ap_return_1_preg[12] <= 1'b0;
        ap_return_1_preg[13] <= 1'b0;
        ap_return_1_preg[14] <= 1'b0;
        ap_return_1_preg[15] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1))) begin
                        ap_return_1_preg[15 : 2] <= sext_ln110_7_fu_701_p1[15 : 2];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_2_preg[2] <= 1'b0;
        ap_return_2_preg[3] <= 1'b0;
        ap_return_2_preg[4] <= 1'b0;
        ap_return_2_preg[5] <= 1'b0;
        ap_return_2_preg[6] <= 1'b0;
        ap_return_2_preg[7] <= 1'b0;
        ap_return_2_preg[8] <= 1'b0;
        ap_return_2_preg[9] <= 1'b0;
        ap_return_2_preg[10] <= 1'b0;
        ap_return_2_preg[11] <= 1'b0;
        ap_return_2_preg[12] <= 1'b0;
        ap_return_2_preg[13] <= 1'b0;
        ap_return_2_preg[14] <= 1'b0;
        ap_return_2_preg[15] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1))) begin
                        ap_return_2_preg[15 : 2] <= sext_ln110_8_fu_713_p1[15 : 2];
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_3_preg[2] <= 1'b0;
        ap_return_3_preg[3] <= 1'b0;
        ap_return_3_preg[4] <= 1'b0;
        ap_return_3_preg[5] <= 1'b0;
        ap_return_3_preg[6] <= 1'b0;
        ap_return_3_preg[7] <= 1'b0;
        ap_return_3_preg[8] <= 1'b0;
        ap_return_3_preg[9] <= 1'b0;
        ap_return_3_preg[10] <= 1'b0;
        ap_return_3_preg[11] <= 1'b0;
        ap_return_3_preg[12] <= 1'b0;
        ap_return_3_preg[13] <= 1'b0;
        ap_return_3_preg[14] <= 1'b0;
        ap_return_3_preg[15] <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1))) begin
                        ap_return_3_preg[15 : 2] <= sext_ln246_fu_725_p1[15 : 2];
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd0))) begin
        do_init_reg_127 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_127 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd0))) begin
        empty_79_reg_405 <= x_8_fu_623_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        empty_79_reg_405 <= 12'd136;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd0))) begin
        empty_80_reg_419 <= x_9_fu_649_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        empty_80_reg_419 <= 12'd4088;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd0))) begin
        empty_81_reg_433 <= x_10_fu_675_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        empty_81_reg_433 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd0))) begin
        empty_reg_391 <= x_fu_597_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        empty_reg_391 <= 12'd128;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd0))) begin
        in_index21_reg_269 <= in_index_reg_782;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index21_reg_269 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_39)) begin
        if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_283 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_283;
        end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_283 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_283 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_283;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_39)) begin
        if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_295 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_295;
        end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_295 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_295 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_295;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_39)) begin
        if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_307 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_307;
        end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_307 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_307 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_307;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_39)) begin
        if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_reg_319 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_reg_319;
        end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_reg_319 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_reg_319 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_reg_319;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_39)) begin
        if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_reg_331 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_reg_331;
        end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_reg_331 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_reg_331 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_reg_331;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_39)) begin
        if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_reg_343 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_reg_343;
        end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_reg_343 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_reg_343 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_reg_343;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_39)) begin
        if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_reg_355 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_reg_355;
        end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_reg_355 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_reg_355 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_reg_355;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_39)) begin
        if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_reg_367 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_reg_367;
        end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_reg_367 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_reg_367 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_reg_367;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_39)) begin
        if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_reg_379 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_reg_379;
        end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_reg_379 <= void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
        end else if ((1'b1 == 1'b1)) begin
            void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_reg_379 <= ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_reg_379;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_reg_757 <= a_fu_505_p11;
        icmp_ln42_reg_787 <= icmp_ln42_fu_568_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index_reg_782 <= in_index_fu_562_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_163)) begin
        if ((icmp_ln42_reg_787 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_131_p6 = 1'd1;
        end else if ((icmp_ln42_reg_787 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_131_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_131_p6 = do_init_reg_127;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_131_p6 = do_init_reg_127;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_163)) begin
        if ((icmp_ln42_reg_787 == 1'd1)) begin
            ap_phi_mux_in_index21_phi_fu_273_p6 = 4'd0;
        end else if ((icmp_ln42_reg_787 == 1'd0)) begin
            ap_phi_mux_in_index21_phi_fu_273_p6 = in_index_reg_782;
        end else begin
            ap_phi_mux_in_index21_phi_fu_273_p6 = in_index21_reg_269;
        end
    end else begin
        ap_phi_mux_in_index21_phi_fu_273_p6 = in_index21_reg_269;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_phi_fu_287_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_283;
    end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_phi_fu_287_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_phi_fu_287_p4 = ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_283;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_phi_fu_299_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_295;
    end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_phi_fu_299_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_phi_fu_299_p4 = ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_295;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_phi_fu_311_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_307;
    end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_phi_fu_311_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_phi_fu_311_p4 = ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_307;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_phi_fu_323_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_reg_319;
    end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_phi_fu_323_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_phi_fu_323_p4 = ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_reg_319;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_phi_fu_335_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_reg_331;
    end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_phi_fu_335_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_phi_fu_335_p4 = ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_reg_331;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_phi_fu_347_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_reg_343;
    end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_phi_fu_347_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_phi_fu_347_p4 = ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_reg_343;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_phi_fu_359_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_reg_355;
    end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_phi_fu_359_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_phi_fu_359_p4 = ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_reg_355;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_phi_fu_371_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_reg_367;
    end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_phi_fu_371_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_phi_fu_371_p4 = ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_reg_367;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd0)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_phi_fu_383_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_reg_379;
    end else if ((ap_phi_mux_do_init_phi_fu_131_p6 == 1'd1)) begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_phi_fu_383_p4 = void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
    end else begin
        ap_phi_mux_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_phi_fu_383_p4 = ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_reg_379;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln42_fu_568_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1))) begin
        ap_return_0 = sext_ln110_fu_689_p1;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1))) begin
        ap_return_1 = sext_ln110_7_fu_701_p1;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1))) begin
        ap_return_2 = sext_ln110_8_fu_713_p1;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_787 == 1'd1))) begin
        ap_return_3 = sext_ln246_fu_725_p1;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_ce0 = 1'b1;
    end else begin
        w2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_ce1 = 1'b1;
    end else begin
        w2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_ce2 = 1'b1;
    end else begin
        w2_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_ce3 = 1'b1;
    end else begin
        w2_ce3 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln55_30_fu_540_p2 = ($signed(zext_ln42_7_fu_501_p1) + $signed(5'd18));

assign add_ln55_31_cast_fu_546_p1 = add_ln55_30_fu_540_p2;

assign add_ln55_31_fu_551_p2 = (zext_ln42_6_fu_497_p1 + 6'd27);

assign add_ln55_32_cast_fu_557_p1 = add_ln55_31_fu_551_p2;

assign add_ln55_cast_fu_535_p1 = add_ln55_fu_529_p2;

assign add_ln55_fu_529_p2 = (zext_ln42_7_fu_501_p1 + 5'd9);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_163 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_39 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_61_reg_283 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_62_reg_295 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_63_reg_307 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_64_reg_319 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_65_reg_331 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_66_reg_343 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_67_reg_355 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_68_reg_367 = 'bx;

assign ap_phi_reg_pp0_iter0_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_69_reg_379 = 'bx;

assign icmp_ln42_fu_568_p2 = ((ap_phi_mux_in_index21_phi_fu_273_p6 == 4'd8) ? 1'b1 : 1'b0);

assign in_index_fu_562_p2 = (ap_phi_mux_in_index21_phi_fu_273_p6 + 4'd1);

assign mul_ln53_32_fu_607_p0 = sext_ln73_fu_574_p1;

assign mul_ln53_33_fu_633_p0 = sext_ln73_fu_574_p1;

assign mul_ln53_34_fu_659_p0 = sext_ln73_fu_574_p1;

assign mul_ln53_fu_581_p0 = sext_ln73_fu_574_p1;

assign sext_ln110_7_fu_701_p1 = $signed(shl_ln111_8_fu_693_p3);

assign sext_ln110_8_fu_713_p1 = $signed(shl_ln111_9_fu_705_p3);

assign sext_ln110_fu_689_p1 = $signed(shl_ln_fu_681_p3);

assign sext_ln246_fu_725_p1 = $signed(shl_ln111_s_fu_717_p3);

assign sext_ln73_fu_574_p1 = $signed(a_reg_757);

assign shl_ln111_8_fu_693_p3 = {{x_8_fu_623_p2}, {2'd0}};

assign shl_ln111_9_fu_705_p3 = {{x_9_fu_649_p2}, {2'd0}};

assign shl_ln111_s_fu_717_p3 = {{x_10_fu_675_p2}, {2'd0}};

assign shl_ln_fu_681_p3 = {{x_fu_597_p2}, {2'd0}};

assign trunc_ln53_31_fu_639_p4 = {{mul_ln53_33_fu_633_p2[18:7]}};

assign trunc_ln53_32_fu_665_p4 = {{mul_ln53_34_fu_659_p2[18:7]}};

assign trunc_ln53_s_fu_613_p4 = {{mul_ln53_32_fu_607_p2[18:7]}};

assign trunc_ln_fu_587_p4 = {{mul_ln53_fu_581_p2[18:7]}};

assign w2_address0 = add_ln55_32_cast_fu_557_p1;

assign w2_address1 = add_ln55_31_cast_fu_546_p1;

assign w2_address2 = add_ln55_cast_fu_535_p1;

assign w2_address3 = zext_ln42_fu_492_p1;

assign x_10_fu_675_p2 = (trunc_ln53_32_fu_665_p4 + empty_81_reg_433);

assign x_8_fu_623_p2 = (trunc_ln53_s_fu_613_p4 + empty_79_reg_405);

assign x_9_fu_649_p2 = (trunc_ln53_31_fu_639_p4 + empty_80_reg_419);

assign x_fu_597_p2 = (trunc_ln_fu_587_p4 + empty_reg_391);

assign zext_ln42_6_fu_497_p1 = ap_phi_mux_in_index21_phi_fu_273_p6;

assign zext_ln42_7_fu_501_p1 = ap_phi_mux_in_index21_phi_fu_273_p6;

assign zext_ln42_fu_492_p1 = ap_phi_mux_in_index21_phi_fu_273_p6;

always @ (posedge ap_clk) begin
    ap_return_0_preg[1:0] <= 2'b00;
    ap_return_1_preg[1:0] <= 2'b00;
    ap_return_2_preg[1:0] <= 2'b00;
    ap_return_3_preg[1:0] <= 2'b00;
end

endmodule //myproject_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s
