// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer5_out_dout,
        layer5_out_empty_n,
        layer5_out_read,
        layer6_out_din,
        layer6_out_full_n,
        layer6_out_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] layer5_out_dout;
input   layer5_out_empty_n;
output   layer5_out_read;
output  [127:0] layer6_out_din;
input   layer6_out_full_n;
output   layer6_out_write;

reg ap_idle;
reg layer5_out_read;
reg layer6_out_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_113_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer5_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer6_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [14:0] out_data_1_fu_284_p3;
reg   [14:0] out_data_1_reg_446;
wire   [14:0] out_data_3_fu_298_p3;
reg   [14:0] out_data_3_reg_451;
wire   [14:0] out_data_5_fu_312_p3;
reg   [14:0] out_data_5_reg_456;
wire   [14:0] out_data_7_fu_326_p3;
reg   [14:0] out_data_7_reg_461;
wire   [14:0] select_ln51_fu_340_p3;
reg   [14:0] select_ln51_reg_466;
wire   [14:0] select_ln51_1_fu_354_p3;
reg   [14:0] select_ln51_1_reg_471;
wire   [14:0] select_ln51_2_fu_368_p3;
reg   [14:0] select_ln51_2_reg_476;
wire   [14:0] select_ln51_3_fu_382_p3;
reg   [14:0] select_ln51_3_reg_481;
reg   [4:0] i_fu_88;
wire   [4:0] i_2_fu_119_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] in_data_fu_130_p1;
wire   [0:0] icmp_ln51_fu_278_p2;
wire   [14:0] trunc_ln44_1_fu_134_p1;
wire   [15:0] in_data_4_fu_198_p4;
wire   [0:0] icmp_ln51_1_fu_292_p2;
wire   [14:0] in_data_4_cast_fu_208_p4;
wire   [15:0] in_data_5_fu_138_p4;
wire   [0:0] icmp_ln51_2_fu_306_p2;
wire   [14:0] in_data_5_cast_fu_218_p4;
wire   [15:0] in_data_6_fu_148_p4;
wire   [0:0] icmp_ln51_3_fu_320_p2;
wire   [14:0] in_data_6_cast_fu_228_p4;
wire   [15:0] tmp_s_fu_158_p4;
wire   [0:0] icmp_ln51_4_fu_334_p2;
wire   [14:0] tmp_cast_fu_238_p4;
wire   [15:0] tmp_1_fu_168_p4;
wire   [0:0] icmp_ln51_5_fu_348_p2;
wire   [14:0] tmp_cast_54_fu_248_p4;
wire   [15:0] trunc_ln44_6_fu_178_p4;
wire   [0:0] icmp_ln51_6_fu_362_p2;
wire   [14:0] tmp_1_cast_fu_258_p4;
wire   [15:0] trunc_ln44_7_fu_188_p4;
wire   [0:0] icmp_ln51_7_fu_376_p2;
wire   [14:0] tmp_2_cast_fu_268_p4;
wire   [15:0] zext_ln51_2_fu_408_p1;
wire   [15:0] zext_ln51_1_fu_405_p1;
wire   [15:0] zext_ln51_fu_402_p1;
wire   [15:0] zext_ln45_3_fu_399_p1;
wire   [15:0] zext_ln45_2_fu_396_p1;
wire   [15:0] zext_ln45_1_fu_393_p1;
wire   [15:0] zext_ln45_fu_390_p1;
wire   [126:0] or_ln57_s_fu_411_p9;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

myproject_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln41_fu_113_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_88 <= i_2_fu_119_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_88 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        out_data_1_reg_446 <= out_data_1_fu_284_p3;
        out_data_3_reg_451 <= out_data_3_fu_298_p3;
        out_data_5_reg_456 <= out_data_5_fu_312_p3;
        out_data_7_reg_461 <= out_data_7_fu_326_p3;
        select_ln51_1_reg_471 <= select_ln51_1_fu_354_p3;
        select_ln51_2_reg_476 <= select_ln51_2_fu_368_p3;
        select_ln51_3_reg_481 <= select_ln51_3_fu_382_p3;
        select_ln51_reg_466 <= select_ln51_fu_340_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_113_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer5_out_blk_n = layer5_out_empty_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer5_out_read = 1'b1;
    end else begin
        layer5_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer6_out_blk_n = layer6_out_full_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer6_out_write = 1'b1;
    end else begin
        layer6_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((layer6_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer5_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((layer6_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer5_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((layer6_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer5_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer5_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer6_out_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign i_2_fu_119_p2 = (ap_sig_allocacmp_i_1 + 5'd1);

assign icmp_ln41_fu_113_p2 = ((ap_sig_allocacmp_i_1 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln51_1_fu_292_p2 = (($signed(in_data_4_fu_198_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_306_p2 = (($signed(in_data_5_fu_138_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_320_p2 = (($signed(in_data_6_fu_148_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_4_fu_334_p2 = (($signed(tmp_s_fu_158_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_5_fu_348_p2 = (($signed(tmp_1_fu_168_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_6_fu_362_p2 = (($signed(trunc_ln44_6_fu_178_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_7_fu_376_p2 = (($signed(trunc_ln44_7_fu_188_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_278_p2 = (($signed(in_data_fu_130_p1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign in_data_4_cast_fu_208_p4 = {{layer5_out_dout[30:16]}};

assign in_data_4_fu_198_p4 = {{layer5_out_dout[31:16]}};

assign in_data_5_cast_fu_218_p4 = {{layer5_out_dout[46:32]}};

assign in_data_5_fu_138_p4 = {{layer5_out_dout[47:32]}};

assign in_data_6_cast_fu_228_p4 = {{layer5_out_dout[62:48]}};

assign in_data_6_fu_148_p4 = {{layer5_out_dout[63:48]}};

assign in_data_fu_130_p1 = layer5_out_dout[15:0];

assign layer6_out_din = or_ln57_s_fu_411_p9;

assign or_ln57_s_fu_411_p9 = {{{{{{{{select_ln51_3_reg_481}, {zext_ln51_2_fu_408_p1}}, {zext_ln51_1_fu_405_p1}}, {zext_ln51_fu_402_p1}}, {zext_ln45_3_fu_399_p1}}, {zext_ln45_2_fu_396_p1}}, {zext_ln45_1_fu_393_p1}}, {zext_ln45_fu_390_p1}};

assign out_data_1_fu_284_p3 = ((icmp_ln51_fu_278_p2[0:0] == 1'b1) ? trunc_ln44_1_fu_134_p1 : 15'd0);

assign out_data_3_fu_298_p3 = ((icmp_ln51_1_fu_292_p2[0:0] == 1'b1) ? in_data_4_cast_fu_208_p4 : 15'd0);

assign out_data_5_fu_312_p3 = ((icmp_ln51_2_fu_306_p2[0:0] == 1'b1) ? in_data_5_cast_fu_218_p4 : 15'd0);

assign out_data_7_fu_326_p3 = ((icmp_ln51_3_fu_320_p2[0:0] == 1'b1) ? in_data_6_cast_fu_228_p4 : 15'd0);

assign select_ln51_1_fu_354_p3 = ((icmp_ln51_5_fu_348_p2[0:0] == 1'b1) ? tmp_cast_54_fu_248_p4 : 15'd0);

assign select_ln51_2_fu_368_p3 = ((icmp_ln51_6_fu_362_p2[0:0] == 1'b1) ? tmp_1_cast_fu_258_p4 : 15'd0);

assign select_ln51_3_fu_382_p3 = ((icmp_ln51_7_fu_376_p2[0:0] == 1'b1) ? tmp_2_cast_fu_268_p4 : 15'd0);

assign select_ln51_fu_340_p3 = ((icmp_ln51_4_fu_334_p2[0:0] == 1'b1) ? tmp_cast_fu_238_p4 : 15'd0);

assign tmp_1_cast_fu_258_p4 = {{layer5_out_dout[110:96]}};

assign tmp_1_fu_168_p4 = {{layer5_out_dout[95:80]}};

assign tmp_2_cast_fu_268_p4 = {{layer5_out_dout[126:112]}};

assign tmp_cast_54_fu_248_p4 = {{layer5_out_dout[94:80]}};

assign tmp_cast_fu_238_p4 = {{layer5_out_dout[78:64]}};

assign tmp_s_fu_158_p4 = {{layer5_out_dout[79:64]}};

assign trunc_ln44_1_fu_134_p1 = layer5_out_dout[14:0];

assign trunc_ln44_6_fu_178_p4 = {{layer5_out_dout[111:96]}};

assign trunc_ln44_7_fu_188_p4 = {{layer5_out_dout[127:112]}};

assign zext_ln45_1_fu_393_p1 = out_data_3_reg_451;

assign zext_ln45_2_fu_396_p1 = out_data_5_reg_456;

assign zext_ln45_3_fu_399_p1 = out_data_7_reg_461;

assign zext_ln45_fu_390_p1 = out_data_1_reg_446;

assign zext_ln51_1_fu_405_p1 = select_ln51_1_reg_471;

assign zext_ln51_2_fu_408_p1 = select_ln51_2_reg_476;

assign zext_ln51_fu_402_p1 = select_ln51_reg_466;

endmodule //myproject_relu_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_relu_config6_s
