// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config7_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer6_out_dout,
        layer6_out_empty_n,
        layer6_out_read,
        layer7_out_din,
        layer7_out_full_n,
        layer7_out_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [127:0] layer6_out_dout;
input   layer6_out_empty_n;
output   layer6_out_read;
output  [127:0] layer7_out_din;
input   layer7_out_full_n;
output   layer7_out_write;

reg ap_idle;
reg layer6_out_read;
reg layer7_out_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln55_reg_1714;
reg   [0:0] icmp_ln55_reg_1714_pp0_iter1_reg;
reg   [0:0] and_ln55_1_reg_1736;
reg    ap_predicate_op243_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_228_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] sY;
reg   [31:0] pY;
reg   [31:0] pX;
reg   [31:0] sX;
reg   [13:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1;
reg   [13:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_13;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_12;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_11;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_10;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_9;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_8;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_7;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_6;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_q0;
reg    layer6_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer7_out_blk_n;
reg   [0:0] icmp_ln109_reg_1710;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln55_fu_244_p2;
wire   [0:0] icmp_ln55_2_fu_258_p2;
reg   [0:0] icmp_ln55_2_reg_1718;
wire   [0:0] icmp_ln55_3_fu_264_p2;
reg   [0:0] icmp_ln55_3_reg_1723;
wire   [0:0] icmp_ln76_fu_276_p2;
reg   [0:0] icmp_ln76_reg_1728;
wire   [0:0] icmp_ln80_fu_330_p2;
reg   [0:0] icmp_ln80_reg_1732;
wire   [0:0] and_ln55_1_fu_787_p2;
wire   [11:0] select_ln65_fu_1125_p3;
reg   [11:0] select_ln65_reg_1740;
wire   [11:0] select_ln65_9_fu_1145_p3;
reg   [11:0] select_ln65_9_reg_1746;
wire   [11:0] select_ln65_11_fu_1165_p3;
reg   [11:0] select_ln65_11_reg_1752;
wire   [11:0] select_ln65_12_fu_1185_p3;
reg   [11:0] select_ln65_12_reg_1758;
wire   [11:0] select_ln65_14_fu_1205_p3;
reg   [11:0] select_ln65_14_reg_1764;
wire   [11:0] select_ln65_15_fu_1225_p3;
reg   [11:0] select_ln65_15_reg_1770;
wire   [11:0] select_ln65_17_fu_1245_p3;
reg   [11:0] select_ln65_17_reg_1776;
wire   [11:0] select_ln65_18_fu_1265_p3;
reg   [11:0] select_ln65_18_reg_1782;
wire   [11:0] select_ln65_20_fu_1285_p3;
reg   [11:0] select_ln65_20_reg_1788;
wire   [11:0] select_ln65_21_fu_1305_p3;
reg   [11:0] select_ln65_21_reg_1794;
wire   [11:0] select_ln65_23_fu_1325_p3;
reg   [11:0] select_ln65_23_reg_1800;
wire   [11:0] select_ln65_24_fu_1345_p3;
reg   [11:0] select_ln65_24_reg_1806;
wire   [11:0] select_ln65_26_fu_1365_p3;
reg   [11:0] select_ln65_26_reg_1812;
wire   [11:0] select_ln65_27_fu_1385_p3;
reg   [11:0] select_ln65_27_reg_1818;
wire   [11:0] select_ln65_29_fu_1405_p3;
reg   [11:0] select_ln65_29_reg_1824;
wire   [11:0] select_ln65_30_fu_1425_p3;
reg   [11:0] select_ln65_30_reg_1830;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_213_p4;
wire   [31:0] add_ln86_fu_1451_p2;
reg   [31:0] ap_phi_reg_pp0_iter1_storemerge_reg_209;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_reg_209;
wire   [31:0] add_ln80_fu_324_p2;
wire   [31:0] add_ln76_fu_270_p2;
wire   [31:0] add_ln91_fu_296_p2;
wire   [13:0] trunc_ln246_fu_511_p1;
wire   [13:0] trunc_ln246_1_fu_525_p1;
wire   [13:0] trunc_ln246_2_fu_539_p1;
wire   [13:0] trunc_ln246_3_fu_553_p1;
wire   [13:0] trunc_ln246_4_fu_567_p1;
wire   [13:0] trunc_ln246_5_fu_581_p1;
wire   [13:0] trunc_ln246_6_fu_595_p1;
wire   [13:0] trunc_ln201_fu_609_p1;
wire   [13:0] trunc_ln115_1_fu_357_p1;
reg   [4:0] indvar_flatten_fu_192;
wire   [4:0] add_ln109_fu_234_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] trunc_ln115_fu_353_p1;
wire   [31:0] select_ln91_fu_288_p3;
wire   [0:0] and_ln55_fu_783_p2;
wire   [0:0] icmp_ln55_1_fu_777_p2;
wire   [11:0] pool_window_fu_793_p4;
wire   [11:0] pool_window_1_fu_803_p4;
wire   [0:0] icmp_ln65_fu_1113_p2;
wire   [0:0] xor_ln65_fu_1119_p2;
wire   [11:0] pool_window_2_fu_813_p4;
wire   [11:0] pool_window_3_fu_823_p4;
wire   [0:0] icmp_ln65_9_fu_1133_p2;
wire   [0:0] xor_ln65_9_fu_1139_p2;
wire   [11:0] pool_window_4_fu_833_p4;
wire   [11:0] pool_window_5_fu_843_p4;
wire   [0:0] icmp_ln65_11_fu_1153_p2;
wire   [0:0] xor_ln65_11_fu_1159_p2;
wire   [11:0] pool_window_6_fu_853_p4;
wire   [11:0] pool_window_7_fu_863_p4;
wire   [0:0] icmp_ln65_12_fu_1173_p2;
wire   [0:0] xor_ln65_12_fu_1179_p2;
wire   [11:0] pool_window_8_fu_873_p4;
wire   [11:0] pool_window_9_fu_883_p4;
wire   [0:0] icmp_ln65_14_fu_1193_p2;
wire   [0:0] xor_ln65_14_fu_1199_p2;
wire   [11:0] pool_window_31_fu_893_p4;
wire   [11:0] pool_window_10_fu_903_p4;
wire   [0:0] icmp_ln65_15_fu_1213_p2;
wire   [0:0] xor_ln65_15_fu_1219_p2;
wire   [11:0] pool_window_11_fu_913_p4;
wire   [11:0] pool_window_12_fu_923_p4;
wire   [0:0] icmp_ln65_17_fu_1233_p2;
wire   [0:0] xor_ln65_17_fu_1239_p2;
wire   [11:0] pool_window_13_fu_933_p4;
wire   [11:0] pool_window_14_fu_943_p4;
wire   [0:0] icmp_ln65_18_fu_1253_p2;
wire   [0:0] xor_ln65_18_fu_1259_p2;
wire   [11:0] pool_window_15_fu_953_p4;
wire   [11:0] pool_window_16_fu_963_p4;
wire   [0:0] icmp_ln65_20_fu_1273_p2;
wire   [0:0] xor_ln65_20_fu_1279_p2;
wire   [11:0] pool_window_17_fu_973_p4;
wire   [11:0] pool_window_18_fu_983_p4;
wire   [0:0] icmp_ln65_21_fu_1293_p2;
wire   [0:0] xor_ln65_21_fu_1299_p2;
wire   [11:0] pool_window_19_fu_993_p4;
wire   [11:0] pool_window_20_fu_1003_p4;
wire   [0:0] icmp_ln65_23_fu_1313_p2;
wire   [0:0] xor_ln65_23_fu_1319_p2;
wire   [11:0] pool_window_21_fu_1013_p4;
wire   [11:0] pool_window_22_fu_1023_p4;
wire   [0:0] icmp_ln65_24_fu_1333_p2;
wire   [0:0] xor_ln65_24_fu_1339_p2;
wire   [11:0] pool_window_23_fu_1033_p4;
wire   [11:0] pool_window_24_fu_1043_p4;
wire   [0:0] icmp_ln65_26_fu_1353_p2;
wire   [0:0] xor_ln65_26_fu_1359_p2;
wire   [11:0] pool_window_25_fu_1053_p4;
wire   [11:0] pool_window_26_fu_1063_p4;
wire   [0:0] icmp_ln65_27_fu_1373_p2;
wire   [0:0] xor_ln65_27_fu_1379_p2;
wire   [11:0] pool_window_27_fu_1073_p4;
wire   [11:0] pool_window_28_fu_1083_p4;
wire   [0:0] icmp_ln65_29_fu_1393_p2;
wire   [0:0] xor_ln65_29_fu_1399_p2;
wire   [11:0] pool_window_29_fu_1093_p4;
wire   [11:0] pool_window_30_fu_1103_p4;
wire   [0:0] icmp_ln65_30_fu_1413_p2;
wire   [0:0] xor_ln65_30_fu_1419_p2;
wire   [0:0] icmp_ln86_fu_1437_p2;
wire   [31:0] select_ln86_fu_1443_p3;
wire   [0:0] icmp_ln65_10_fu_1464_p2;
wire   [0:0] xor_ln65_10_fu_1468_p2;
wire   [11:0] select_ln65_10_fu_1474_p3;
wire   [13:0] res_pack_fu_1480_p3;
wire   [0:0] icmp_ln65_13_fu_1492_p2;
wire   [0:0] xor_ln65_13_fu_1496_p2;
wire   [11:0] select_ln65_13_fu_1502_p3;
wire   [13:0] res_pack_1_fu_1508_p3;
wire   [0:0] icmp_ln65_16_fu_1520_p2;
wire   [0:0] xor_ln65_16_fu_1524_p2;
wire   [11:0] select_ln65_16_fu_1530_p3;
wire   [13:0] res_pack_2_fu_1536_p3;
wire   [0:0] icmp_ln65_19_fu_1548_p2;
wire   [0:0] xor_ln65_19_fu_1552_p2;
wire   [11:0] select_ln65_19_fu_1558_p3;
wire   [13:0] res_pack_3_fu_1564_p3;
wire   [0:0] icmp_ln65_22_fu_1576_p2;
wire   [0:0] xor_ln65_22_fu_1580_p2;
wire   [11:0] select_ln65_22_fu_1586_p3;
wire   [13:0] shl_ln68_4_fu_1592_p3;
wire   [0:0] icmp_ln65_25_fu_1604_p2;
wire   [0:0] xor_ln65_25_fu_1608_p2;
wire   [11:0] select_ln65_25_fu_1614_p3;
wire   [13:0] shl_ln68_5_fu_1620_p3;
wire   [0:0] icmp_ln65_28_fu_1632_p2;
wire   [0:0] xor_ln65_28_fu_1636_p2;
wire   [11:0] select_ln65_28_fu_1642_p3;
wire   [13:0] shl_ln68_6_fu_1648_p3;
wire   [0:0] icmp_ln65_31_fu_1660_p2;
wire   [0:0] xor_ln65_31_fu_1664_p2;
wire   [11:0] select_ln65_31_fu_1670_p3;
wire  signed [15:0] sext_ln42_6_fu_1656_p1;
wire  signed [15:0] sext_ln42_5_fu_1628_p1;
wire  signed [15:0] sext_ln42_4_fu_1600_p1;
wire  signed [15:0] sext_ln42_3_fu_1572_p1;
wire  signed [15:0] sext_ln42_2_fu_1544_p1;
wire  signed [15:0] sext_ln42_1_fu_1516_p1;
wire  signed [15:0] sext_ln42_fu_1488_p1;
wire   [125:0] or_ln72_s_fu_1676_p10;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_256;
reg    ap_condition_254;
reg    ap_condition_345;
reg    ap_condition_280;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 sY = 32'd0;
#0 pY = 32'd0;
#0 pX = 32'd0;
#0 sX = 32'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 = 14'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_13 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_12 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_11 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_10 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_9 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_8 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_7 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_6 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap = 14'd0;
#0 ap_done_reg = 1'b0;
end

myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config7_s_void_porcU #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_we0),
    .d0(trunc_ln115_fu_353_p1),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_q0)
);

myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config7_s_void_porcU #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_q0)
);

myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config7_s_void_porcU #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_q0)
);

myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config7_s_void_porcU #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_q0)
);

myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config7_s_void_porcU #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_q0)
);

myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config7_s_void_porcU #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_q0)
);

myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config7_s_void_porcU #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_q0)
);

myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config7_s_void_porcU #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(2'd3),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_q0)
);

myproject_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_254)) begin
        if ((1'b1 == ap_condition_256)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_209 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_209 <= ap_phi_reg_pp0_iter0_storemerge_reg_209;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_228_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_192 <= add_ln109_fu_234_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_192 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_345)) begin
        if ((icmp_ln76_fu_276_p2 == 1'd1)) begin
            pX <= 32'd0;
        end else if ((icmp_ln76_fu_276_p2 == 1'd0)) begin
            pX <= add_ln76_fu_270_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_280)) begin
        if ((icmp_ln80_fu_330_p2 == 1'd1)) begin
            pY <= 32'd0;
        end else if ((icmp_ln80_fu_330_p2 == 1'd0)) begin
            pY <= add_ln80_fu_324_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_345)) begin
        if ((icmp_ln76_fu_276_p2 == 1'd1)) begin
            sX <= 32'd0;
        end else if ((icmp_ln76_fu_276_p2 == 1'd0)) begin
            sX <= add_ln91_fu_296_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln55_reg_1714 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln55_1_reg_1736 <= and_ln55_1_fu_787_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln109_reg_1710 <= icmp_ln109_fu_228_p2;
        icmp_ln55_reg_1714_pp0_iter1_reg <= icmp_ln55_reg_1714;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_228_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln55_fu_244_p2 == 1'd1))) begin
        icmp_ln55_2_reg_1718 <= icmp_ln55_2_fu_258_p2;
        icmp_ln55_3_reg_1723 <= icmp_ln55_3_fu_264_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_228_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln55_reg_1714 <= icmp_ln55_fu_244_p2;
        icmp_ln76_reg_1728 <= icmp_ln76_fu_276_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_228_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln76_fu_276_p2 == 1'd1))) begin
        icmp_ln80_reg_1732 <= icmp_ln80_fu_330_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap <= {{layer6_out_dout[125:112]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1 <= {{layer6_out_dout[109:96]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_10 <= trunc_ln246_5_fu_581_p1;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_11 <= trunc_ln246_4_fu_567_p1;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_12 <= trunc_ln246_3_fu_553_p1;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_13 <= trunc_ln246_2_fu_539_p1;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2 <= {{layer6_out_dout[93:80]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3 <= {{layer6_out_dout[77:64]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4 <= {{layer6_out_dout[61:48]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5 <= {{layer6_out_dout[45:32]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_6 <= {{layer6_out_dout[29:16]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_7 <= trunc_ln115_1_fu_357_p1;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_8 <= trunc_ln201_fu_609_p1;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_9 <= trunc_ln246_6_fu_595_p1;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel <= trunc_ln246_1_fu_525_p1;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 <= trunc_ln246_fu_511_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln76_reg_1728 == 1'd1))) begin
        sY <= ap_phi_mux_storemerge_phi_fu_213_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln55_1_fu_787_p2) & (icmp_ln55_reg_1714 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln65_11_reg_1752 <= select_ln65_11_fu_1165_p3;
        select_ln65_12_reg_1758 <= select_ln65_12_fu_1185_p3;
        select_ln65_14_reg_1764 <= select_ln65_14_fu_1205_p3;
        select_ln65_15_reg_1770 <= select_ln65_15_fu_1225_p3;
        select_ln65_17_reg_1776 <= select_ln65_17_fu_1245_p3;
        select_ln65_18_reg_1782 <= select_ln65_18_fu_1265_p3;
        select_ln65_20_reg_1788 <= select_ln65_20_fu_1285_p3;
        select_ln65_21_reg_1794 <= select_ln65_21_fu_1305_p3;
        select_ln65_23_reg_1800 <= select_ln65_23_fu_1325_p3;
        select_ln65_24_reg_1806 <= select_ln65_24_fu_1345_p3;
        select_ln65_26_reg_1812 <= select_ln65_26_fu_1365_p3;
        select_ln65_27_reg_1818 <= select_ln65_27_fu_1385_p3;
        select_ln65_29_reg_1824 <= select_ln65_29_fu_1405_p3;
        select_ln65_30_reg_1830 <= select_ln65_30_fu_1425_p3;
        select_ln65_9_reg_1746 <= select_ln65_9_fu_1145_p3;
        select_ln65_reg_1740 <= select_ln65_fu_1125_p3;
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_228_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_reg_1732 == 1'd0) & (icmp_ln76_reg_1728 == 1'd1) & (icmp_ln109_reg_1710 == 1'd0))) begin
        ap_phi_mux_storemerge_phi_fu_213_p4 = add_ln86_fu_1451_p2;
    end else begin
        ap_phi_mux_storemerge_phi_fu_213_p4 = ap_phi_reg_pp0_iter1_storemerge_reg_209;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_192;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_blk_n = layer6_out_empty_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_read = 1'b1;
    end else begin
        layer6_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op243_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer7_out_blk_n = layer7_out_full_n;
    end else begin
        layer7_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op243_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer7_out_write = 1'b1;
    end else begin
        layer7_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_234_p2 = (ap_sig_allocacmp_indvar_flatten_load + 5'd1);

assign add_ln76_fu_270_p2 = (pX + 32'd1);

assign add_ln80_fu_324_p2 = (pY + 32'd1);

assign add_ln86_fu_1451_p2 = (sY + select_ln86_fu_1443_p3);

assign add_ln91_fu_296_p2 = (sX + select_ln91_fu_288_p3);

assign and_ln55_1_fu_787_p2 = (icmp_ln55_1_fu_777_p2 & and_ln55_fu_783_p2);

assign and_ln55_fu_783_p2 = (icmp_ln55_3_reg_1723 & icmp_ln55_2_reg_1718);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_predicate_op243_write_state3 == 1'b1) & (layer7_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer6_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_predicate_op243_write_state3 == 1'b1) & (layer7_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer6_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_predicate_op243_write_state3 == 1'b1) & (layer7_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer6_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer6_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op243_write_state3 == 1'b1) & (layer7_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_254 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_256 = ((icmp_ln109_fu_228_p2 == 1'd0) & (icmp_ln80_fu_330_p2 == 1'd1) & (icmp_ln76_fu_276_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_280 = ((icmp_ln109_fu_228_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln76_fu_276_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_345 = ((icmp_ln109_fu_228_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_storemerge_reg_209 = 'bx;

always @ (*) begin
    ap_predicate_op243_write_state3 = ((1'd1 == and_ln55_1_reg_1736) & (icmp_ln55_reg_1714_pp0_iter1_reg == 1'd1));
end

assign icmp_ln109_fu_228_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln55_1_fu_777_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln55_2_fu_258_p2 = (($signed(pY) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_3_fu_264_p2 = (($signed(pX) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_244_p2 = ((sX == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln65_10_fu_1464_p2 = (($signed(select_ln65_reg_1740) < $signed(select_ln65_9_reg_1746)) ? 1'b1 : 1'b0);

assign icmp_ln65_11_fu_1153_p2 = (($signed(pool_window_4_fu_833_p4) < $signed(pool_window_5_fu_843_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_12_fu_1173_p2 = (($signed(pool_window_6_fu_853_p4) < $signed(pool_window_7_fu_863_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_13_fu_1492_p2 = (($signed(select_ln65_11_reg_1752) < $signed(select_ln65_12_reg_1758)) ? 1'b1 : 1'b0);

assign icmp_ln65_14_fu_1193_p2 = (($signed(pool_window_8_fu_873_p4) < $signed(pool_window_9_fu_883_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_15_fu_1213_p2 = (($signed(pool_window_31_fu_893_p4) < $signed(pool_window_10_fu_903_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_16_fu_1520_p2 = (($signed(select_ln65_14_reg_1764) < $signed(select_ln65_15_reg_1770)) ? 1'b1 : 1'b0);

assign icmp_ln65_17_fu_1233_p2 = (($signed(pool_window_11_fu_913_p4) < $signed(pool_window_12_fu_923_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_18_fu_1253_p2 = (($signed(pool_window_13_fu_933_p4) < $signed(pool_window_14_fu_943_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_19_fu_1548_p2 = (($signed(select_ln65_17_reg_1776) < $signed(select_ln65_18_reg_1782)) ? 1'b1 : 1'b0);

assign icmp_ln65_20_fu_1273_p2 = (($signed(pool_window_15_fu_953_p4) < $signed(pool_window_16_fu_963_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_21_fu_1293_p2 = (($signed(pool_window_17_fu_973_p4) < $signed(pool_window_18_fu_983_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_22_fu_1576_p2 = (($signed(select_ln65_20_reg_1788) < $signed(select_ln65_21_reg_1794)) ? 1'b1 : 1'b0);

assign icmp_ln65_23_fu_1313_p2 = (($signed(pool_window_19_fu_993_p4) < $signed(pool_window_20_fu_1003_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_24_fu_1333_p2 = (($signed(pool_window_21_fu_1013_p4) < $signed(pool_window_22_fu_1023_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_25_fu_1604_p2 = (($signed(select_ln65_23_reg_1800) < $signed(select_ln65_24_reg_1806)) ? 1'b1 : 1'b0);

assign icmp_ln65_26_fu_1353_p2 = (($signed(pool_window_23_fu_1033_p4) < $signed(pool_window_24_fu_1043_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_27_fu_1373_p2 = (($signed(pool_window_25_fu_1053_p4) < $signed(pool_window_26_fu_1063_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_28_fu_1632_p2 = (($signed(select_ln65_26_reg_1812) < $signed(select_ln65_27_reg_1818)) ? 1'b1 : 1'b0);

assign icmp_ln65_29_fu_1393_p2 = (($signed(pool_window_27_fu_1073_p4) < $signed(pool_window_28_fu_1083_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_30_fu_1413_p2 = (($signed(pool_window_29_fu_1093_p4) < $signed(pool_window_30_fu_1103_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_31_fu_1660_p2 = (($signed(select_ln65_29_reg_1824) < $signed(select_ln65_30_reg_1830)) ? 1'b1 : 1'b0);

assign icmp_ln65_9_fu_1133_p2 = (($signed(pool_window_2_fu_813_p4) < $signed(pool_window_3_fu_823_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_1113_p2 = (($signed(pool_window_fu_793_p4) < $signed(pool_window_1_fu_803_p4)) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_276_p2 = ((add_ln76_fu_270_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_330_p2 = ((add_ln80_fu_324_p2 == 32'd4) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_1437_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign layer7_out_din = $signed(or_ln72_s_fu_1676_p10);

assign or_ln72_s_fu_1676_p10 = {{{{{{{{{select_ln65_31_fu_1670_p3}, {2'd0}}, {sext_ln42_6_fu_1656_p1}}, {sext_ln42_5_fu_1628_p1}}, {sext_ln42_4_fu_1600_p1}}, {sext_ln42_3_fu_1572_p1}}, {sext_ln42_2_fu_1544_p1}}, {sext_ln42_1_fu_1516_p1}}, {sext_ln42_fu_1488_p1}};

assign pool_window_10_fu_903_p4 = {{layer6_out_dout[45:34]}};

assign pool_window_11_fu_913_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_12[13:2]}};

assign pool_window_12_fu_923_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_q0[13:2]}};

assign pool_window_13_fu_933_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_4[13:2]}};

assign pool_window_14_fu_943_p4 = {{layer6_out_dout[61:50]}};

assign pool_window_15_fu_953_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_11[13:2]}};

assign pool_window_16_fu_963_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_q0[13:2]}};

assign pool_window_17_fu_973_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3[13:2]}};

assign pool_window_18_fu_983_p4 = {{layer6_out_dout[77:66]}};

assign pool_window_19_fu_993_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_10[13:2]}};

assign pool_window_1_fu_803_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_q0[13:2]}};

assign pool_window_20_fu_1003_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_q0[13:2]}};

assign pool_window_21_fu_1013_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2[13:2]}};

assign pool_window_22_fu_1023_p4 = {{layer6_out_dout[93:82]}};

assign pool_window_23_fu_1033_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_9[13:2]}};

assign pool_window_24_fu_1043_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_q0[13:2]}};

assign pool_window_25_fu_1053_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1[13:2]}};

assign pool_window_26_fu_1063_p4 = {{layer6_out_dout[109:98]}};

assign pool_window_27_fu_1073_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_8[13:2]}};

assign pool_window_28_fu_1083_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_q0[13:2]}};

assign pool_window_29_fu_1093_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap[13:2]}};

assign pool_window_2_fu_813_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_7[13:2]}};

assign pool_window_30_fu_1103_p4 = {{layer6_out_dout[125:114]}};

assign pool_window_31_fu_893_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_5[13:2]}};

assign pool_window_3_fu_823_p4 = {{layer6_out_dout[13:2]}};

assign pool_window_4_fu_833_p4 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel[13:2]}};

assign pool_window_5_fu_843_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_q0[13:2]}};

assign pool_window_6_fu_853_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_6[13:2]}};

assign pool_window_7_fu_863_p4 = {{layer6_out_dout[29:18]}};

assign pool_window_8_fu_873_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_13[13:2]}};

assign pool_window_9_fu_883_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_q0[13:2]}};

assign pool_window_fu_793_p4 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1[13:2]}};

assign res_pack_1_fu_1508_p3 = {{select_ln65_13_fu_1502_p3}, {2'd0}};

assign res_pack_2_fu_1536_p3 = {{select_ln65_16_fu_1530_p3}, {2'd0}};

assign res_pack_3_fu_1564_p3 = {{select_ln65_19_fu_1558_p3}, {2'd0}};

assign res_pack_fu_1480_p3 = {{select_ln65_10_fu_1474_p3}, {2'd0}};

assign select_ln65_10_fu_1474_p3 = ((xor_ln65_10_fu_1468_p2[0:0] == 1'b1) ? select_ln65_reg_1740 : select_ln65_9_reg_1746);

assign select_ln65_11_fu_1165_p3 = ((xor_ln65_11_fu_1159_p2[0:0] == 1'b1) ? pool_window_4_fu_833_p4 : pool_window_5_fu_843_p4);

assign select_ln65_12_fu_1185_p3 = ((xor_ln65_12_fu_1179_p2[0:0] == 1'b1) ? pool_window_6_fu_853_p4 : pool_window_7_fu_863_p4);

assign select_ln65_13_fu_1502_p3 = ((xor_ln65_13_fu_1496_p2[0:0] == 1'b1) ? select_ln65_11_reg_1752 : select_ln65_12_reg_1758);

assign select_ln65_14_fu_1205_p3 = ((xor_ln65_14_fu_1199_p2[0:0] == 1'b1) ? pool_window_8_fu_873_p4 : pool_window_9_fu_883_p4);

assign select_ln65_15_fu_1225_p3 = ((xor_ln65_15_fu_1219_p2[0:0] == 1'b1) ? pool_window_31_fu_893_p4 : pool_window_10_fu_903_p4);

assign select_ln65_16_fu_1530_p3 = ((xor_ln65_16_fu_1524_p2[0:0] == 1'b1) ? select_ln65_14_reg_1764 : select_ln65_15_reg_1770);

assign select_ln65_17_fu_1245_p3 = ((xor_ln65_17_fu_1239_p2[0:0] == 1'b1) ? pool_window_11_fu_913_p4 : pool_window_12_fu_923_p4);

assign select_ln65_18_fu_1265_p3 = ((xor_ln65_18_fu_1259_p2[0:0] == 1'b1) ? pool_window_13_fu_933_p4 : pool_window_14_fu_943_p4);

assign select_ln65_19_fu_1558_p3 = ((xor_ln65_19_fu_1552_p2[0:0] == 1'b1) ? select_ln65_17_reg_1776 : select_ln65_18_reg_1782);

assign select_ln65_20_fu_1285_p3 = ((xor_ln65_20_fu_1279_p2[0:0] == 1'b1) ? pool_window_15_fu_953_p4 : pool_window_16_fu_963_p4);

assign select_ln65_21_fu_1305_p3 = ((xor_ln65_21_fu_1299_p2[0:0] == 1'b1) ? pool_window_17_fu_973_p4 : pool_window_18_fu_983_p4);

assign select_ln65_22_fu_1586_p3 = ((xor_ln65_22_fu_1580_p2[0:0] == 1'b1) ? select_ln65_20_reg_1788 : select_ln65_21_reg_1794);

assign select_ln65_23_fu_1325_p3 = ((xor_ln65_23_fu_1319_p2[0:0] == 1'b1) ? pool_window_19_fu_993_p4 : pool_window_20_fu_1003_p4);

assign select_ln65_24_fu_1345_p3 = ((xor_ln65_24_fu_1339_p2[0:0] == 1'b1) ? pool_window_21_fu_1013_p4 : pool_window_22_fu_1023_p4);

assign select_ln65_25_fu_1614_p3 = ((xor_ln65_25_fu_1608_p2[0:0] == 1'b1) ? select_ln65_23_reg_1800 : select_ln65_24_reg_1806);

assign select_ln65_26_fu_1365_p3 = ((xor_ln65_26_fu_1359_p2[0:0] == 1'b1) ? pool_window_23_fu_1033_p4 : pool_window_24_fu_1043_p4);

assign select_ln65_27_fu_1385_p3 = ((xor_ln65_27_fu_1379_p2[0:0] == 1'b1) ? pool_window_25_fu_1053_p4 : pool_window_26_fu_1063_p4);

assign select_ln65_28_fu_1642_p3 = ((xor_ln65_28_fu_1636_p2[0:0] == 1'b1) ? select_ln65_26_reg_1812 : select_ln65_27_reg_1818);

assign select_ln65_29_fu_1405_p3 = ((xor_ln65_29_fu_1399_p2[0:0] == 1'b1) ? pool_window_27_fu_1073_p4 : pool_window_28_fu_1083_p4);

assign select_ln65_30_fu_1425_p3 = ((xor_ln65_30_fu_1419_p2[0:0] == 1'b1) ? pool_window_29_fu_1093_p4 : pool_window_30_fu_1103_p4);

assign select_ln65_31_fu_1670_p3 = ((xor_ln65_31_fu_1664_p2[0:0] == 1'b1) ? select_ln65_29_reg_1824 : select_ln65_30_reg_1830);

assign select_ln65_9_fu_1145_p3 = ((xor_ln65_9_fu_1139_p2[0:0] == 1'b1) ? pool_window_2_fu_813_p4 : pool_window_3_fu_823_p4);

assign select_ln65_fu_1125_p3 = ((xor_ln65_fu_1119_p2[0:0] == 1'b1) ? pool_window_fu_793_p4 : pool_window_1_fu_803_p4);

assign select_ln86_fu_1443_p3 = ((icmp_ln86_fu_1437_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign select_ln91_fu_288_p3 = ((icmp_ln55_fu_244_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign sext_ln42_1_fu_1516_p1 = $signed(res_pack_1_fu_1508_p3);

assign sext_ln42_2_fu_1544_p1 = $signed(res_pack_2_fu_1536_p3);

assign sext_ln42_3_fu_1572_p1 = $signed(res_pack_3_fu_1564_p3);

assign sext_ln42_4_fu_1600_p1 = $signed(shl_ln68_4_fu_1592_p3);

assign sext_ln42_5_fu_1628_p1 = $signed(shl_ln68_5_fu_1620_p3);

assign sext_ln42_6_fu_1656_p1 = $signed(shl_ln68_6_fu_1648_p3);

assign sext_ln42_fu_1488_p1 = $signed(res_pack_fu_1480_p3);

assign shl_ln68_4_fu_1592_p3 = {{select_ln65_22_fu_1586_p3}, {2'd0}};

assign shl_ln68_5_fu_1620_p3 = {{select_ln65_25_fu_1614_p3}, {2'd0}};

assign shl_ln68_6_fu_1648_p3 = {{select_ln65_28_fu_1642_p3}, {2'd0}};

assign trunc_ln115_1_fu_357_p1 = layer6_out_dout[13:0];

assign trunc_ln115_fu_353_p1 = layer6_out_dout[15:0];

assign trunc_ln201_fu_609_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_q0[13:0];

assign trunc_ln246_1_fu_525_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_q0[13:0];

assign trunc_ln246_2_fu_539_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_q0[13:0];

assign trunc_ln246_3_fu_553_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_q0[13:0];

assign trunc_ln246_4_fu_567_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_q0[13:0];

assign trunc_ln246_5_fu_581_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_q0[13:0];

assign trunc_ln246_6_fu_595_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_q0[13:0];

assign trunc_ln246_fu_511_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_7_q0[13:0];

assign void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_1_d0 = {{layer6_out_dout[111:96]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_2_d0 = {{layer6_out_dout[95:80]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_3_d0 = {{layer6_out_dout[79:64]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_4_d0 = {{layer6_out_dout[63:48]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_5_d0 = {{layer6_out_dout[47:32]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_6_d0 = {{layer6_out_dout[31:16]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_8u_0_line_buffer_d0 = {{layer6_out_dout[127:112]}};

assign xor_ln65_10_fu_1468_p2 = (icmp_ln65_10_fu_1464_p2 ^ 1'd1);

assign xor_ln65_11_fu_1159_p2 = (icmp_ln65_11_fu_1153_p2 ^ 1'd1);

assign xor_ln65_12_fu_1179_p2 = (icmp_ln65_12_fu_1173_p2 ^ 1'd1);

assign xor_ln65_13_fu_1496_p2 = (icmp_ln65_13_fu_1492_p2 ^ 1'd1);

assign xor_ln65_14_fu_1199_p2 = (icmp_ln65_14_fu_1193_p2 ^ 1'd1);

assign xor_ln65_15_fu_1219_p2 = (icmp_ln65_15_fu_1213_p2 ^ 1'd1);

assign xor_ln65_16_fu_1524_p2 = (icmp_ln65_16_fu_1520_p2 ^ 1'd1);

assign xor_ln65_17_fu_1239_p2 = (icmp_ln65_17_fu_1233_p2 ^ 1'd1);

assign xor_ln65_18_fu_1259_p2 = (icmp_ln65_18_fu_1253_p2 ^ 1'd1);

assign xor_ln65_19_fu_1552_p2 = (icmp_ln65_19_fu_1548_p2 ^ 1'd1);

assign xor_ln65_20_fu_1279_p2 = (icmp_ln65_20_fu_1273_p2 ^ 1'd1);

assign xor_ln65_21_fu_1299_p2 = (icmp_ln65_21_fu_1293_p2 ^ 1'd1);

assign xor_ln65_22_fu_1580_p2 = (icmp_ln65_22_fu_1576_p2 ^ 1'd1);

assign xor_ln65_23_fu_1319_p2 = (icmp_ln65_23_fu_1313_p2 ^ 1'd1);

assign xor_ln65_24_fu_1339_p2 = (icmp_ln65_24_fu_1333_p2 ^ 1'd1);

assign xor_ln65_25_fu_1608_p2 = (icmp_ln65_25_fu_1604_p2 ^ 1'd1);

assign xor_ln65_26_fu_1359_p2 = (icmp_ln65_26_fu_1353_p2 ^ 1'd1);

assign xor_ln65_27_fu_1379_p2 = (icmp_ln65_27_fu_1373_p2 ^ 1'd1);

assign xor_ln65_28_fu_1636_p2 = (icmp_ln65_28_fu_1632_p2 ^ 1'd1);

assign xor_ln65_29_fu_1399_p2 = (icmp_ln65_29_fu_1393_p2 ^ 1'd1);

assign xor_ln65_30_fu_1419_p2 = (icmp_ln65_30_fu_1413_p2 ^ 1'd1);

assign xor_ln65_31_fu_1664_p2 = (icmp_ln65_31_fu_1660_p2 ^ 1'd1);

assign xor_ln65_9_fu_1139_p2 = (icmp_ln65_9_fu_1133_p2 ^ 1'd1);

assign xor_ln65_fu_1119_p2 = (icmp_ln65_fu_1113_p2 ^ 1'd1);

endmodule //myproject_pooling2d_cl_array_ap_fixed_8u_array_ap_fixed_16_6_5_3_0_8u_config7_s
