// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config12_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer11_out_dout,
        layer11_out_empty_n,
        layer11_out_read,
        layer12_out_TDATA,
        layer12_out_TVALID,
        layer12_out_TREADY
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [159:0] layer11_out_dout;
input   layer11_out_empty_n;
output   layer11_out_read;
output  [159:0] layer12_out_TDATA;
output   layer12_out_TVALID;
input   layer12_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer11_out_read;
reg layer12_out_TVALID;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] exp_table_address0;
reg    exp_table_ce0;
wire   [16:0] exp_table_q0;
reg   [9:0] exp_table_address1;
reg    exp_table_ce1;
wire   [16:0] exp_table_q1;
wire   [9:0] exp_table_address2;
reg    exp_table_ce2;
wire   [16:0] exp_table_q2;
wire   [9:0] exp_table_address3;
reg    exp_table_ce3;
wire   [16:0] exp_table_q3;
wire   [9:0] exp_table_address4;
reg    exp_table_ce4;
wire   [16:0] exp_table_q4;
wire   [9:0] exp_table_address5;
reg    exp_table_ce5;
wire   [16:0] exp_table_q5;
wire   [9:0] exp_table_address6;
reg    exp_table_ce6;
wire   [16:0] exp_table_q6;
wire   [9:0] exp_table_address7;
reg    exp_table_ce7;
wire   [16:0] exp_table_q7;
wire   [9:0] invert_table_address0;
reg    invert_table_ce0;
wire   [17:0] invert_table_q0;
reg    layer11_out_blk_n;
reg    layer12_out_TDATA_blk_n;
wire    ap_CS_fsm_state16;
wire  signed [15:0] data_array_fu_323_p1;
reg  signed [15:0] data_array_reg_1976;
reg  signed [15:0] data_array_1_reg_1983;
reg  signed [15:0] data_array_2_reg_1990;
reg  signed [15:0] data_array_7_reg_1997;
reg  signed [15:0] data_array_8_reg_2004;
reg  signed [15:0] data_array_9_reg_2011;
reg  signed [15:0] data_array_3_reg_2018;
reg  signed [15:0] data_array_4_reg_2025;
reg  signed [15:0] data_array_5_reg_2032;
reg  signed [15:0] data_array_6_reg_2039;
wire   [15:0] select_ln65_6_fu_533_p3;
reg   [15:0] select_ln65_6_reg_2046;
wire    ap_CS_fsm_state2;
wire   [15:0] select_ln65_7_fu_551_p3;
reg   [15:0] select_ln65_7_reg_2052;
wire    ap_CS_fsm_state3;
wire   [9:0] select_ln215_17_fu_1273_p3;
reg   [9:0] select_ln215_17_reg_2098;
wire   [9:0] select_ln215_19_fu_1299_p3;
reg   [9:0] select_ln215_19_reg_2103;
reg   [16:0] exp_res_reg_2108;
wire    ap_CS_fsm_state4;
reg   [16:0] exp_res_1_reg_2114;
reg   [16:0] exp_res_2_reg_2120;
reg   [16:0] exp_res_3_reg_2126;
reg   [16:0] exp_res_4_reg_2132;
reg   [16:0] exp_res_5_reg_2138;
reg   [16:0] exp_res_6_reg_2144;
reg   [16:0] exp_res_7_reg_2150;
reg   [16:0] exp_res_8_reg_2166;
wire    ap_CS_fsm_state5;
reg   [16:0] exp_res_9_reg_2171;
reg   [0:0] tmp_42_reg_2176;
wire   [17:0] add_ln50_1_fu_1725_p2;
reg   [17:0] add_ln50_1_reg_2182;
reg   [0:0] tmp_43_reg_2187;
wire   [16:0] select_ln50_2_fu_1759_p3;
reg   [16:0] select_ln50_2_reg_2193;
wire    ap_CS_fsm_state6;
wire  signed [25:0] sext_ln244_fu_1915_p1;
reg  signed [25:0] sext_ln244_reg_2204;
wire    ap_CS_fsm_state7;
wire   [15:0] grp_fu_313_p4;
reg   [15:0] trunc_ln2_reg_2209;
reg   [15:0] trunc_ln244_1_reg_2214;
wire    ap_CS_fsm_state8;
reg   [15:0] trunc_ln244_2_reg_2219;
wire    ap_CS_fsm_state9;
reg   [15:0] trunc_ln244_3_reg_2224;
wire    ap_CS_fsm_state10;
reg   [15:0] trunc_ln244_4_reg_2229;
wire    ap_CS_fsm_state11;
reg   [15:0] trunc_ln244_5_reg_2234;
wire    ap_CS_fsm_state12;
reg   [15:0] trunc_ln244_6_reg_2239;
wire    ap_CS_fsm_state13;
reg   [15:0] trunc_ln244_7_reg_2244;
wire    ap_CS_fsm_state14;
reg   [15:0] trunc_ln244_8_reg_2249;
wire    ap_CS_fsm_state15;
wire   [63:0] zext_ln225_fu_1033_p1;
wire   [63:0] zext_ln225_1_fu_1064_p1;
wire   [63:0] zext_ln225_2_fu_1095_p1;
wire   [63:0] zext_ln225_3_fu_1126_p1;
wire   [63:0] zext_ln225_4_fu_1157_p1;
wire   [63:0] zext_ln225_5_fu_1188_p1;
wire   [63:0] zext_ln225_6_fu_1219_p1;
wire   [63:0] zext_ln225_7_fu_1250_p1;
wire   [63:0] zext_ln225_8_fu_1307_p1;
wire   [63:0] zext_ln225_9_fu_1311_p1;
wire   [63:0] zext_ln235_fu_1910_p1;
reg    ap_block_state1;
reg  signed [17:0] grp_fu_275_p0;
reg   [16:0] grp_fu_275_p1;
wire   [25:0] zext_ln244_fu_1920_p1;
wire   [25:0] zext_ln244_1_fu_1924_p1;
wire   [25:0] zext_ln244_2_fu_1928_p1;
wire   [25:0] zext_ln244_3_fu_1932_p1;
wire   [25:0] zext_ln244_4_fu_1936_p1;
wire   [25:0] zext_ln244_5_fu_1940_p1;
wire   [25:0] zext_ln244_6_fu_1944_p1;
wire   [25:0] zext_ln244_7_fu_1948_p1;
wire   [25:0] zext_ln244_8_fu_1952_p1;
wire   [25:0] zext_ln244_9_fu_1956_p1;
wire   [25:0] grp_fu_275_p2;
wire   [0:0] icmp_ln65_fu_417_p2;
wire   [0:0] xor_ln65_fu_421_p2;
wire   [0:0] icmp_ln65_1_fu_433_p2;
wire   [0:0] xor_ln65_1_fu_437_p2;
wire   [15:0] select_ln65_fu_427_p3;
wire   [15:0] select_ln65_1_fu_443_p3;
wire   [0:0] icmp_ln65_2_fu_449_p2;
wire   [0:0] xor_ln65_2_fu_455_p2;
wire   [0:0] icmp_ln65_3_fu_469_p2;
wire   [0:0] xor_ln65_3_fu_473_p2;
wire   [0:0] icmp_ln65_4_fu_485_p2;
wire   [0:0] xor_ln65_4_fu_489_p2;
wire   [15:0] select_ln65_3_fu_479_p3;
wire   [15:0] select_ln65_4_fu_495_p3;
wire   [0:0] icmp_ln65_5_fu_501_p2;
wire   [0:0] xor_ln65_5_fu_507_p2;
wire   [15:0] select_ln65_2_fu_461_p3;
wire   [15:0] select_ln65_5_fu_513_p3;
wire   [0:0] icmp_ln65_6_fu_521_p2;
wire   [0:0] xor_ln65_6_fu_527_p2;
wire   [0:0] icmp_ln65_7_fu_541_p2;
wire   [0:0] xor_ln65_7_fu_545_p2;
wire   [0:0] icmp_ln65_8_fu_557_p2;
wire   [0:0] xor_ln65_8_fu_561_p2;
wire   [15:0] x_max_fu_567_p3;
wire  signed [16:0] sext_ln215_fu_573_p1;
wire  signed [16:0] sext_ln215_1_fu_576_p1;
wire   [16:0] sub_ln215_fu_580_p2;
wire   [0:0] tmp_10_fu_586_p3;
wire   [0:0] tmp_11_fu_594_p3;
wire   [0:0] xor_ln215_fu_602_p2;
wire  signed [16:0] sext_ln215_2_fu_620_p1;
wire   [16:0] sub_ln215_1_fu_623_p2;
wire   [0:0] tmp_12_fu_629_p3;
wire   [0:0] tmp_13_fu_637_p3;
wire   [0:0] xor_ln215_2_fu_645_p2;
wire  signed [16:0] sext_ln215_3_fu_663_p1;
wire   [16:0] sub_ln215_2_fu_666_p2;
wire   [0:0] tmp_14_fu_672_p3;
wire   [0:0] tmp_15_fu_680_p3;
wire   [0:0] xor_ln215_4_fu_688_p2;
wire  signed [16:0] sext_ln215_4_fu_706_p1;
wire   [16:0] sub_ln215_3_fu_709_p2;
wire   [0:0] tmp_16_fu_715_p3;
wire   [0:0] tmp_17_fu_723_p3;
wire   [0:0] xor_ln215_6_fu_731_p2;
wire  signed [16:0] sext_ln215_5_fu_749_p1;
wire   [16:0] sub_ln215_4_fu_752_p2;
wire   [0:0] tmp_18_fu_758_p3;
wire   [0:0] tmp_19_fu_766_p3;
wire   [0:0] xor_ln215_8_fu_774_p2;
wire  signed [16:0] sext_ln215_6_fu_792_p1;
wire   [16:0] sub_ln215_5_fu_795_p2;
wire   [0:0] tmp_20_fu_801_p3;
wire   [0:0] tmp_21_fu_809_p3;
wire   [0:0] xor_ln215_10_fu_817_p2;
wire  signed [16:0] sext_ln215_7_fu_835_p1;
wire   [16:0] sub_ln215_6_fu_838_p2;
wire   [0:0] tmp_22_fu_844_p3;
wire   [0:0] tmp_23_fu_852_p3;
wire   [0:0] xor_ln215_12_fu_860_p2;
wire  signed [16:0] sext_ln215_8_fu_878_p1;
wire   [16:0] sub_ln215_7_fu_881_p2;
wire   [0:0] tmp_24_fu_887_p3;
wire   [0:0] tmp_25_fu_895_p3;
wire   [0:0] xor_ln215_14_fu_903_p2;
wire  signed [16:0] sext_ln215_9_fu_921_p1;
wire   [16:0] sub_ln215_8_fu_924_p2;
wire   [0:0] tmp_26_fu_930_p3;
wire   [0:0] tmp_27_fu_938_p3;
wire   [0:0] xor_ln215_16_fu_946_p2;
wire  signed [16:0] sext_ln215_10_fu_964_p1;
wire   [16:0] sub_ln215_9_fu_967_p2;
wire   [0:0] tmp_28_fu_973_p3;
wire   [0:0] tmp_29_fu_981_p3;
wire   [0:0] xor_ln215_18_fu_989_p2;
wire   [0:0] and_ln215_fu_608_p2;
wire   [0:0] xor_ln215_1_fu_614_p2;
wire   [9:0] select_ln215_fu_1007_p3;
wire   [9:0] tmp_fu_1015_p4;
wire   [9:0] select_ln215_1_fu_1025_p3;
wire   [0:0] and_ln215_1_fu_651_p2;
wire   [0:0] xor_ln215_3_fu_657_p2;
wire   [9:0] select_ln215_2_fu_1038_p3;
wire   [9:0] tmp_1_fu_1046_p4;
wire   [9:0] select_ln215_3_fu_1056_p3;
wire   [0:0] and_ln215_2_fu_694_p2;
wire   [0:0] xor_ln215_5_fu_700_p2;
wire   [9:0] select_ln215_4_fu_1069_p3;
wire   [9:0] tmp_2_fu_1077_p4;
wire   [9:0] select_ln215_5_fu_1087_p3;
wire   [0:0] and_ln215_3_fu_737_p2;
wire   [0:0] xor_ln215_7_fu_743_p2;
wire   [9:0] select_ln215_6_fu_1100_p3;
wire   [9:0] tmp_3_fu_1108_p4;
wire   [9:0] select_ln215_7_fu_1118_p3;
wire   [0:0] and_ln215_4_fu_780_p2;
wire   [0:0] xor_ln215_9_fu_786_p2;
wire   [9:0] select_ln215_8_fu_1131_p3;
wire   [9:0] tmp_4_fu_1139_p4;
wire   [9:0] select_ln215_9_fu_1149_p3;
wire   [0:0] and_ln215_5_fu_823_p2;
wire   [0:0] xor_ln215_11_fu_829_p2;
wire   [9:0] select_ln215_10_fu_1162_p3;
wire   [9:0] tmp_5_fu_1170_p4;
wire   [9:0] select_ln215_11_fu_1180_p3;
wire   [0:0] and_ln215_6_fu_866_p2;
wire   [0:0] xor_ln215_13_fu_872_p2;
wire   [9:0] select_ln215_12_fu_1193_p3;
wire   [9:0] tmp_6_fu_1201_p4;
wire   [9:0] select_ln215_13_fu_1211_p3;
wire   [0:0] and_ln215_7_fu_909_p2;
wire   [0:0] xor_ln215_15_fu_915_p2;
wire   [9:0] select_ln215_14_fu_1224_p3;
wire   [9:0] tmp_7_fu_1232_p4;
wire   [9:0] select_ln215_15_fu_1242_p3;
wire   [0:0] and_ln215_8_fu_952_p2;
wire   [0:0] xor_ln215_17_fu_958_p2;
wire   [9:0] select_ln215_16_fu_1255_p3;
wire   [9:0] tmp_8_fu_1263_p4;
wire   [0:0] and_ln215_9_fu_995_p2;
wire   [0:0] xor_ln215_19_fu_1001_p2;
wire   [9:0] select_ln215_18_fu_1281_p3;
wire   [9:0] tmp_s_fu_1289_p4;
wire   [17:0] zext_ln50_1_fu_1326_p1;
wire   [17:0] zext_ln50_fu_1323_p1;
wire   [17:0] add_ln50_5_fu_1329_p2;
wire   [0:0] tmp_31_fu_1343_p3;
wire   [0:0] tmp_30_fu_1335_p3;
wire   [17:0] select_ln50_3_fu_1351_p3;
wire   [17:0] zext_ln50_3_fu_1370_p1;
wire   [17:0] zext_ln50_2_fu_1367_p1;
wire   [17:0] add_ln50_6_fu_1373_p2;
wire   [0:0] tmp_33_fu_1387_p3;
wire   [0:0] tmp_32_fu_1379_p3;
wire   [17:0] select_ln50_5_fu_1395_p3;
wire  signed [17:0] select_ln50_4_fu_1359_p3;
wire  signed [17:0] select_ln50_6_fu_1403_p3;
wire  signed [18:0] sext_ln50_4_fu_1415_p1;
wire  signed [18:0] sext_ln50_3_fu_1411_p1;
wire   [18:0] add_ln50_7_fu_1419_p2;
wire   [17:0] add_ln50_8_fu_1433_p2;
wire   [0:0] tmp_34_fu_1425_p3;
wire   [0:0] tmp_35_fu_1439_p3;
wire   [0:0] xor_ln50_6_fu_1447_p2;
wire   [0:0] xor_ln50_7_fu_1459_p2;
wire   [0:0] xor_ln50_8_fu_1471_p2;
wire   [0:0] and_ln50_3_fu_1453_p2;
wire   [0:0] xor_ln50_9_fu_1477_p2;
wire   [0:0] and_ln50_4_fu_1465_p2;
wire   [0:0] or_ln50_1_fu_1483_p2;
wire   [17:0] select_ln50_7_fu_1489_p3;
wire   [17:0] select_ln50_8_fu_1497_p3;
wire   [17:0] zext_ln50_5_fu_1516_p1;
wire   [17:0] zext_ln50_4_fu_1513_p1;
wire   [17:0] add_ln50_9_fu_1519_p2;
wire   [0:0] tmp_37_fu_1533_p3;
wire   [0:0] tmp_36_fu_1525_p3;
wire   [17:0] select_ln50_10_fu_1541_p3;
wire   [17:0] zext_ln50_7_fu_1560_p1;
wire   [17:0] zext_ln50_6_fu_1557_p1;
wire   [17:0] add_ln50_10_fu_1563_p2;
wire   [0:0] tmp_39_fu_1577_p3;
wire   [0:0] tmp_38_fu_1569_p3;
wire   [17:0] select_ln50_12_fu_1585_p3;
wire  signed [17:0] select_ln50_11_fu_1549_p3;
wire  signed [17:0] select_ln50_13_fu_1593_p3;
wire  signed [18:0] sext_ln50_6_fu_1605_p1;
wire  signed [18:0] sext_ln50_5_fu_1601_p1;
wire   [18:0] add_ln50_11_fu_1609_p2;
wire   [17:0] add_ln50_12_fu_1623_p2;
wire   [0:0] tmp_40_fu_1615_p3;
wire   [0:0] tmp_41_fu_1629_p3;
wire   [0:0] xor_ln50_10_fu_1637_p2;
wire   [0:0] xor_ln50_11_fu_1649_p2;
wire   [0:0] xor_ln50_12_fu_1661_p2;
wire   [0:0] and_ln50_5_fu_1643_p2;
wire   [0:0] xor_ln50_13_fu_1667_p2;
wire   [0:0] and_ln50_6_fu_1655_p2;
wire   [0:0] or_ln50_2_fu_1673_p2;
wire   [17:0] select_ln50_14_fu_1679_p3;
wire   [17:0] select_ln50_15_fu_1687_p3;
wire  signed [17:0] select_ln50_9_fu_1505_p3;
wire  signed [17:0] select_ln50_16_fu_1695_p3;
wire  signed [18:0] sext_ln50_fu_1703_p1;
wire  signed [18:0] sext_ln50_1_fu_1707_p1;
wire   [18:0] add_ln50_fu_1711_p2;
wire   [17:0] zext_ln219_fu_1319_p1;
wire   [17:0] zext_ln215_fu_1315_p1;
wire   [17:0] add_ln50_2_fu_1739_p2;
wire   [0:0] tmp_44_fu_1751_p3;
wire   [16:0] add_ln50_13_fu_1745_p2;
wire   [0:0] xor_ln50_fu_1767_p2;
wire   [0:0] and_ln50_fu_1772_p2;
wire   [0:0] xor_ln50_1_fu_1777_p2;
wire   [17:0] select_ln50_fu_1781_p3;
wire  signed [17:0] select_ln50_1_fu_1789_p3;
wire  signed [18:0] sext_ln50_2_fu_1799_p1;
wire   [18:0] zext_ln50_9_fu_1803_p1;
wire   [18:0] add_ln50_3_fu_1806_p2;
wire   [17:0] zext_ln50_8_fu_1796_p1;
wire   [17:0] add_ln50_4_fu_1820_p2;
wire   [0:0] tmp_45_fu_1812_p3;
wire   [0:0] tmp_46_fu_1826_p3;
wire   [0:0] xor_ln50_2_fu_1834_p2;
wire   [0:0] xor_ln50_3_fu_1846_p2;
wire   [0:0] xor_ln50_4_fu_1858_p2;
wire   [0:0] and_ln50_1_fu_1840_p2;
wire   [0:0] xor_ln50_5_fu_1864_p2;
wire   [9:0] tmp_9_fu_1876_p4;
wire   [0:0] and_ln50_2_fu_1852_p2;
wire   [0:0] or_ln50_fu_1870_p2;
wire   [9:0] select_ln50_17_fu_1886_p3;
wire   [9:0] select_ln50_18_fu_1894_p3;
wire   [9:0] select_ln50_19_fu_1902_p3;
wire    ap_CS_fsm_state17;
reg   [16:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
end

myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config12_s_exp_tabAem #(
    .DataWidth( 17 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0),
    .ce0(exp_table_ce0),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1),
    .q1(exp_table_q1),
    .address2(exp_table_address2),
    .ce2(exp_table_ce2),
    .q2(exp_table_q2),
    .address3(exp_table_address3),
    .ce3(exp_table_ce3),
    .q3(exp_table_q3),
    .address4(exp_table_address4),
    .ce4(exp_table_ce4),
    .q4(exp_table_q4),
    .address5(exp_table_address5),
    .ce5(exp_table_ce5),
    .q5(exp_table_q5),
    .address6(exp_table_address6),
    .ce6(exp_table_ce6),
    .q6(exp_table_q6),
    .address7(exp_table_address7),
    .ce7(exp_table_ce7),
    .q7(exp_table_q7)
);

myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config12_s_invert_Bew #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0),
    .q0(invert_table_q0)
);

myproject_mul_18s_17ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 26 ))
mul_18s_17ns_26_1_1_U272(
    .din0(grp_fu_275_p0),
    .din1(grp_fu_275_p1),
    .dout(grp_fu_275_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln50_1_reg_2182 <= add_ln50_1_fu_1725_p2;
        exp_res_8_reg_2166 <= exp_table_q1;
        exp_res_9_reg_2171 <= exp_table_q0;
        select_ln50_2_reg_2193 <= select_ln50_2_fu_1759_p3;
        tmp_42_reg_2176 <= add_ln50_fu_1711_p2[32'd18];
        tmp_43_reg_2187 <= add_ln50_1_fu_1725_p2[32'd17];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_array_1_reg_1983 <= {{layer11_out_dout[31:16]}};
        data_array_2_reg_1990 <= {{layer11_out_dout[47:32]}};
        data_array_3_reg_2018 <= {{layer11_out_dout[63:48]}};
        data_array_4_reg_2025 <= {{layer11_out_dout[79:64]}};
        data_array_5_reg_2032 <= {{layer11_out_dout[95:80]}};
        data_array_6_reg_2039 <= {{layer11_out_dout[111:96]}};
        data_array_7_reg_1997 <= {{layer11_out_dout[127:112]}};
        data_array_8_reg_2004 <= {{layer11_out_dout[143:128]}};
        data_array_9_reg_2011 <= {{layer11_out_dout[159:144]}};
        data_array_reg_1976 <= data_array_fu_323_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        exp_res_1_reg_2114 <= exp_table_q6;
        exp_res_2_reg_2120 <= exp_table_q5;
        exp_res_3_reg_2126 <= exp_table_q4;
        exp_res_4_reg_2132 <= exp_table_q3;
        exp_res_5_reg_2138 <= exp_table_q2;
        exp_res_6_reg_2144 <= exp_table_q1;
        exp_res_7_reg_2150 <= exp_table_q0;
        exp_res_reg_2108 <= exp_table_q7;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        select_ln215_17_reg_2098 <= select_ln215_17_fu_1273_p3;
        select_ln215_19_reg_2103 <= select_ln215_19_fu_1299_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln65_6_reg_2046 <= select_ln65_6_fu_533_p3;
        select_ln65_7_reg_2052 <= select_ln65_7_fu_551_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        sext_ln244_reg_2204 <= sext_ln244_fu_1915_p1;
        trunc_ln2_reg_2209 <= {{grp_fu_275_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        trunc_ln244_1_reg_2214 <= {{grp_fu_275_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        trunc_ln244_2_reg_2219 <= {{grp_fu_275_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        trunc_ln244_3_reg_2224 <= {{grp_fu_275_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        trunc_ln244_4_reg_2229 <= {{grp_fu_275_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        trunc_ln244_5_reg_2234 <= {{grp_fu_275_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        trunc_ln244_6_reg_2239 <= {{grp_fu_275_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        trunc_ln244_7_reg_2244 <= {{grp_fu_275_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        trunc_ln244_8_reg_2249 <= {{grp_fu_275_p2[25:10]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((layer12_out_TREADY == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if (((layer11_out_empty_n == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        exp_table_address0 = zext_ln225_9_fu_1311_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_address0 = zext_ln225_7_fu_1250_p1;
    end else begin
        exp_table_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        exp_table_address1 = zext_ln225_8_fu_1307_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_address1 = zext_ln225_6_fu_1219_p1;
    end else begin
        exp_table_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        exp_table_ce0 = 1'b1;
    end else begin
        exp_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        exp_table_ce1 = 1'b1;
    end else begin
        exp_table_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce2 = 1'b1;
    end else begin
        exp_table_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce3 = 1'b1;
    end else begin
        exp_table_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce4 = 1'b1;
    end else begin
        exp_table_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce5 = 1'b1;
    end else begin
        exp_table_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce6 = 1'b1;
    end else begin
        exp_table_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce7 = 1'b1;
    end else begin
        exp_table_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_275_p0 = sext_ln244_reg_2204;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_275_p0 = sext_ln244_fu_1915_p1;
    end else begin
        grp_fu_275_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_275_p1 = zext_ln244_9_fu_1956_p1;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_275_p1 = zext_ln244_8_fu_1952_p1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_275_p1 = zext_ln244_7_fu_1948_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_275_p1 = zext_ln244_6_fu_1944_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_275_p1 = zext_ln244_5_fu_1940_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_275_p1 = zext_ln244_4_fu_1936_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_275_p1 = zext_ln244_3_fu_1932_p1;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_275_p1 = zext_ln244_2_fu_1928_p1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_275_p1 = zext_ln244_1_fu_1924_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_275_p1 = zext_ln244_fu_1920_p1;
    end else begin
        grp_fu_275_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        invert_table_ce0 = 1'b1;
    end else begin
        invert_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_out_blk_n = layer11_out_empty_n;
    end else begin
        layer11_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer11_out_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_out_read = 1'b1;
    end else begin
        layer11_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        layer12_out_TDATA_blk_n = layer12_out_TREADY;
    end else begin
        layer12_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer12_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        layer12_out_TVALID = 1'b1;
    end else begin
        layer12_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((layer11_out_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((layer12_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln50_10_fu_1563_p2 = (zext_ln50_7_fu_1560_p1 + zext_ln50_6_fu_1557_p1);

assign add_ln50_11_fu_1609_p2 = ($signed(sext_ln50_6_fu_1605_p1) + $signed(sext_ln50_5_fu_1601_p1));

assign add_ln50_12_fu_1623_p2 = ($signed(select_ln50_13_fu_1593_p3) + $signed(select_ln50_11_fu_1549_p3));

assign add_ln50_13_fu_1745_p2 = (exp_table_q0 + exp_table_q1);

assign add_ln50_1_fu_1725_p2 = ($signed(select_ln50_9_fu_1505_p3) + $signed(select_ln50_16_fu_1695_p3));

assign add_ln50_2_fu_1739_p2 = (zext_ln219_fu_1319_p1 + zext_ln215_fu_1315_p1);

assign add_ln50_3_fu_1806_p2 = ($signed(sext_ln50_2_fu_1799_p1) + $signed(zext_ln50_9_fu_1803_p1));

assign add_ln50_4_fu_1820_p2 = ($signed(select_ln50_1_fu_1789_p3) + $signed(zext_ln50_8_fu_1796_p1));

assign add_ln50_5_fu_1329_p2 = (zext_ln50_1_fu_1326_p1 + zext_ln50_fu_1323_p1);

assign add_ln50_6_fu_1373_p2 = (zext_ln50_3_fu_1370_p1 + zext_ln50_2_fu_1367_p1);

assign add_ln50_7_fu_1419_p2 = ($signed(sext_ln50_4_fu_1415_p1) + $signed(sext_ln50_3_fu_1411_p1));

assign add_ln50_8_fu_1433_p2 = ($signed(select_ln50_6_fu_1403_p3) + $signed(select_ln50_4_fu_1359_p3));

assign add_ln50_9_fu_1519_p2 = (zext_ln50_5_fu_1516_p1 + zext_ln50_4_fu_1513_p1);

assign add_ln50_fu_1711_p2 = ($signed(sext_ln50_fu_1703_p1) + $signed(sext_ln50_1_fu_1707_p1));

assign and_ln215_1_fu_651_p2 = (xor_ln215_2_fu_645_p2 & tmp_13_fu_637_p3);

assign and_ln215_2_fu_694_p2 = (xor_ln215_4_fu_688_p2 & tmp_15_fu_680_p3);

assign and_ln215_3_fu_737_p2 = (xor_ln215_6_fu_731_p2 & tmp_17_fu_723_p3);

assign and_ln215_4_fu_780_p2 = (xor_ln215_8_fu_774_p2 & tmp_19_fu_766_p3);

assign and_ln215_5_fu_823_p2 = (xor_ln215_10_fu_817_p2 & tmp_21_fu_809_p3);

assign and_ln215_6_fu_866_p2 = (xor_ln215_12_fu_860_p2 & tmp_23_fu_852_p3);

assign and_ln215_7_fu_909_p2 = (xor_ln215_14_fu_903_p2 & tmp_25_fu_895_p3);

assign and_ln215_8_fu_952_p2 = (xor_ln215_16_fu_946_p2 & tmp_27_fu_938_p3);

assign and_ln215_9_fu_995_p2 = (xor_ln215_18_fu_989_p2 & tmp_29_fu_981_p3);

assign and_ln215_fu_608_p2 = (xor_ln215_fu_602_p2 & tmp_11_fu_594_p3);

assign and_ln50_1_fu_1840_p2 = (xor_ln50_2_fu_1834_p2 & tmp_46_fu_1826_p3);

assign and_ln50_2_fu_1852_p2 = (xor_ln50_3_fu_1846_p2 & tmp_45_fu_1812_p3);

assign and_ln50_3_fu_1453_p2 = (xor_ln50_6_fu_1447_p2 & tmp_35_fu_1439_p3);

assign and_ln50_4_fu_1465_p2 = (xor_ln50_7_fu_1459_p2 & tmp_34_fu_1425_p3);

assign and_ln50_5_fu_1643_p2 = (xor_ln50_10_fu_1637_p2 & tmp_41_fu_1629_p3);

assign and_ln50_6_fu_1655_p2 = (xor_ln50_11_fu_1649_p2 & tmp_40_fu_1615_p3);

assign and_ln50_fu_1772_p2 = (xor_ln50_fu_1767_p2 & tmp_43_reg_2187);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((layer11_out_empty_n == 1'b0) | (ap_start == 1'b0));
end

assign data_array_fu_323_p1 = layer11_out_dout[15:0];

assign exp_table_address2 = zext_ln225_5_fu_1188_p1;

assign exp_table_address3 = zext_ln225_4_fu_1157_p1;

assign exp_table_address4 = zext_ln225_3_fu_1126_p1;

assign exp_table_address5 = zext_ln225_2_fu_1095_p1;

assign exp_table_address6 = zext_ln225_1_fu_1064_p1;

assign exp_table_address7 = zext_ln225_fu_1033_p1;

assign grp_fu_313_p4 = {{grp_fu_275_p2[25:10]}};

assign icmp_ln65_1_fu_433_p2 = (($signed(data_array_2_reg_1990) < $signed(data_array_3_reg_2018)) ? 1'b1 : 1'b0);

assign icmp_ln65_2_fu_449_p2 = (($signed(select_ln65_fu_427_p3) < $signed(select_ln65_1_fu_443_p3)) ? 1'b1 : 1'b0);

assign icmp_ln65_3_fu_469_p2 = (($signed(data_array_4_reg_2025) < $signed(data_array_5_reg_2032)) ? 1'b1 : 1'b0);

assign icmp_ln65_4_fu_485_p2 = (($signed(data_array_6_reg_2039) < $signed(data_array_7_reg_1997)) ? 1'b1 : 1'b0);

assign icmp_ln65_5_fu_501_p2 = (($signed(select_ln65_3_fu_479_p3) < $signed(select_ln65_4_fu_495_p3)) ? 1'b1 : 1'b0);

assign icmp_ln65_6_fu_521_p2 = (($signed(select_ln65_2_fu_461_p3) < $signed(select_ln65_5_fu_513_p3)) ? 1'b1 : 1'b0);

assign icmp_ln65_7_fu_541_p2 = (($signed(data_array_8_reg_2004) < $signed(data_array_9_reg_2011)) ? 1'b1 : 1'b0);

assign icmp_ln65_8_fu_557_p2 = (($signed(select_ln65_6_reg_2046) < $signed(select_ln65_7_reg_2052)) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_417_p2 = (($signed(data_array_reg_1976) < $signed(data_array_1_reg_1983)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln235_fu_1910_p1;

assign layer12_out_TDATA = {{{{{{{{{{grp_fu_313_p4}, {trunc_ln244_8_reg_2249}}, {trunc_ln244_7_reg_2244}}, {trunc_ln244_6_reg_2239}}, {trunc_ln244_5_reg_2234}}, {trunc_ln244_4_reg_2229}}, {trunc_ln244_3_reg_2224}}, {trunc_ln244_2_reg_2219}}, {trunc_ln244_1_reg_2214}}, {trunc_ln2_reg_2209}};

assign or_ln50_1_fu_1483_p2 = (xor_ln50_9_fu_1477_p2 | and_ln50_3_fu_1453_p2);

assign or_ln50_2_fu_1673_p2 = (xor_ln50_13_fu_1667_p2 | and_ln50_5_fu_1643_p2);

assign or_ln50_fu_1870_p2 = (xor_ln50_5_fu_1864_p2 | and_ln50_1_fu_1840_p2);

assign select_ln215_10_fu_1162_p3 = ((and_ln215_5_fu_823_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_11_fu_1180_p3 = ((xor_ln215_11_fu_829_p2[0:0] == 1'b1) ? select_ln215_10_fu_1162_p3 : tmp_5_fu_1170_p4);

assign select_ln215_12_fu_1193_p3 = ((and_ln215_6_fu_866_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_13_fu_1211_p3 = ((xor_ln215_13_fu_872_p2[0:0] == 1'b1) ? select_ln215_12_fu_1193_p3 : tmp_6_fu_1201_p4);

assign select_ln215_14_fu_1224_p3 = ((and_ln215_7_fu_909_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_15_fu_1242_p3 = ((xor_ln215_15_fu_915_p2[0:0] == 1'b1) ? select_ln215_14_fu_1224_p3 : tmp_7_fu_1232_p4);

assign select_ln215_16_fu_1255_p3 = ((and_ln215_8_fu_952_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_17_fu_1273_p3 = ((xor_ln215_17_fu_958_p2[0:0] == 1'b1) ? select_ln215_16_fu_1255_p3 : tmp_8_fu_1263_p4);

assign select_ln215_18_fu_1281_p3 = ((and_ln215_9_fu_995_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_19_fu_1299_p3 = ((xor_ln215_19_fu_1001_p2[0:0] == 1'b1) ? select_ln215_18_fu_1281_p3 : tmp_s_fu_1289_p4);

assign select_ln215_1_fu_1025_p3 = ((xor_ln215_1_fu_614_p2[0:0] == 1'b1) ? select_ln215_fu_1007_p3 : tmp_fu_1015_p4);

assign select_ln215_2_fu_1038_p3 = ((and_ln215_1_fu_651_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_3_fu_1056_p3 = ((xor_ln215_3_fu_657_p2[0:0] == 1'b1) ? select_ln215_2_fu_1038_p3 : tmp_1_fu_1046_p4);

assign select_ln215_4_fu_1069_p3 = ((and_ln215_2_fu_694_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_5_fu_1087_p3 = ((xor_ln215_5_fu_700_p2[0:0] == 1'b1) ? select_ln215_4_fu_1069_p3 : tmp_2_fu_1077_p4);

assign select_ln215_6_fu_1100_p3 = ((and_ln215_3_fu_737_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_7_fu_1118_p3 = ((xor_ln215_7_fu_743_p2[0:0] == 1'b1) ? select_ln215_6_fu_1100_p3 : tmp_3_fu_1108_p4);

assign select_ln215_8_fu_1131_p3 = ((and_ln215_4_fu_780_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln215_9_fu_1149_p3 = ((xor_ln215_9_fu_786_p2[0:0] == 1'b1) ? select_ln215_8_fu_1131_p3 : tmp_4_fu_1139_p4);

assign select_ln215_fu_1007_p3 = ((and_ln215_fu_608_p2[0:0] == 1'b1) ? 10'd511 : 10'd512);

assign select_ln50_10_fu_1541_p3 = ((tmp_37_fu_1533_p3[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln50_11_fu_1549_p3 = ((tmp_36_fu_1525_p3[0:0] == 1'b1) ? select_ln50_10_fu_1541_p3 : add_ln50_9_fu_1519_p2);

assign select_ln50_12_fu_1585_p3 = ((tmp_39_fu_1577_p3[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln50_13_fu_1593_p3 = ((tmp_38_fu_1569_p3[0:0] == 1'b1) ? select_ln50_12_fu_1585_p3 : add_ln50_10_fu_1563_p2);

assign select_ln50_14_fu_1679_p3 = ((xor_ln50_12_fu_1661_p2[0:0] == 1'b1) ? 18'd131071 : add_ln50_12_fu_1623_p2);

assign select_ln50_15_fu_1687_p3 = ((and_ln50_6_fu_1655_p2[0:0] == 1'b1) ? 18'd131072 : add_ln50_12_fu_1623_p2);

assign select_ln50_16_fu_1695_p3 = ((or_ln50_2_fu_1673_p2[0:0] == 1'b1) ? select_ln50_14_fu_1679_p3 : select_ln50_15_fu_1687_p3);

assign select_ln50_17_fu_1886_p3 = ((xor_ln50_4_fu_1858_p2[0:0] == 1'b1) ? 10'd511 : tmp_9_fu_1876_p4);

assign select_ln50_18_fu_1894_p3 = ((and_ln50_2_fu_1852_p2[0:0] == 1'b1) ? 10'd512 : tmp_9_fu_1876_p4);

assign select_ln50_19_fu_1902_p3 = ((or_ln50_fu_1870_p2[0:0] == 1'b1) ? select_ln50_17_fu_1886_p3 : select_ln50_18_fu_1894_p3);

assign select_ln50_1_fu_1789_p3 = ((xor_ln50_1_fu_1777_p2[0:0] == 1'b1) ? select_ln50_fu_1781_p3 : add_ln50_1_reg_2182);

assign select_ln50_2_fu_1759_p3 = ((tmp_44_fu_1751_p3[0:0] == 1'b1) ? 17'd131071 : add_ln50_13_fu_1745_p2);

assign select_ln50_3_fu_1351_p3 = ((tmp_31_fu_1343_p3[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln50_4_fu_1359_p3 = ((tmp_30_fu_1335_p3[0:0] == 1'b1) ? select_ln50_3_fu_1351_p3 : add_ln50_5_fu_1329_p2);

assign select_ln50_5_fu_1395_p3 = ((tmp_33_fu_1387_p3[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln50_6_fu_1403_p3 = ((tmp_32_fu_1379_p3[0:0] == 1'b1) ? select_ln50_5_fu_1395_p3 : add_ln50_6_fu_1373_p2);

assign select_ln50_7_fu_1489_p3 = ((xor_ln50_8_fu_1471_p2[0:0] == 1'b1) ? 18'd131071 : add_ln50_8_fu_1433_p2);

assign select_ln50_8_fu_1497_p3 = ((and_ln50_4_fu_1465_p2[0:0] == 1'b1) ? 18'd131072 : add_ln50_8_fu_1433_p2);

assign select_ln50_9_fu_1505_p3 = ((or_ln50_1_fu_1483_p2[0:0] == 1'b1) ? select_ln50_7_fu_1489_p3 : select_ln50_8_fu_1497_p3);

assign select_ln50_fu_1781_p3 = ((and_ln50_fu_1772_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln65_1_fu_443_p3 = ((xor_ln65_1_fu_437_p2[0:0] == 1'b1) ? data_array_2_reg_1990 : data_array_3_reg_2018);

assign select_ln65_2_fu_461_p3 = ((xor_ln65_2_fu_455_p2[0:0] == 1'b1) ? select_ln65_fu_427_p3 : select_ln65_1_fu_443_p3);

assign select_ln65_3_fu_479_p3 = ((xor_ln65_3_fu_473_p2[0:0] == 1'b1) ? data_array_4_reg_2025 : data_array_5_reg_2032);

assign select_ln65_4_fu_495_p3 = ((xor_ln65_4_fu_489_p2[0:0] == 1'b1) ? data_array_6_reg_2039 : data_array_7_reg_1997);

assign select_ln65_5_fu_513_p3 = ((xor_ln65_5_fu_507_p2[0:0] == 1'b1) ? select_ln65_3_fu_479_p3 : select_ln65_4_fu_495_p3);

assign select_ln65_6_fu_533_p3 = ((xor_ln65_6_fu_527_p2[0:0] == 1'b1) ? select_ln65_2_fu_461_p3 : select_ln65_5_fu_513_p3);

assign select_ln65_7_fu_551_p3 = ((xor_ln65_7_fu_545_p2[0:0] == 1'b1) ? data_array_8_reg_2004 : data_array_9_reg_2011);

assign select_ln65_fu_427_p3 = ((xor_ln65_fu_421_p2[0:0] == 1'b1) ? data_array_reg_1976 : data_array_1_reg_1983);

assign sext_ln215_10_fu_964_p1 = data_array_9_reg_2011;

assign sext_ln215_1_fu_576_p1 = $signed(x_max_fu_567_p3);

assign sext_ln215_2_fu_620_p1 = data_array_1_reg_1983;

assign sext_ln215_3_fu_663_p1 = data_array_2_reg_1990;

assign sext_ln215_4_fu_706_p1 = data_array_3_reg_2018;

assign sext_ln215_5_fu_749_p1 = data_array_4_reg_2025;

assign sext_ln215_6_fu_792_p1 = data_array_5_reg_2032;

assign sext_ln215_7_fu_835_p1 = data_array_6_reg_2039;

assign sext_ln215_8_fu_878_p1 = data_array_7_reg_1997;

assign sext_ln215_9_fu_921_p1 = data_array_8_reg_2004;

assign sext_ln215_fu_573_p1 = data_array_reg_1976;

assign sext_ln244_fu_1915_p1 = $signed(invert_table_q0);

assign sext_ln50_1_fu_1707_p1 = select_ln50_16_fu_1695_p3;

assign sext_ln50_2_fu_1799_p1 = select_ln50_1_fu_1789_p3;

assign sext_ln50_3_fu_1411_p1 = select_ln50_4_fu_1359_p3;

assign sext_ln50_4_fu_1415_p1 = select_ln50_6_fu_1403_p3;

assign sext_ln50_5_fu_1601_p1 = select_ln50_11_fu_1549_p3;

assign sext_ln50_6_fu_1605_p1 = select_ln50_13_fu_1593_p3;

assign sext_ln50_fu_1703_p1 = select_ln50_9_fu_1505_p3;

assign sub_ln215_1_fu_623_p2 = ($signed(sext_ln215_2_fu_620_p1) - $signed(sext_ln215_1_fu_576_p1));

assign sub_ln215_2_fu_666_p2 = ($signed(sext_ln215_3_fu_663_p1) - $signed(sext_ln215_1_fu_576_p1));

assign sub_ln215_3_fu_709_p2 = ($signed(sext_ln215_4_fu_706_p1) - $signed(sext_ln215_1_fu_576_p1));

assign sub_ln215_4_fu_752_p2 = ($signed(sext_ln215_5_fu_749_p1) - $signed(sext_ln215_1_fu_576_p1));

assign sub_ln215_5_fu_795_p2 = ($signed(sext_ln215_6_fu_792_p1) - $signed(sext_ln215_1_fu_576_p1));

assign sub_ln215_6_fu_838_p2 = ($signed(sext_ln215_7_fu_835_p1) - $signed(sext_ln215_1_fu_576_p1));

assign sub_ln215_7_fu_881_p2 = ($signed(sext_ln215_8_fu_878_p1) - $signed(sext_ln215_1_fu_576_p1));

assign sub_ln215_8_fu_924_p2 = ($signed(sext_ln215_9_fu_921_p1) - $signed(sext_ln215_1_fu_576_p1));

assign sub_ln215_9_fu_967_p2 = ($signed(sext_ln215_10_fu_964_p1) - $signed(sext_ln215_1_fu_576_p1));

assign sub_ln215_fu_580_p2 = ($signed(sext_ln215_fu_573_p1) - $signed(sext_ln215_1_fu_576_p1));

assign tmp_10_fu_586_p3 = sub_ln215_fu_580_p2[32'd16];

assign tmp_11_fu_594_p3 = sub_ln215_fu_580_p2[32'd15];

assign tmp_12_fu_629_p3 = sub_ln215_1_fu_623_p2[32'd16];

assign tmp_13_fu_637_p3 = sub_ln215_1_fu_623_p2[32'd15];

assign tmp_14_fu_672_p3 = sub_ln215_2_fu_666_p2[32'd16];

assign tmp_15_fu_680_p3 = sub_ln215_2_fu_666_p2[32'd15];

assign tmp_16_fu_715_p3 = sub_ln215_3_fu_709_p2[32'd16];

assign tmp_17_fu_723_p3 = sub_ln215_3_fu_709_p2[32'd15];

assign tmp_18_fu_758_p3 = sub_ln215_4_fu_752_p2[32'd16];

assign tmp_19_fu_766_p3 = sub_ln215_4_fu_752_p2[32'd15];

assign tmp_1_fu_1046_p4 = {{sub_ln215_1_fu_623_p2[15:6]}};

assign tmp_20_fu_801_p3 = sub_ln215_5_fu_795_p2[32'd16];

assign tmp_21_fu_809_p3 = sub_ln215_5_fu_795_p2[32'd15];

assign tmp_22_fu_844_p3 = sub_ln215_6_fu_838_p2[32'd16];

assign tmp_23_fu_852_p3 = sub_ln215_6_fu_838_p2[32'd15];

assign tmp_24_fu_887_p3 = sub_ln215_7_fu_881_p2[32'd16];

assign tmp_25_fu_895_p3 = sub_ln215_7_fu_881_p2[32'd15];

assign tmp_26_fu_930_p3 = sub_ln215_8_fu_924_p2[32'd16];

assign tmp_27_fu_938_p3 = sub_ln215_8_fu_924_p2[32'd15];

assign tmp_28_fu_973_p3 = sub_ln215_9_fu_967_p2[32'd16];

assign tmp_29_fu_981_p3 = sub_ln215_9_fu_967_p2[32'd15];

assign tmp_2_fu_1077_p4 = {{sub_ln215_2_fu_666_p2[15:6]}};

assign tmp_30_fu_1335_p3 = add_ln50_5_fu_1329_p2[32'd17];

assign tmp_31_fu_1343_p3 = add_ln50_5_fu_1329_p2[32'd17];

assign tmp_32_fu_1379_p3 = add_ln50_6_fu_1373_p2[32'd17];

assign tmp_33_fu_1387_p3 = add_ln50_6_fu_1373_p2[32'd17];

assign tmp_34_fu_1425_p3 = add_ln50_7_fu_1419_p2[32'd18];

assign tmp_35_fu_1439_p3 = add_ln50_8_fu_1433_p2[32'd17];

assign tmp_36_fu_1525_p3 = add_ln50_9_fu_1519_p2[32'd17];

assign tmp_37_fu_1533_p3 = add_ln50_9_fu_1519_p2[32'd17];

assign tmp_38_fu_1569_p3 = add_ln50_10_fu_1563_p2[32'd17];

assign tmp_39_fu_1577_p3 = add_ln50_10_fu_1563_p2[32'd17];

assign tmp_3_fu_1108_p4 = {{sub_ln215_3_fu_709_p2[15:6]}};

assign tmp_40_fu_1615_p3 = add_ln50_11_fu_1609_p2[32'd18];

assign tmp_41_fu_1629_p3 = add_ln50_12_fu_1623_p2[32'd17];

assign tmp_44_fu_1751_p3 = add_ln50_2_fu_1739_p2[32'd17];

assign tmp_45_fu_1812_p3 = add_ln50_3_fu_1806_p2[32'd18];

assign tmp_46_fu_1826_p3 = add_ln50_4_fu_1820_p2[32'd17];

assign tmp_4_fu_1139_p4 = {{sub_ln215_4_fu_752_p2[15:6]}};

assign tmp_5_fu_1170_p4 = {{sub_ln215_5_fu_795_p2[15:6]}};

assign tmp_6_fu_1201_p4 = {{sub_ln215_6_fu_838_p2[15:6]}};

assign tmp_7_fu_1232_p4 = {{sub_ln215_7_fu_881_p2[15:6]}};

assign tmp_8_fu_1263_p4 = {{sub_ln215_8_fu_924_p2[15:6]}};

assign tmp_9_fu_1876_p4 = {{add_ln50_4_fu_1820_p2[17:8]}};

assign tmp_fu_1015_p4 = {{sub_ln215_fu_580_p2[15:6]}};

assign tmp_s_fu_1289_p4 = {{sub_ln215_9_fu_967_p2[15:6]}};

assign x_max_fu_567_p3 = ((xor_ln65_8_fu_561_p2[0:0] == 1'b1) ? select_ln65_6_reg_2046 : select_ln65_7_reg_2052);

assign xor_ln215_10_fu_817_p2 = (tmp_20_fu_801_p3 ^ 1'd1);

assign xor_ln215_11_fu_829_p2 = (tmp_21_fu_809_p3 ^ tmp_20_fu_801_p3);

assign xor_ln215_12_fu_860_p2 = (tmp_22_fu_844_p3 ^ 1'd1);

assign xor_ln215_13_fu_872_p2 = (tmp_23_fu_852_p3 ^ tmp_22_fu_844_p3);

assign xor_ln215_14_fu_903_p2 = (tmp_24_fu_887_p3 ^ 1'd1);

assign xor_ln215_15_fu_915_p2 = (tmp_25_fu_895_p3 ^ tmp_24_fu_887_p3);

assign xor_ln215_16_fu_946_p2 = (tmp_26_fu_930_p3 ^ 1'd1);

assign xor_ln215_17_fu_958_p2 = (tmp_27_fu_938_p3 ^ tmp_26_fu_930_p3);

assign xor_ln215_18_fu_989_p2 = (tmp_28_fu_973_p3 ^ 1'd1);

assign xor_ln215_19_fu_1001_p2 = (tmp_29_fu_981_p3 ^ tmp_28_fu_973_p3);

assign xor_ln215_1_fu_614_p2 = (tmp_11_fu_594_p3 ^ tmp_10_fu_586_p3);

assign xor_ln215_2_fu_645_p2 = (tmp_12_fu_629_p3 ^ 1'd1);

assign xor_ln215_3_fu_657_p2 = (tmp_13_fu_637_p3 ^ tmp_12_fu_629_p3);

assign xor_ln215_4_fu_688_p2 = (tmp_14_fu_672_p3 ^ 1'd1);

assign xor_ln215_5_fu_700_p2 = (tmp_15_fu_680_p3 ^ tmp_14_fu_672_p3);

assign xor_ln215_6_fu_731_p2 = (tmp_16_fu_715_p3 ^ 1'd1);

assign xor_ln215_7_fu_743_p2 = (tmp_17_fu_723_p3 ^ tmp_16_fu_715_p3);

assign xor_ln215_8_fu_774_p2 = (tmp_18_fu_758_p3 ^ 1'd1);

assign xor_ln215_9_fu_786_p2 = (tmp_19_fu_766_p3 ^ tmp_18_fu_758_p3);

assign xor_ln215_fu_602_p2 = (tmp_10_fu_586_p3 ^ 1'd1);

assign xor_ln50_10_fu_1637_p2 = (tmp_40_fu_1615_p3 ^ 1'd1);

assign xor_ln50_11_fu_1649_p2 = (tmp_41_fu_1629_p3 ^ 1'd1);

assign xor_ln50_12_fu_1661_p2 = (tmp_41_fu_1629_p3 ^ tmp_40_fu_1615_p3);

assign xor_ln50_13_fu_1667_p2 = (xor_ln50_12_fu_1661_p2 ^ 1'd1);

assign xor_ln50_1_fu_1777_p2 = (tmp_43_reg_2187 ^ tmp_42_reg_2176);

assign xor_ln50_2_fu_1834_p2 = (tmp_45_fu_1812_p3 ^ 1'd1);

assign xor_ln50_3_fu_1846_p2 = (tmp_46_fu_1826_p3 ^ 1'd1);

assign xor_ln50_4_fu_1858_p2 = (tmp_46_fu_1826_p3 ^ tmp_45_fu_1812_p3);

assign xor_ln50_5_fu_1864_p2 = (xor_ln50_4_fu_1858_p2 ^ 1'd1);

assign xor_ln50_6_fu_1447_p2 = (tmp_34_fu_1425_p3 ^ 1'd1);

assign xor_ln50_7_fu_1459_p2 = (tmp_35_fu_1439_p3 ^ 1'd1);

assign xor_ln50_8_fu_1471_p2 = (tmp_35_fu_1439_p3 ^ tmp_34_fu_1425_p3);

assign xor_ln50_9_fu_1477_p2 = (xor_ln50_8_fu_1471_p2 ^ 1'd1);

assign xor_ln50_fu_1767_p2 = (tmp_42_reg_2176 ^ 1'd1);

assign xor_ln65_1_fu_437_p2 = (icmp_ln65_1_fu_433_p2 ^ 1'd1);

assign xor_ln65_2_fu_455_p2 = (icmp_ln65_2_fu_449_p2 ^ 1'd1);

assign xor_ln65_3_fu_473_p2 = (icmp_ln65_3_fu_469_p2 ^ 1'd1);

assign xor_ln65_4_fu_489_p2 = (icmp_ln65_4_fu_485_p2 ^ 1'd1);

assign xor_ln65_5_fu_507_p2 = (icmp_ln65_5_fu_501_p2 ^ 1'd1);

assign xor_ln65_6_fu_527_p2 = (icmp_ln65_6_fu_521_p2 ^ 1'd1);

assign xor_ln65_7_fu_545_p2 = (icmp_ln65_7_fu_541_p2 ^ 1'd1);

assign xor_ln65_8_fu_561_p2 = (icmp_ln65_8_fu_557_p2 ^ 1'd1);

assign xor_ln65_fu_421_p2 = (icmp_ln65_fu_417_p2 ^ 1'd1);

assign zext_ln215_fu_1315_p1 = exp_table_q1;

assign zext_ln219_fu_1319_p1 = exp_table_q0;

assign zext_ln225_1_fu_1064_p1 = select_ln215_3_fu_1056_p3;

assign zext_ln225_2_fu_1095_p1 = select_ln215_5_fu_1087_p3;

assign zext_ln225_3_fu_1126_p1 = select_ln215_7_fu_1118_p3;

assign zext_ln225_4_fu_1157_p1 = select_ln215_9_fu_1149_p3;

assign zext_ln225_5_fu_1188_p1 = select_ln215_11_fu_1180_p3;

assign zext_ln225_6_fu_1219_p1 = select_ln215_13_fu_1211_p3;

assign zext_ln225_7_fu_1250_p1 = select_ln215_15_fu_1242_p3;

assign zext_ln225_8_fu_1307_p1 = select_ln215_17_reg_2098;

assign zext_ln225_9_fu_1311_p1 = select_ln215_19_reg_2103;

assign zext_ln225_fu_1033_p1 = select_ln215_1_fu_1025_p3;

assign zext_ln235_fu_1910_p1 = select_ln50_19_fu_1902_p3;

assign zext_ln244_1_fu_1924_p1 = exp_res_1_reg_2114;

assign zext_ln244_2_fu_1928_p1 = exp_res_2_reg_2120;

assign zext_ln244_3_fu_1932_p1 = exp_res_3_reg_2126;

assign zext_ln244_4_fu_1936_p1 = exp_res_4_reg_2132;

assign zext_ln244_5_fu_1940_p1 = exp_res_5_reg_2138;

assign zext_ln244_6_fu_1944_p1 = exp_res_6_reg_2144;

assign zext_ln244_7_fu_1948_p1 = exp_res_7_reg_2150;

assign zext_ln244_8_fu_1952_p1 = exp_res_8_reg_2166;

assign zext_ln244_9_fu_1956_p1 = exp_res_9_reg_2171;

assign zext_ln244_fu_1920_p1 = exp_res_reg_2108;

assign zext_ln50_1_fu_1326_p1 = exp_res_1_reg_2114;

assign zext_ln50_2_fu_1367_p1 = exp_res_2_reg_2120;

assign zext_ln50_3_fu_1370_p1 = exp_res_3_reg_2126;

assign zext_ln50_4_fu_1513_p1 = exp_res_4_reg_2132;

assign zext_ln50_5_fu_1516_p1 = exp_res_5_reg_2138;

assign zext_ln50_6_fu_1557_p1 = exp_res_6_reg_2144;

assign zext_ln50_7_fu_1560_p1 = exp_res_7_reg_2150;

assign zext_ln50_8_fu_1796_p1 = select_ln50_2_reg_2193;

assign zext_ln50_9_fu_1803_p1 = select_ln50_2_reg_2193;

assign zext_ln50_fu_1323_p1 = exp_res_reg_2108;

endmodule //myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config12_s
