// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer3_out_dout,
        layer3_out_empty_n,
        layer3_out_read,
        layer4_out_din,
        layer4_out_full_n,
        layer4_out_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] layer3_out_dout;
input   layer3_out_empty_n;
output   layer3_out_read;
output  [63:0] layer4_out_din;
input   layer4_out_full_n;
output   layer4_out_write;

reg ap_idle;
reg layer3_out_read;
reg layer4_out_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg   [0:0] icmp_ln55_reg_994;
reg   [0:0] icmp_ln55_reg_994_pp0_iter1_reg;
reg   [0:0] and_ln55_2_reg_1016;
reg    ap_predicate_op151_write_state3;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_164_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] sY_1;
reg   [31:0] pY_1;
reg   [31:0] pX_1;
reg   [31:0] sX_1;
reg   [13:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5;
reg   [13:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4;
reg   [13:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3;
reg   [13:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_17;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_16;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_15;
reg   [13:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_14;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_d0;
wire   [15:0] void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0;
reg    layer3_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer4_out_blk_n;
reg   [0:0] icmp_ln109_reg_990;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln55_fu_180_p2;
wire   [0:0] icmp_ln55_5_fu_194_p2;
reg   [0:0] icmp_ln55_5_reg_998;
wire   [0:0] icmp_ln55_6_fu_200_p2;
reg   [0:0] icmp_ln55_6_reg_1003;
wire   [0:0] icmp_ln76_fu_212_p2;
reg   [0:0] icmp_ln76_reg_1008;
wire   [0:0] icmp_ln80_fu_266_p2;
reg   [0:0] icmp_ln80_reg_1012;
wire   [0:0] and_ln55_2_fu_507_p2;
wire   [11:0] select_ln65_fu_685_p3;
reg   [11:0] select_ln65_reg_1020;
wire   [11:0] select_ln65_32_fu_705_p3;
reg   [11:0] select_ln65_32_reg_1026;
wire   [11:0] select_ln65_34_fu_725_p3;
reg   [11:0] select_ln65_34_reg_1032;
wire   [11:0] select_ln65_35_fu_745_p3;
reg   [11:0] select_ln65_35_reg_1038;
wire   [11:0] select_ln65_37_fu_765_p3;
reg   [11:0] select_ln65_37_reg_1044;
wire   [11:0] select_ln65_38_fu_785_p3;
reg   [11:0] select_ln65_38_reg_1050;
wire   [11:0] select_ln65_40_fu_805_p3;
reg   [11:0] select_ln65_40_reg_1056;
wire   [11:0] select_ln65_41_fu_825_p3;
reg   [11:0] select_ln65_41_reg_1062;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_149_p4;
wire   [31:0] add_ln86_fu_851_p2;
reg   [31:0] ap_phi_reg_pp0_iter1_storemerge_reg_145;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_reg_145;
wire   [31:0] add_ln80_fu_260_p2;
wire   [31:0] add_ln76_fu_206_p2;
wire   [31:0] add_ln91_fu_232_p2;
wire   [13:0] trunc_ln246_fu_367_p1;
wire   [13:0] trunc_ln246_7_fu_381_p1;
wire   [13:0] trunc_ln246_8_fu_395_p1;
wire   [13:0] trunc_ln201_fu_409_p1;
wire   [13:0] trunc_ln115_2_fu_293_p1;
reg   [6:0] indvar_flatten_fu_128;
wire   [6:0] add_ln109_fu_170_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] trunc_ln115_fu_289_p1;
wire   [31:0] select_ln91_fu_224_p3;
wire   [0:0] and_ln55_fu_503_p2;
wire   [0:0] icmp_ln55_4_fu_497_p2;
wire   [11:0] pool_window_fu_513_p4;
wire   [11:0] pool_window_45_fu_523_p4;
wire   [0:0] icmp_ln65_fu_673_p2;
wire   [0:0] xor_ln65_fu_679_p2;
wire   [11:0] pool_window_31_fu_533_p4;
wire   [11:0] pool_window_32_fu_543_p4;
wire   [0:0] icmp_ln65_32_fu_693_p2;
wire   [0:0] xor_ln65_32_fu_699_p2;
wire   [11:0] pool_window_33_fu_553_p4;
wire   [11:0] pool_window_34_fu_563_p4;
wire   [0:0] icmp_ln65_34_fu_713_p2;
wire   [0:0] xor_ln65_34_fu_719_p2;
wire   [11:0] pool_window_35_fu_573_p4;
wire   [11:0] pool_window_36_fu_583_p4;
wire   [0:0] icmp_ln65_35_fu_733_p2;
wire   [0:0] xor_ln65_35_fu_739_p2;
wire   [11:0] pool_window_37_fu_593_p4;
wire   [11:0] pool_window_38_fu_603_p4;
wire   [0:0] icmp_ln65_37_fu_753_p2;
wire   [0:0] xor_ln65_37_fu_759_p2;
wire   [11:0] pool_window_39_fu_613_p4;
wire   [11:0] pool_window_40_fu_623_p4;
wire   [0:0] icmp_ln65_38_fu_773_p2;
wire   [0:0] xor_ln65_38_fu_779_p2;
wire   [11:0] pool_window_41_fu_633_p4;
wire   [11:0] pool_window_42_fu_643_p4;
wire   [0:0] icmp_ln65_40_fu_793_p2;
wire   [0:0] xor_ln65_40_fu_799_p2;
wire   [11:0] pool_window_43_fu_653_p4;
wire   [11:0] pool_window_44_fu_663_p4;
wire   [0:0] icmp_ln65_41_fu_813_p2;
wire   [0:0] xor_ln65_41_fu_819_p2;
wire   [0:0] icmp_ln86_fu_837_p2;
wire   [31:0] select_ln86_fu_843_p3;
wire   [0:0] icmp_ln65_33_fu_864_p2;
wire   [0:0] xor_ln65_33_fu_868_p2;
wire   [11:0] select_ln65_33_fu_874_p3;
wire   [13:0] res_pack_fu_880_p3;
wire   [0:0] icmp_ln65_36_fu_892_p2;
wire   [0:0] xor_ln65_36_fu_896_p2;
wire   [11:0] select_ln65_36_fu_902_p3;
wire   [13:0] res_pack_4_fu_908_p3;
wire   [0:0] icmp_ln65_39_fu_920_p2;
wire   [0:0] xor_ln65_39_fu_924_p2;
wire   [11:0] select_ln65_39_fu_930_p3;
wire   [13:0] res_pack_5_fu_936_p3;
wire   [0:0] icmp_ln65_42_fu_948_p2;
wire   [0:0] xor_ln65_42_fu_952_p2;
wire   [11:0] select_ln65_42_fu_958_p3;
wire  signed [15:0] sext_ln42_8_fu_944_p1;
wire  signed [15:0] sext_ln42_7_fu_916_p1;
wire  signed [15:0] sext_ln42_fu_888_p1;
wire   [61:0] or_ln72_s_fu_964_p6;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_200;
reg    ap_condition_198;
reg    ap_condition_265;
reg    ap_condition_224;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 sY_1 = 32'd0;
#0 pY_1 = 32'd0;
#0 pX_1 = 32'd0;
#0 sX_1 = 32'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 = 14'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 = 14'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 = 14'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_17 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_16 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_15 = 14'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_14 = 14'd0;
#0 ap_done_reg = 1'b0;
end

myproject_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config4_s_void_poeOg #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0),
    .d0(trunc_ln115_fu_289_p1),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0)
);

myproject_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config4_s_void_poeOg #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0)
);

myproject_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config4_s_void_poeOg #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0)
);

myproject_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config4_s_void_poeOg #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(3'd7),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0)
);

myproject_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_198)) begin
        if ((1'b1 == ap_condition_200)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_145 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_145 <= ap_phi_reg_pp0_iter0_storemerge_reg_145;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_164_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_128 <= add_ln109_fu_170_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_128 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_265)) begin
        if ((icmp_ln76_fu_212_p2 == 1'd1)) begin
            pX_1 <= 32'd0;
        end else if ((icmp_ln76_fu_212_p2 == 1'd0)) begin
            pX_1 <= add_ln76_fu_206_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_224)) begin
        if ((icmp_ln80_fu_266_p2 == 1'd1)) begin
            pY_1 <= 32'd0;
        end else if ((icmp_ln80_fu_266_p2 == 1'd0)) begin
            pY_1 <= add_ln80_fu_260_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_265)) begin
        if ((icmp_ln76_fu_212_p2 == 1'd1)) begin
            sX_1 <= 32'd0;
        end else if ((icmp_ln76_fu_212_p2 == 1'd0)) begin
            sX_1 <= add_ln91_fu_232_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln55_reg_994 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln55_2_reg_1016 <= and_ln55_2_fu_507_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln109_reg_990 <= icmp_ln109_fu_164_p2;
        icmp_ln55_reg_994_pp0_iter1_reg <= icmp_ln55_reg_994;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln55_fu_180_p2 == 1'd1))) begin
        icmp_ln55_5_reg_998 <= icmp_ln55_5_fu_194_p2;
        icmp_ln55_6_reg_1003 <= icmp_ln55_6_fu_200_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln55_reg_994 <= icmp_ln55_fu_180_p2;
        icmp_ln76_reg_1008 <= icmp_ln76_fu_212_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln76_fu_212_p2 == 1'd1))) begin
        icmp_ln80_reg_1012 <= icmp_ln80_fu_266_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_14 <= {{layer3_out_dout[61:48]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_15 <= {{layer3_out_dout[45:32]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_16 <= {{layer3_out_dout[29:16]}};
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_17 <= trunc_ln115_2_fu_293_p1;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 <= trunc_ln201_fu_409_p1;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 <= trunc_ln246_8_fu_395_p1;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 <= trunc_ln246_7_fu_381_p1;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 <= trunc_ln246_fu_367_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln76_reg_1008 == 1'd1))) begin
        sY_1 <= ap_phi_mux_storemerge_phi_fu_149_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln55_2_fu_507_p2) & (icmp_ln55_reg_994 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln65_32_reg_1026 <= select_ln65_32_fu_705_p3;
        select_ln65_34_reg_1032 <= select_ln65_34_fu_725_p3;
        select_ln65_35_reg_1038 <= select_ln65_35_fu_745_p3;
        select_ln65_37_reg_1044 <= select_ln65_37_fu_765_p3;
        select_ln65_38_reg_1050 <= select_ln65_38_fu_785_p3;
        select_ln65_40_reg_1056 <= select_ln65_40_fu_805_p3;
        select_ln65_41_reg_1062 <= select_ln65_41_fu_825_p3;
        select_ln65_reg_1020 <= select_ln65_fu_685_p3;
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_164_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_reg_1012 == 1'd0) & (icmp_ln76_reg_1008 == 1'd1) & (icmp_ln109_reg_990 == 1'd0))) begin
        ap_phi_mux_storemerge_phi_fu_149_p4 = add_ln86_fu_851_p2;
    end else begin
        ap_phi_mux_storemerge_phi_fu_149_p4 = ap_phi_reg_pp0_iter1_storemerge_reg_145;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer3_out_blk_n = layer3_out_empty_n;
    end else begin
        layer3_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer3_out_read = 1'b1;
    end else begin
        layer3_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op151_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op151_write_state3 == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer4_out_write = 1'b1;
    end else begin
        layer4_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_170_p2 = (ap_sig_allocacmp_indvar_flatten_load + 7'd1);

assign add_ln76_fu_206_p2 = (pX_1 + 32'd1);

assign add_ln80_fu_260_p2 = (pY_1 + 32'd1);

assign add_ln86_fu_851_p2 = (sY_1 + select_ln86_fu_843_p3);

assign add_ln91_fu_232_p2 = (sX_1 + select_ln91_fu_224_p3);

assign and_ln55_2_fu_507_p2 = (icmp_ln55_4_fu_497_p2 & and_ln55_fu_503_p2);

assign and_ln55_fu_503_p2 = (icmp_ln55_6_reg_1003 & icmp_ln55_5_reg_998);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_predicate_op151_write_state3 == 1'b1) & (layer4_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer3_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_predicate_op151_write_state3 == 1'b1) & (layer4_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer3_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_predicate_op151_write_state3 == 1'b1) & (layer4_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer3_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer3_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((ap_predicate_op151_write_state3 == 1'b1) & (layer4_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_198 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_200 = ((icmp_ln109_fu_164_p2 == 1'd0) & (icmp_ln80_fu_266_p2 == 1'd1) & (icmp_ln76_fu_212_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_224 = ((icmp_ln109_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln76_fu_212_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_265 = ((icmp_ln109_fu_164_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_storemerge_reg_145 = 'bx;

always @ (*) begin
    ap_predicate_op151_write_state3 = ((1'd1 == and_ln55_2_reg_1016) & (icmp_ln55_reg_994_pp0_iter1_reg == 1'd1));
end

assign icmp_ln109_fu_164_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln55_4_fu_497_p2 = ((sY_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln55_5_fu_194_p2 = (($signed(pY_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_6_fu_200_p2 = (($signed(pX_1) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_180_p2 = ((sX_1 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln65_32_fu_693_p2 = (($signed(pool_window_31_fu_533_p4) < $signed(pool_window_32_fu_543_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_33_fu_864_p2 = (($signed(select_ln65_reg_1020) < $signed(select_ln65_32_reg_1026)) ? 1'b1 : 1'b0);

assign icmp_ln65_34_fu_713_p2 = (($signed(pool_window_33_fu_553_p4) < $signed(pool_window_34_fu_563_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_35_fu_733_p2 = (($signed(pool_window_35_fu_573_p4) < $signed(pool_window_36_fu_583_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_36_fu_892_p2 = (($signed(select_ln65_34_reg_1032) < $signed(select_ln65_35_reg_1038)) ? 1'b1 : 1'b0);

assign icmp_ln65_37_fu_753_p2 = (($signed(pool_window_37_fu_593_p4) < $signed(pool_window_38_fu_603_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_38_fu_773_p2 = (($signed(pool_window_39_fu_613_p4) < $signed(pool_window_40_fu_623_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_39_fu_920_p2 = (($signed(select_ln65_37_reg_1044) < $signed(select_ln65_38_reg_1050)) ? 1'b1 : 1'b0);

assign icmp_ln65_40_fu_793_p2 = (($signed(pool_window_41_fu_633_p4) < $signed(pool_window_42_fu_643_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_41_fu_813_p2 = (($signed(pool_window_43_fu_653_p4) < $signed(pool_window_44_fu_663_p4)) ? 1'b1 : 1'b0);

assign icmp_ln65_42_fu_948_p2 = (($signed(select_ln65_40_reg_1056) < $signed(select_ln65_41_reg_1062)) ? 1'b1 : 1'b0);

assign icmp_ln65_fu_673_p2 = (($signed(pool_window_fu_513_p4) < $signed(pool_window_45_fu_523_p4)) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_212_p2 = ((add_ln76_fu_206_p2 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_266_p2 = ((add_ln80_fu_260_p2 == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_837_p2 = ((sY_1 == 32'd1) ? 1'b1 : 1'b0);

assign layer4_out_din = $signed(or_ln72_s_fu_964_p6);

assign or_ln72_s_fu_964_p6 = {{{{{select_ln65_42_fu_958_p3}, {2'd0}}, {sext_ln42_8_fu_944_p1}}, {sext_ln42_7_fu_916_p1}}, {sext_ln42_fu_888_p1}};

assign pool_window_31_fu_533_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_17[13:2]}};

assign pool_window_32_fu_543_p4 = {{layer3_out_dout[13:2]}};

assign pool_window_33_fu_553_p4 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4[13:2]}};

assign pool_window_34_fu_563_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0[13:2]}};

assign pool_window_35_fu_573_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_16[13:2]}};

assign pool_window_36_fu_583_p4 = {{layer3_out_dout[29:18]}};

assign pool_window_37_fu_593_p4 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3[13:2]}};

assign pool_window_38_fu_603_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0[13:2]}};

assign pool_window_39_fu_613_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_15[13:2]}};

assign pool_window_40_fu_623_p4 = {{layer3_out_dout[45:34]}};

assign pool_window_41_fu_633_p4 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2[13:2]}};

assign pool_window_42_fu_643_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0[13:2]}};

assign pool_window_43_fu_653_p4 = {{p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_14[13:2]}};

assign pool_window_44_fu_663_p4 = {{layer3_out_dout[61:50]}};

assign pool_window_45_fu_523_p4 = {{void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0[13:2]}};

assign pool_window_fu_513_p4 = {{void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5[13:2]}};

assign res_pack_4_fu_908_p3 = {{select_ln65_36_fu_902_p3}, {2'd0}};

assign res_pack_5_fu_936_p3 = {{select_ln65_39_fu_930_p3}, {2'd0}};

assign res_pack_fu_880_p3 = {{select_ln65_33_fu_874_p3}, {2'd0}};

assign select_ln65_32_fu_705_p3 = ((xor_ln65_32_fu_699_p2[0:0] == 1'b1) ? pool_window_31_fu_533_p4 : pool_window_32_fu_543_p4);

assign select_ln65_33_fu_874_p3 = ((xor_ln65_33_fu_868_p2[0:0] == 1'b1) ? select_ln65_reg_1020 : select_ln65_32_reg_1026);

assign select_ln65_34_fu_725_p3 = ((xor_ln65_34_fu_719_p2[0:0] == 1'b1) ? pool_window_33_fu_553_p4 : pool_window_34_fu_563_p4);

assign select_ln65_35_fu_745_p3 = ((xor_ln65_35_fu_739_p2[0:0] == 1'b1) ? pool_window_35_fu_573_p4 : pool_window_36_fu_583_p4);

assign select_ln65_36_fu_902_p3 = ((xor_ln65_36_fu_896_p2[0:0] == 1'b1) ? select_ln65_34_reg_1032 : select_ln65_35_reg_1038);

assign select_ln65_37_fu_765_p3 = ((xor_ln65_37_fu_759_p2[0:0] == 1'b1) ? pool_window_37_fu_593_p4 : pool_window_38_fu_603_p4);

assign select_ln65_38_fu_785_p3 = ((xor_ln65_38_fu_779_p2[0:0] == 1'b1) ? pool_window_39_fu_613_p4 : pool_window_40_fu_623_p4);

assign select_ln65_39_fu_930_p3 = ((xor_ln65_39_fu_924_p2[0:0] == 1'b1) ? select_ln65_37_reg_1044 : select_ln65_38_reg_1050);

assign select_ln65_40_fu_805_p3 = ((xor_ln65_40_fu_799_p2[0:0] == 1'b1) ? pool_window_41_fu_633_p4 : pool_window_42_fu_643_p4);

assign select_ln65_41_fu_825_p3 = ((xor_ln65_41_fu_819_p2[0:0] == 1'b1) ? pool_window_43_fu_653_p4 : pool_window_44_fu_663_p4);

assign select_ln65_42_fu_958_p3 = ((xor_ln65_42_fu_952_p2[0:0] == 1'b1) ? select_ln65_40_reg_1056 : select_ln65_41_reg_1062);

assign select_ln65_fu_685_p3 = ((xor_ln65_fu_679_p2[0:0] == 1'b1) ? pool_window_fu_513_p4 : pool_window_45_fu_523_p4);

assign select_ln86_fu_843_p3 = ((icmp_ln86_fu_837_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign select_ln91_fu_224_p3 = ((icmp_ln55_fu_180_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign sext_ln42_7_fu_916_p1 = $signed(res_pack_4_fu_908_p3);

assign sext_ln42_8_fu_944_p1 = $signed(res_pack_5_fu_936_p3);

assign sext_ln42_fu_888_p1 = $signed(res_pack_fu_880_p3);

assign trunc_ln115_2_fu_293_p1 = layer3_out_dout[13:0];

assign trunc_ln115_fu_289_p1 = layer3_out_dout[15:0];

assign trunc_ln201_fu_409_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_q0[13:0];

assign trunc_ln246_7_fu_381_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_q0[13:0];

assign trunc_ln246_8_fu_395_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_q0[13:0];

assign trunc_ln246_fu_367_p1 = void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_3_q0[13:0];

assign void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_1_d0 = {{layer3_out_dout[47:32]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_2_d0 = {{layer3_out_dout[31:16]}};

assign void_pooling2d_cl_stream_stream_array_ap_fixed_4u_0_line_buffer_d0 = {{layer3_out_dout[63:48]}};

assign xor_ln65_32_fu_699_p2 = (icmp_ln65_32_fu_693_p2 ^ 1'd1);

assign xor_ln65_33_fu_868_p2 = (icmp_ln65_33_fu_864_p2 ^ 1'd1);

assign xor_ln65_34_fu_719_p2 = (icmp_ln65_34_fu_713_p2 ^ 1'd1);

assign xor_ln65_35_fu_739_p2 = (icmp_ln65_35_fu_733_p2 ^ 1'd1);

assign xor_ln65_36_fu_896_p2 = (icmp_ln65_36_fu_892_p2 ^ 1'd1);

assign xor_ln65_37_fu_759_p2 = (icmp_ln65_37_fu_753_p2 ^ 1'd1);

assign xor_ln65_38_fu_779_p2 = (icmp_ln65_38_fu_773_p2 ^ 1'd1);

assign xor_ln65_39_fu_924_p2 = (icmp_ln65_39_fu_920_p2 ^ 1'd1);

assign xor_ln65_40_fu_799_p2 = (icmp_ln65_40_fu_793_p2 ^ 1'd1);

assign xor_ln65_41_fu_819_p2 = (icmp_ln65_41_fu_813_p2 ^ 1'd1);

assign xor_ln65_42_fu_952_p2 = (icmp_ln65_42_fu_948_p2 ^ 1'd1);

assign xor_ln65_fu_679_p2 = (icmp_ln65_fu_673_p2 ^ 1'd1);

endmodule //myproject_pooling2d_cl_array_ap_fixed_4u_array_ap_fixed_16_6_5_3_0_4u_config4_s
