// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_elem_0_0_0_0_0_val,
        layer2_out_din,
        layer2_out_full_n,
        layer2_out_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] in_elem_0_0_0_0_0_val;
output  [63:0] layer2_out_din;
input   layer2_out_full_n;
output   layer2_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer2_out_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
reg   [15:0] void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
reg   [31:0] sX_3;
reg   [31:0] sY_3;
reg   [31:0] pY_3;
reg   [31:0] pX_3;
reg    layer2_out_blk_n;
wire    ap_CS_fsm_state4;
reg   [0:0] icmp_ln289_reg_333;
reg   [0:0] and_ln289_2_reg_347;
wire   [0:0] icmp_ln289_fu_152_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] and_ln289_2_fu_209_p2;
reg   [15:0] res_out_reg_351;
wire    ap_CS_fsm_state3;
reg   [15:0] res_out_14_reg_356;
reg   [15:0] res_out_15_reg_361;
reg   [15:0] res_out_16_reg_366;
reg    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_ap_start;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_ap_done;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_ap_idle;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_ap_ready;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld;
wire   [15:0] call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
wire    call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld;
wire    grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_start;
wire    grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_done;
wire    grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_idle;
wire    grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_ready;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_0;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_1;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_2;
wire   [15:0] grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_3;
wire   [31:0] select_ln323_fu_309_p3;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_84_p4;
reg    ap_predicate_op29_write_state4;
reg    ap_block_state4;
wire   [0:0] icmp_ln313_fu_245_p2;
wire   [0:0] icmp_ln317_fu_292_p2;
reg    grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_start_reg;
wire   [31:0] select_ln328_fu_262_p3;
wire   [31:0] add_ln317_fu_287_p2;
wire   [31:0] add_ln313_fu_240_p2;
wire   [30:0] tmp_fu_171_p4;
wire   [30:0] tmp_48_fu_187_p4;
wire   [0:0] icmp_ln289_5_fu_181_p2;
wire   [0:0] icmp_ln289_6_fu_197_p2;
wire   [0:0] and_ln289_fu_203_p2;
wire   [0:0] grp_fu_143_p2;
wire   [31:0] add_ln328_fu_257_p2;
wire   [31:0] add_ln323_fu_304_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_condition_137;
reg    ap_condition_234;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15 = 16'd0;
#0 void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12 = 16'd0;
#0 sX_3 = 32'd0;
#0 sY_3 = 32'd0;
#0 pY_3 = 32'd0;
#0 pX_3 = 32'd0;
#0 grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_start_reg = 1'b0;
end

myproject_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_ap_start),
    .ap_done(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_ap_done),
    .ap_idle(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_ap_idle),
    .ap_ready(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_ap_ready),
    .in_elem_0_0_0_0_0_val(in_elem_0_0_0_0_0_val),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_i(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld(call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld)
);

myproject_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_start),
    .ap_done(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_done),
    .ap_idle(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_idle),
    .ap_ready(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_ready),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11),
    .void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10(void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10),
    .ap_return_0(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_0),
    .ap_return_1(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_1),
    .ap_return_2(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_2),
    .ap_return_3(grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln289_fu_152_p2 == 1'd1) & (1'd1 == and_ln289_2_fu_209_p2) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_start_reg <= 1'b1;
        end else if ((grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_ready == 1'b1)) begin
            grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_137)) begin
        if ((icmp_ln313_fu_245_p2 == 1'd1)) begin
            pX_3 <= 32'd0;
        end else if ((icmp_ln313_fu_245_p2 == 1'd0)) begin
            pX_3 <= add_ln313_fu_240_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_234)) begin
        if ((icmp_ln317_fu_292_p2 == 1'd1)) begin
            pY_3 <= 32'd0;
        end else if ((icmp_ln317_fu_292_p2 == 1'd0)) begin
            pY_3 <= add_ln317_fu_287_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_137)) begin
        if ((icmp_ln313_fu_245_p2 == 1'd1)) begin
            sX_3 <= 32'd0;
        end else if ((icmp_ln313_fu_245_p2 == 1'd0)) begin
            sX_3 <= select_ln328_fu_262_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln289_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        and_ln289_2_reg_347 <= and_ln289_2_fu_209_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln289_reg_333 <= icmp_ln289_fu_152_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        res_out_14_reg_356 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_1;
        res_out_15_reg_361 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_2;
        res_out_16_reg_366 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_3;
        res_out_reg_351 <= grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((layer2_out_full_n == 1'b0) & (ap_predicate_op29_write_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln313_fu_245_p2 == 1'd1))) begin
        sY_3 <= ap_phi_mux_storemerge_phi_fu_84_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_10_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_11_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_12;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_13_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_14_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_15;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_16_o;
    end
end

always @ (posedge ap_clk) begin
    if (((call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_17_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18_ap_vld == 1'b1))) begin
        void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18 <= call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_void_compute_output_buffer_2d_array_const_ap_shift_reg_n_chan_stream_weig_18;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer2_out_full_n == 1'b0) & (ap_predicate_op29_write_state4 == 1'b1))) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((~((layer2_out_full_n == 1'b0) & (ap_predicate_op29_write_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (icmp_ln313_fu_245_p2 == 1'd1))) begin
        if ((icmp_ln317_fu_292_p2 == 1'd1)) begin
            ap_phi_mux_storemerge_phi_fu_84_p4 = 32'd0;
        end else if ((icmp_ln317_fu_292_p2 == 1'd0)) begin
            ap_phi_mux_storemerge_phi_fu_84_p4 = select_ln323_fu_309_p3;
        end else begin
            ap_phi_mux_storemerge_phi_fu_84_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_storemerge_phi_fu_84_p4 = 'bx;
    end
end

always @ (*) begin
    if ((~((layer2_out_full_n == 1'b0) & (ap_predicate_op29_write_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_ap_start = 1'b1;
    end else begin
        call_ln286_shift_line_buffer_array_ap_fixed_16_6_5_3_0_1u_config2_s_fu_91_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln289_2_reg_347) & (icmp_ln289_reg_333 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        layer2_out_blk_n = layer2_out_full_n;
    end else begin
        layer2_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer2_out_full_n == 1'b0) & (ap_predicate_op29_write_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4) & (ap_predicate_op29_write_state4 == 1'b1))) begin
        layer2_out_write = 1'b1;
    end else begin
        layer2_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln289_fu_152_p2 == 1'd1) & (1'd1 == and_ln289_2_fu_209_p2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((layer2_out_full_n == 1'b0) & (ap_predicate_op29_write_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln313_fu_240_p2 = (pX_3 + 32'd1);

assign add_ln317_fu_287_p2 = (pY_3 + 32'd1);

assign add_ln323_fu_304_p2 = (sY_3 + 32'd1);

assign add_ln328_fu_257_p2 = (sX_3 + 32'd1);

assign and_ln289_2_fu_209_p2 = (grp_fu_143_p2 & and_ln289_fu_203_p2);

assign and_ln289_fu_203_p2 = (icmp_ln289_6_fu_197_p2 & icmp_ln289_5_fu_181_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state4 = ((layer2_out_full_n == 1'b0) & (ap_predicate_op29_write_state4 == 1'b1));
end

always @ (*) begin
    ap_condition_137 = (~((layer2_out_full_n == 1'b0) & (ap_predicate_op29_write_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4));
end

always @ (*) begin
    ap_condition_234 = (~((layer2_out_full_n == 1'b0) & (ap_predicate_op29_write_state4 == 1'b1)) & (1'b1 == ap_CS_fsm_state4) & (icmp_ln313_fu_245_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op29_write_state4 = ((1'd1 == and_ln289_2_reg_347) & (icmp_ln289_reg_333 == 1'd1));
end

assign grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_start = grp_dense_resource_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_mult_s_fu_119_ap_start_reg;

assign grp_fu_143_p2 = ((sY_3 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln289_5_fu_181_p2 = (($signed(tmp_fu_171_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln289_6_fu_197_p2 = (($signed(tmp_48_fu_187_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln289_fu_152_p2 = ((sX_3 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln313_fu_245_p2 = ((add_ln313_fu_240_p2 == 32'd10) ? 1'b1 : 1'b0);

assign icmp_ln317_fu_292_p2 = ((add_ln317_fu_287_p2 == 32'd10) ? 1'b1 : 1'b0);

assign layer2_out_din = {{{{res_out_16_reg_366}, {res_out_15_reg_361}}, {res_out_14_reg_356}}, {res_out_reg_351}};

assign select_ln323_fu_309_p3 = ((grp_fu_143_p2[0:0] == 1'b1) ? 32'd2 : add_ln323_fu_304_p2);

assign select_ln328_fu_262_p3 = ((icmp_ln289_reg_333[0:0] == 1'b1) ? 32'd2 : add_ln328_fu_257_p2);

assign tmp_48_fu_187_p4 = {{pX_3[31:1]}};

assign tmp_fu_171_p4 = {{pY_3[31:1]}};

endmodule //myproject_compute_output_buffer_2d_array_array_ap_fixed_16_6_5_3_0_4u_config2_s
